// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: voice/s2s/v1/federation_management.proto

package s2sv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FederationManagementService_RegisterNode_FullMethodName   = "/voice.s2s.v1.FederationManagementService/RegisterNode"
	FederationManagementService_ApproveNode_FullMethodName    = "/voice.s2s.v1.FederationManagementService/ApproveNode"
	FederationManagementService_DeactivateNode_FullMethodName = "/voice.s2s.v1.FederationManagementService/DeactivateNode"
	FederationManagementService_ListNodes_FullMethodName      = "/voice.s2s.v1.FederationManagementService/ListNodes"
	FederationManagementService_GetNodeStatus_FullMethodName  = "/voice.s2s.v1.FederationManagementService/GetNodeStatus"
	FederationManagementService_Defederate_FullMethodName     = "/voice.s2s.v1.FederationManagementService/Defederate"
)

// FederationManagementServiceClient is the client API for FederationManagementService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Control-plane API for federation nodes (master-side operators / automation; mTLS).
// Complements node↔master data plane in s2s.proto (same package).
type FederationManagementServiceClient interface {
	RegisterNode(ctx context.Context, in *RegisterNodeRequest, opts ...grpc.CallOption) (*RegisterNodeResponse, error)
	ApproveNode(ctx context.Context, in *ApproveNodeRequest, opts ...grpc.CallOption) (*ApproveNodeResponse, error)
	DeactivateNode(ctx context.Context, in *DeactivateNodeRequest, opts ...grpc.CallOption) (*DeactivateNodeResponse, error)
	ListNodes(ctx context.Context, in *ListNodesRequest, opts ...grpc.CallOption) (*ListNodesResponse, error)
	GetNodeStatus(ctx context.Context, in *GetNodeStatusRequest, opts ...grpc.CallOption) (*GetNodeStatusResponse, error)
	Defederate(ctx context.Context, in *DefederateRequest, opts ...grpc.CallOption) (*DefederateResponse, error)
}

type federationManagementServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFederationManagementServiceClient(cc grpc.ClientConnInterface) FederationManagementServiceClient {
	return &federationManagementServiceClient{cc}
}

func (c *federationManagementServiceClient) RegisterNode(ctx context.Context, in *RegisterNodeRequest, opts ...grpc.CallOption) (*RegisterNodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterNodeResponse)
	err := c.cc.Invoke(ctx, FederationManagementService_RegisterNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *federationManagementServiceClient) ApproveNode(ctx context.Context, in *ApproveNodeRequest, opts ...grpc.CallOption) (*ApproveNodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApproveNodeResponse)
	err := c.cc.Invoke(ctx, FederationManagementService_ApproveNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *federationManagementServiceClient) DeactivateNode(ctx context.Context, in *DeactivateNodeRequest, opts ...grpc.CallOption) (*DeactivateNodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeactivateNodeResponse)
	err := c.cc.Invoke(ctx, FederationManagementService_DeactivateNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *federationManagementServiceClient) ListNodes(ctx context.Context, in *ListNodesRequest, opts ...grpc.CallOption) (*ListNodesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListNodesResponse)
	err := c.cc.Invoke(ctx, FederationManagementService_ListNodes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *federationManagementServiceClient) GetNodeStatus(ctx context.Context, in *GetNodeStatusRequest, opts ...grpc.CallOption) (*GetNodeStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNodeStatusResponse)
	err := c.cc.Invoke(ctx, FederationManagementService_GetNodeStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *federationManagementServiceClient) Defederate(ctx context.Context, in *DefederateRequest, opts ...grpc.CallOption) (*DefederateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DefederateResponse)
	err := c.cc.Invoke(ctx, FederationManagementService_Defederate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FederationManagementServiceServer is the server API for FederationManagementService service.
// All implementations must embed UnimplementedFederationManagementServiceServer
// for forward compatibility.
//
// Control-plane API for federation nodes (master-side operators / automation; mTLS).
// Complements node↔master data plane in s2s.proto (same package).
type FederationManagementServiceServer interface {
	RegisterNode(context.Context, *RegisterNodeRequest) (*RegisterNodeResponse, error)
	ApproveNode(context.Context, *ApproveNodeRequest) (*ApproveNodeResponse, error)
	DeactivateNode(context.Context, *DeactivateNodeRequest) (*DeactivateNodeResponse, error)
	ListNodes(context.Context, *ListNodesRequest) (*ListNodesResponse, error)
	GetNodeStatus(context.Context, *GetNodeStatusRequest) (*GetNodeStatusResponse, error)
	Defederate(context.Context, *DefederateRequest) (*DefederateResponse, error)
	mustEmbedUnimplementedFederationManagementServiceServer()
}

// UnimplementedFederationManagementServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFederationManagementServiceServer struct{}

func (UnimplementedFederationManagementServiceServer) RegisterNode(context.Context, *RegisterNodeRequest) (*RegisterNodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterNode not implemented")
}
func (UnimplementedFederationManagementServiceServer) ApproveNode(context.Context, *ApproveNodeRequest) (*ApproveNodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ApproveNode not implemented")
}
func (UnimplementedFederationManagementServiceServer) DeactivateNode(context.Context, *DeactivateNodeRequest) (*DeactivateNodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeactivateNode not implemented")
}
func (UnimplementedFederationManagementServiceServer) ListNodes(context.Context, *ListNodesRequest) (*ListNodesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListNodes not implemented")
}
func (UnimplementedFederationManagementServiceServer) GetNodeStatus(context.Context, *GetNodeStatusRequest) (*GetNodeStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNodeStatus not implemented")
}
func (UnimplementedFederationManagementServiceServer) Defederate(context.Context, *DefederateRequest) (*DefederateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Defederate not implemented")
}
func (UnimplementedFederationManagementServiceServer) mustEmbedUnimplementedFederationManagementServiceServer() {
}
func (UnimplementedFederationManagementServiceServer) testEmbeddedByValue() {}

// UnsafeFederationManagementServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FederationManagementServiceServer will
// result in compilation errors.
type UnsafeFederationManagementServiceServer interface {
	mustEmbedUnimplementedFederationManagementServiceServer()
}

func RegisterFederationManagementServiceServer(s grpc.ServiceRegistrar, srv FederationManagementServiceServer) {
	// If the following call panics, it indicates UnimplementedFederationManagementServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FederationManagementService_ServiceDesc, srv)
}

func _FederationManagementService_RegisterNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FederationManagementServiceServer).RegisterNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FederationManagementService_RegisterNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FederationManagementServiceServer).RegisterNode(ctx, req.(*RegisterNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FederationManagementService_ApproveNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApproveNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FederationManagementServiceServer).ApproveNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FederationManagementService_ApproveNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FederationManagementServiceServer).ApproveNode(ctx, req.(*ApproveNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FederationManagementService_DeactivateNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeactivateNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FederationManagementServiceServer).DeactivateNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FederationManagementService_DeactivateNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FederationManagementServiceServer).DeactivateNode(ctx, req.(*DeactivateNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FederationManagementService_ListNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListNodesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FederationManagementServiceServer).ListNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FederationManagementService_ListNodes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FederationManagementServiceServer).ListNodes(ctx, req.(*ListNodesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FederationManagementService_GetNodeStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNodeStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FederationManagementServiceServer).GetNodeStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FederationManagementService_GetNodeStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FederationManagementServiceServer).GetNodeStatus(ctx, req.(*GetNodeStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FederationManagementService_Defederate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DefederateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FederationManagementServiceServer).Defederate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FederationManagementService_Defederate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FederationManagementServiceServer).Defederate(ctx, req.(*DefederateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FederationManagementService_ServiceDesc is the grpc.ServiceDesc for FederationManagementService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FederationManagementService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "voice.s2s.v1.FederationManagementService",
	HandlerType: (*FederationManagementServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterNode",
			Handler:    _FederationManagementService_RegisterNode_Handler,
		},
		{
			MethodName: "ApproveNode",
			Handler:    _FederationManagementService_ApproveNode_Handler,
		},
		{
			MethodName: "DeactivateNode",
			Handler:    _FederationManagementService_DeactivateNode_Handler,
		},
		{
			MethodName: "ListNodes",
			Handler:    _FederationManagementService_ListNodes_Handler,
		},
		{
			MethodName: "GetNodeStatus",
			Handler:    _FederationManagementService_GetNodeStatus_Handler,
		},
		{
			MethodName: "Defederate",
			Handler:    _FederationManagementService_Defederate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "voice/s2s/v1/federation_management.proto",
}
