// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: voice/chat/v1/chat.proto

package chatv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
	v1 "voice.app/voice/common/v1"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChatType int32

const (
	ChatType_CHAT_TYPE_UNSPECIFIED ChatType = 0
	ChatType_CHAT_TYPE_DM          ChatType = 1
	ChatType_CHAT_TYPE_GROUP       ChatType = 2
	ChatType_CHAT_TYPE_CHANNEL     ChatType = 3
)

// Enum value maps for ChatType.
var (
	ChatType_name = map[int32]string{
		0: "CHAT_TYPE_UNSPECIFIED",
		1: "CHAT_TYPE_DM",
		2: "CHAT_TYPE_GROUP",
		3: "CHAT_TYPE_CHANNEL",
	}
	ChatType_value = map[string]int32{
		"CHAT_TYPE_UNSPECIFIED": 0,
		"CHAT_TYPE_DM":          1,
		"CHAT_TYPE_GROUP":       2,
		"CHAT_TYPE_CHANNEL":     3,
	}
)

func (x ChatType) Enum() *ChatType {
	p := new(ChatType)
	*p = x
	return p
}

func (x ChatType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChatType) Descriptor() protoreflect.EnumDescriptor {
	return file_voice_chat_v1_chat_proto_enumTypes[0].Descriptor()
}

func (ChatType) Type() protoreflect.EnumType {
	return &file_voice_chat_v1_chat_proto_enumTypes[0]
}

func (x ChatType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChatType.Descriptor instead.
func (ChatType) EnumDescriptor() ([]byte, []int) {
	return file_voice_chat_v1_chat_proto_rawDescGZIP(), []int{0}
}

type Chat struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type             ChatType               `protobuf:"varint,2,opt,name=type,proto3,enum=voice.chat.v1.ChatType" json:"type,omitempty"`
	SpaceId          *string                `protobuf:"bytes,3,opt,name=space_id,json=spaceId,proto3,oneof" json:"space_id,omitempty"`
	Name             *string                `protobuf:"bytes,4,opt,name=name,proto3,oneof" json:"name,omitempty"`
	AvatarUrl        *string                `protobuf:"bytes,5,opt,name=avatar_url,json=avatarUrl,proto3,oneof" json:"avatar_url,omitempty"`
	Topic            *string                `protobuf:"bytes,6,opt,name=topic,proto3,oneof" json:"topic,omitempty"`
	CreatorProfileId string                 `protobuf:"bytes,7,opt,name=creator_profile_id,json=creatorProfileId,proto3" json:"creator_profile_id,omitempty"`
	SlowModeSeconds  int32                  `protobuf:"varint,8,opt,name=slow_mode_seconds,json=slowModeSeconds,proto3" json:"slow_mode_seconds,omitempty"`
	LastMessageAt    *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=last_message_at,json=lastMessageAt,proto3,oneof" json:"last_message_at,omitempty"`
	CreatedAt        *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt        *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Chat) Reset() {
	*x = Chat{}
	mi := &file_voice_chat_v1_chat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Chat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chat) ProtoMessage() {}

func (x *Chat) ProtoReflect() protoreflect.Message {
	mi := &file_voice_chat_v1_chat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chat.ProtoReflect.Descriptor instead.
func (*Chat) Descriptor() ([]byte, []int) {
	return file_voice_chat_v1_chat_proto_rawDescGZIP(), []int{0}
}

func (x *Chat) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Chat) GetType() ChatType {
	if x != nil {
		return x.Type
	}
	return ChatType_CHAT_TYPE_UNSPECIFIED
}

func (x *Chat) GetSpaceId() string {
	if x != nil && x.SpaceId != nil {
		return *x.SpaceId
	}
	return ""
}

func (x *Chat) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *Chat) GetAvatarUrl() string {
	if x != nil && x.AvatarUrl != nil {
		return *x.AvatarUrl
	}
	return ""
}

func (x *Chat) GetTopic() string {
	if x != nil && x.Topic != nil {
		return *x.Topic
	}
	return ""
}

func (x *Chat) GetCreatorProfileId() string {
	if x != nil {
		return x.CreatorProfileId
	}
	return ""
}

func (x *Chat) GetSlowModeSeconds() int32 {
	if x != nil {
		return x.SlowModeSeconds
	}
	return 0
}

func (x *Chat) GetLastMessageAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastMessageAt
	}
	return nil
}

func (x *Chat) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Chat) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CreateDMRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OtherProfileId string                 `protobuf:"bytes,1,opt,name=other_profile_id,json=otherProfileId,proto3" json:"other_profile_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateDMRequest) Reset() {
	*x = CreateDMRequest{}
	mi := &file_voice_chat_v1_chat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDMRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDMRequest) ProtoMessage() {}

func (x *CreateDMRequest) ProtoReflect() protoreflect.Message {
	mi := &file_voice_chat_v1_chat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDMRequest.ProtoReflect.Descriptor instead.
func (*CreateDMRequest) Descriptor() ([]byte, []int) {
	return file_voice_chat_v1_chat_proto_rawDescGZIP(), []int{1}
}

func (x *CreateDMRequest) GetOtherProfileId() string {
	if x != nil {
		return x.OtherProfileId
	}
	return ""
}

type GetDMRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OtherProfileId string                 `protobuf:"bytes,1,opt,name=other_profile_id,json=otherProfileId,proto3" json:"other_profile_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetDMRequest) Reset() {
	*x = GetDMRequest{}
	mi := &file_voice_chat_v1_chat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDMRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDMRequest) ProtoMessage() {}

func (x *GetDMRequest) ProtoReflect() protoreflect.Message {
	mi := &file_voice_chat_v1_chat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDMRequest.ProtoReflect.Descriptor instead.
func (*GetDMRequest) Descriptor() ([]byte, []int) {
	return file_voice_chat_v1_chat_proto_rawDescGZIP(), []int{2}
}

func (x *GetDMRequest) GetOtherProfileId() string {
	if x != nil {
		return x.OtherProfileId
	}
	return ""
}

type CreateChatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          ChatType               `protobuf:"varint,1,opt,name=type,proto3,enum=voice.chat.v1.ChatType" json:"type,omitempty"`
	SpaceId       *string                `protobuf:"bytes,2,opt,name=space_id,json=spaceId,proto3,oneof" json:"space_id,omitempty"`
	Name          *string                `protobuf:"bytes,3,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Topic         *string                `protobuf:"bytes,4,opt,name=topic,proto3,oneof" json:"topic,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateChatRequest) Reset() {
	*x = CreateChatRequest{}
	mi := &file_voice_chat_v1_chat_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateChatRequest) ProtoMessage() {}

func (x *CreateChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_voice_chat_v1_chat_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateChatRequest.ProtoReflect.Descriptor instead.
func (*CreateChatRequest) Descriptor() ([]byte, []int) {
	return file_voice_chat_v1_chat_proto_rawDescGZIP(), []int{3}
}

func (x *CreateChatRequest) GetType() ChatType {
	if x != nil {
		return x.Type
	}
	return ChatType_CHAT_TYPE_UNSPECIFIED
}

func (x *CreateChatRequest) GetSpaceId() string {
	if x != nil && x.SpaceId != nil {
		return *x.SpaceId
	}
	return ""
}

func (x *CreateChatRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *CreateChatRequest) GetTopic() string {
	if x != nil && x.Topic != nil {
		return *x.Topic
	}
	return ""
}

type UpdateChatRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ChatId          string                 `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	Name            *string                `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Topic           *string                `protobuf:"bytes,3,opt,name=topic,proto3,oneof" json:"topic,omitempty"`
	SlowModeSeconds *int32                 `protobuf:"varint,4,opt,name=slow_mode_seconds,json=slowModeSeconds,proto3,oneof" json:"slow_mode_seconds,omitempty"`
	AvatarUrl       *string                `protobuf:"bytes,5,opt,name=avatar_url,json=avatarUrl,proto3,oneof" json:"avatar_url,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateChatRequest) Reset() {
	*x = UpdateChatRequest{}
	mi := &file_voice_chat_v1_chat_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateChatRequest) ProtoMessage() {}

func (x *UpdateChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_voice_chat_v1_chat_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateChatRequest.ProtoReflect.Descriptor instead.
func (*UpdateChatRequest) Descriptor() ([]byte, []int) {
	return file_voice_chat_v1_chat_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateChatRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *UpdateChatRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateChatRequest) GetTopic() string {
	if x != nil && x.Topic != nil {
		return *x.Topic
	}
	return ""
}

func (x *UpdateChatRequest) GetSlowModeSeconds() int32 {
	if x != nil && x.SlowModeSeconds != nil {
		return *x.SlowModeSeconds
	}
	return 0
}

func (x *UpdateChatRequest) GetAvatarUrl() string {
	if x != nil && x.AvatarUrl != nil {
		return *x.AvatarUrl
	}
	return ""
}

type DeleteChatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        string                 `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteChatRequest) Reset() {
	*x = DeleteChatRequest{}
	mi := &file_voice_chat_v1_chat_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteChatRequest) ProtoMessage() {}

func (x *DeleteChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_voice_chat_v1_chat_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteChatRequest.ProtoReflect.Descriptor instead.
func (*DeleteChatRequest) Descriptor() ([]byte, []int) {
	return file_voice_chat_v1_chat_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteChatRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

type AddMembersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        string                 `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	ProfileIds    []string               `protobuf:"bytes,2,rep,name=profile_ids,json=profileIds,proto3" json:"profile_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddMembersRequest) Reset() {
	*x = AddMembersRequest{}
	mi := &file_voice_chat_v1_chat_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddMembersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddMembersRequest) ProtoMessage() {}

func (x *AddMembersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_voice_chat_v1_chat_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddMembersRequest.ProtoReflect.Descriptor instead.
func (*AddMembersRequest) Descriptor() ([]byte, []int) {
	return file_voice_chat_v1_chat_proto_rawDescGZIP(), []int{6}
}

func (x *AddMembersRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *AddMembersRequest) GetProfileIds() []string {
	if x != nil {
		return x.ProfileIds
	}
	return nil
}

type RemoveMemberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        string                 `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	ProfileId     string                 `protobuf:"bytes,2,opt,name=profile_id,json=profileId,proto3" json:"profile_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveMemberRequest) Reset() {
	*x = RemoveMemberRequest{}
	mi := &file_voice_chat_v1_chat_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveMemberRequest) ProtoMessage() {}

func (x *RemoveMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_voice_chat_v1_chat_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveMemberRequest.ProtoReflect.Descriptor instead.
func (*RemoveMemberRequest) Descriptor() ([]byte, []int) {
	return file_voice_chat_v1_chat_proto_rawDescGZIP(), []int{7}
}

func (x *RemoveMemberRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *RemoveMemberRequest) GetProfileId() string {
	if x != nil {
		return x.ProfileId
	}
	return ""
}

type LeaveChatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        string                 `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveChatRequest) Reset() {
	*x = LeaveChatRequest{}
	mi := &file_voice_chat_v1_chat_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveChatRequest) ProtoMessage() {}

func (x *LeaveChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_voice_chat_v1_chat_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveChatRequest.ProtoReflect.Descriptor instead.
func (*LeaveChatRequest) Descriptor() ([]byte, []int) {
	return file_voice_chat_v1_chat_proto_rawDescGZIP(), []int{8}
}

func (x *LeaveChatRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

type ListMembersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        string                 `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	Page          *v1.CursorPageRequest  `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMembersRequest) Reset() {
	*x = ListMembersRequest{}
	mi := &file_voice_chat_v1_chat_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMembersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMembersRequest) ProtoMessage() {}

func (x *ListMembersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_voice_chat_v1_chat_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMembersRequest.ProtoReflect.Descriptor instead.
func (*ListMembersRequest) Descriptor() ([]byte, []int) {
	return file_voice_chat_v1_chat_proto_rawDescGZIP(), []int{9}
}

func (x *ListMembersRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *ListMembersRequest) GetPage() *v1.CursorPageRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

type MemberList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Members       []*ChatMember          `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty"`
	NextCursor    string                 `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemberList) Reset() {
	*x = MemberList{}
	mi := &file_voice_chat_v1_chat_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemberList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberList) ProtoMessage() {}

func (x *MemberList) ProtoReflect() protoreflect.Message {
	mi := &file_voice_chat_v1_chat_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberList.ProtoReflect.Descriptor instead.
func (*MemberList) Descriptor() ([]byte, []int) {
	return file_voice_chat_v1_chat_proto_rawDescGZIP(), []int{10}
}

func (x *MemberList) GetMembers() []*ChatMember {
	if x != nil {
		return x.Members
	}
	return nil
}

func (x *MemberList) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

type ChatMember struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProfileId     string                 `protobuf:"bytes,1,opt,name=profile_id,json=profileId,proto3" json:"profile_id,omitempty"`
	Role          string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"` // owner | admin | member
	JoinedAt      *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=joined_at,json=joinedAt,proto3" json:"joined_at,omitempty"`
	MutedUntil    *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=muted_until,json=mutedUntil,proto3,oneof" json:"muted_until,omitempty"`
	IsArchived    bool                   `protobuf:"varint,5,opt,name=is_archived,json=isArchived,proto3" json:"is_archived,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMember) Reset() {
	*x = ChatMember{}
	mi := &file_voice_chat_v1_chat_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMember) ProtoMessage() {}

func (x *ChatMember) ProtoReflect() protoreflect.Message {
	mi := &file_voice_chat_v1_chat_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMember.ProtoReflect.Descriptor instead.
func (*ChatMember) Descriptor() ([]byte, []int) {
	return file_voice_chat_v1_chat_proto_rawDescGZIP(), []int{11}
}

func (x *ChatMember) GetProfileId() string {
	if x != nil {
		return x.ProfileId
	}
	return ""
}

func (x *ChatMember) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *ChatMember) GetJoinedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.JoinedAt
	}
	return nil
}

func (x *ChatMember) GetMutedUntil() *timestamppb.Timestamp {
	if x != nil {
		return x.MutedUntil
	}
	return nil
}

func (x *ChatMember) GetIsArchived() bool {
	if x != nil {
		return x.IsArchived
	}
	return false
}

type ListChatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          *v1.CursorPageRequest  `protobuf:"bytes,1,opt,name=page,proto3" json:"page,omitempty"`
	Inbox         *string                `protobuf:"bytes,2,opt,name=inbox,proto3,oneof" json:"inbox,omitempty"` // main | requests
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListChatsRequest) Reset() {
	*x = ListChatsRequest{}
	mi := &file_voice_chat_v1_chat_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListChatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChatsRequest) ProtoMessage() {}

func (x *ListChatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_voice_chat_v1_chat_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChatsRequest.ProtoReflect.Descriptor instead.
func (*ListChatsRequest) Descriptor() ([]byte, []int) {
	return file_voice_chat_v1_chat_proto_rawDescGZIP(), []int{12}
}

func (x *ListChatsRequest) GetPage() *v1.CursorPageRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

func (x *ListChatsRequest) GetInbox() string {
	if x != nil && x.Inbox != nil {
		return *x.Inbox
	}
	return ""
}

// One row in the inbox: chat metadata plus list fields sourced from Messaging (S2S) when configured.
type ChatListItem struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Chat  *Chat                  `protobuf:"bytes,1,opt,name=chat,proto3" json:"chat,omitempty"`
	// Truncated last visible message text for list UI; empty/absent when unknown or no messages yet.
	LastMessagePreview *string `protobuf:"bytes,2,opt,name=last_message_preview,json=lastMessagePreview,proto3,oneof" json:"last_message_preview,omitempty"`
	// Count of messages unread by the caller in this chat; 0 when caught up or when Messaging is unavailable.
	UnreadCount int64   `protobuf:"varint,3,opt,name=unread_count,json=unreadCount,proto3" json:"unread_count,omitempty"`
	Inbox       *string `protobuf:"bytes,4,opt,name=inbox,proto3,oneof" json:"inbox,omitempty"` // main | requests
	IsStranger  *bool   `protobuf:"varint,5,opt,name=is_stranger,json=isStranger,proto3,oneof" json:"is_stranger,omitempty"`
	// Other participant in a DM (for list titles / avatars); absent for non-DM or when unknown.
	DmPeerProfileId *string `protobuf:"bytes,6,opt,name=dm_peer_profile_id,json=dmPeerProfileId,proto3,oneof" json:"dm_peer_profile_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ChatListItem) Reset() {
	*x = ChatListItem{}
	mi := &file_voice_chat_v1_chat_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatListItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatListItem) ProtoMessage() {}

func (x *ChatListItem) ProtoReflect() protoreflect.Message {
	mi := &file_voice_chat_v1_chat_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatListItem.ProtoReflect.Descriptor instead.
func (*ChatListItem) Descriptor() ([]byte, []int) {
	return file_voice_chat_v1_chat_proto_rawDescGZIP(), []int{13}
}

func (x *ChatListItem) GetChat() *Chat {
	if x != nil {
		return x.Chat
	}
	return nil
}

func (x *ChatListItem) GetLastMessagePreview() string {
	if x != nil && x.LastMessagePreview != nil {
		return *x.LastMessagePreview
	}
	return ""
}

func (x *ChatListItem) GetUnreadCount() int64 {
	if x != nil {
		return x.UnreadCount
	}
	return 0
}

func (x *ChatListItem) GetInbox() string {
	if x != nil && x.Inbox != nil {
		return *x.Inbox
	}
	return ""
}

func (x *ChatListItem) GetIsStranger() bool {
	if x != nil && x.IsStranger != nil {
		return *x.IsStranger
	}
	return false
}

func (x *ChatListItem) GetDmPeerProfileId() string {
	if x != nil && x.DmPeerProfileId != nil {
		return *x.DmPeerProfileId
	}
	return ""
}

type ChatList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*ChatListItem        `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	NextCursor    string                 `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatList) Reset() {
	*x = ChatList{}
	mi := &file_voice_chat_v1_chat_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatList) ProtoMessage() {}

func (x *ChatList) ProtoReflect() protoreflect.Message {
	mi := &file_voice_chat_v1_chat_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatList.ProtoReflect.Descriptor instead.
func (*ChatList) Descriptor() ([]byte, []int) {
	return file_voice_chat_v1_chat_proto_rawDescGZIP(), []int{14}
}

func (x *ChatList) GetItems() []*ChatListItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ChatList) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

type GetChatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        string                 `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChatRequest) Reset() {
	*x = GetChatRequest{}
	mi := &file_voice_chat_v1_chat_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChatRequest) ProtoMessage() {}

func (x *GetChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_voice_chat_v1_chat_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChatRequest.ProtoReflect.Descriptor instead.
func (*GetChatRequest) Descriptor() ([]byte, []int) {
	return file_voice_chat_v1_chat_proto_rawDescGZIP(), []int{15}
}

func (x *GetChatRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

type ListFoldersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFoldersRequest) Reset() {
	*x = ListFoldersRequest{}
	mi := &file_voice_chat_v1_chat_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFoldersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFoldersRequest) ProtoMessage() {}

func (x *ListFoldersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_voice_chat_v1_chat_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFoldersRequest.ProtoReflect.Descriptor instead.
func (*ListFoldersRequest) Descriptor() ([]byte, []int) {
	return file_voice_chat_v1_chat_proto_rawDescGZIP(), []int{16}
}

type FolderList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Folders       []*Folder              `protobuf:"bytes,1,rep,name=folders,proto3" json:"folders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FolderList) Reset() {
	*x = FolderList{}
	mi := &file_voice_chat_v1_chat_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FolderList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FolderList) ProtoMessage() {}

func (x *FolderList) ProtoReflect() protoreflect.Message {
	mi := &file_voice_chat_v1_chat_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FolderList.ProtoReflect.Descriptor instead.
func (*FolderList) Descriptor() ([]byte, []int) {
	return file_voice_chat_v1_chat_proto_rawDescGZIP(), []int{17}
}

func (x *FolderList) GetFolders() []*Folder {
	if x != nil {
		return x.Folders
	}
	return nil
}

type Folder struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name             string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	FolderType       string                 `protobuf:"bytes,3,opt,name=folder_type,json=folderType,proto3" json:"folder_type,omitempty"` // system | custom
	FilterConfigJson string                 `protobuf:"bytes,4,opt,name=filter_config_json,json=filterConfigJson,proto3" json:"filter_config_json,omitempty"`
	SortOrder        int32                  `protobuf:"varint,5,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Folder) Reset() {
	*x = Folder{}
	mi := &file_voice_chat_v1_chat_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Folder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Folder) ProtoMessage() {}

func (x *Folder) ProtoReflect() protoreflect.Message {
	mi := &file_voice_chat_v1_chat_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Folder.ProtoReflect.Descriptor instead.
func (*Folder) Descriptor() ([]byte, []int) {
	return file_voice_chat_v1_chat_proto_rawDescGZIP(), []int{18}
}

func (x *Folder) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Folder) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Folder) GetFolderType() string {
	if x != nil {
		return x.FolderType
	}
	return ""
}

func (x *Folder) GetFilterConfigJson() string {
	if x != nil {
		return x.FilterConfigJson
	}
	return ""
}

func (x *Folder) GetSortOrder() int32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

type CreateFolderRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Name             string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	FilterConfigJson string                 `protobuf:"bytes,2,opt,name=filter_config_json,json=filterConfigJson,proto3" json:"filter_config_json,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateFolderRequest) Reset() {
	*x = CreateFolderRequest{}
	mi := &file_voice_chat_v1_chat_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFolderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFolderRequest) ProtoMessage() {}

func (x *CreateFolderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_voice_chat_v1_chat_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFolderRequest.ProtoReflect.Descriptor instead.
func (*CreateFolderRequest) Descriptor() ([]byte, []int) {
	return file_voice_chat_v1_chat_proto_rawDescGZIP(), []int{19}
}

func (x *CreateFolderRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateFolderRequest) GetFilterConfigJson() string {
	if x != nil {
		return x.FilterConfigJson
	}
	return ""
}

type UpdateFolderRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	FolderId         string                 `protobuf:"bytes,1,opt,name=folder_id,json=folderId,proto3" json:"folder_id,omitempty"`
	Name             *string                `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	FilterConfigJson *string                `protobuf:"bytes,3,opt,name=filter_config_json,json=filterConfigJson,proto3,oneof" json:"filter_config_json,omitempty"`
	SortOrder        *int32                 `protobuf:"varint,4,opt,name=sort_order,json=sortOrder,proto3,oneof" json:"sort_order,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UpdateFolderRequest) Reset() {
	*x = UpdateFolderRequest{}
	mi := &file_voice_chat_v1_chat_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateFolderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFolderRequest) ProtoMessage() {}

func (x *UpdateFolderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_voice_chat_v1_chat_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFolderRequest.ProtoReflect.Descriptor instead.
func (*UpdateFolderRequest) Descriptor() ([]byte, []int) {
	return file_voice_chat_v1_chat_proto_rawDescGZIP(), []int{20}
}

func (x *UpdateFolderRequest) GetFolderId() string {
	if x != nil {
		return x.FolderId
	}
	return ""
}

func (x *UpdateFolderRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateFolderRequest) GetFilterConfigJson() string {
	if x != nil && x.FilterConfigJson != nil {
		return *x.FilterConfigJson
	}
	return ""
}

func (x *UpdateFolderRequest) GetSortOrder() int32 {
	if x != nil && x.SortOrder != nil {
		return *x.SortOrder
	}
	return 0
}

type DeleteFolderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FolderId      string                 `protobuf:"bytes,1,opt,name=folder_id,json=folderId,proto3" json:"folder_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFolderRequest) Reset() {
	*x = DeleteFolderRequest{}
	mi := &file_voice_chat_v1_chat_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFolderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFolderRequest) ProtoMessage() {}

func (x *DeleteFolderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_voice_chat_v1_chat_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFolderRequest.ProtoReflect.Descriptor instead.
func (*DeleteFolderRequest) Descriptor() ([]byte, []int) {
	return file_voice_chat_v1_chat_proto_rawDescGZIP(), []int{21}
}

func (x *DeleteFolderRequest) GetFolderId() string {
	if x != nil {
		return x.FolderId
	}
	return ""
}

type AcceptDMRequestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        string                 `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptDMRequestRequest) Reset() {
	*x = AcceptDMRequestRequest{}
	mi := &file_voice_chat_v1_chat_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptDMRequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptDMRequestRequest) ProtoMessage() {}

func (x *AcceptDMRequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_voice_chat_v1_chat_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptDMRequestRequest.ProtoReflect.Descriptor instead.
func (*AcceptDMRequestRequest) Descriptor() ([]byte, []int) {
	return file_voice_chat_v1_chat_proto_rawDescGZIP(), []int{22}
}

func (x *AcceptDMRequestRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

type DeclineDMRequestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        string                 `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeclineDMRequestRequest) Reset() {
	*x = DeclineDMRequestRequest{}
	mi := &file_voice_chat_v1_chat_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeclineDMRequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeclineDMRequestRequest) ProtoMessage() {}

func (x *DeclineDMRequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_voice_chat_v1_chat_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeclineDMRequestRequest.ProtoReflect.Descriptor instead.
func (*DeclineDMRequestRequest) Descriptor() ([]byte, []int) {
	return file_voice_chat_v1_chat_proto_rawDescGZIP(), []int{23}
}

func (x *DeclineDMRequestRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

type MuteChatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        string                 `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	MutedUntil    *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=muted_until,json=mutedUntil,proto3,oneof" json:"muted_until,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MuteChatRequest) Reset() {
	*x = MuteChatRequest{}
	mi := &file_voice_chat_v1_chat_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MuteChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MuteChatRequest) ProtoMessage() {}

func (x *MuteChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_voice_chat_v1_chat_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MuteChatRequest.ProtoReflect.Descriptor instead.
func (*MuteChatRequest) Descriptor() ([]byte, []int) {
	return file_voice_chat_v1_chat_proto_rawDescGZIP(), []int{24}
}

func (x *MuteChatRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *MuteChatRequest) GetMutedUntil() *timestamppb.Timestamp {
	if x != nil {
		return x.MutedUntil
	}
	return nil
}

type ArchiveChatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        string                 `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	Archived      bool                   `protobuf:"varint,2,opt,name=archived,proto3" json:"archived,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArchiveChatRequest) Reset() {
	*x = ArchiveChatRequest{}
	mi := &file_voice_chat_v1_chat_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArchiveChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArchiveChatRequest) ProtoMessage() {}

func (x *ArchiveChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_voice_chat_v1_chat_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArchiveChatRequest.ProtoReflect.Descriptor instead.
func (*ArchiveChatRequest) Descriptor() ([]byte, []int) {
	return file_voice_chat_v1_chat_proto_rawDescGZIP(), []int{25}
}

func (x *ArchiveChatRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *ArchiveChatRequest) GetArchived() bool {
	if x != nil {
		return x.Archived
	}
	return false
}

// Cross-service pointer to chat_db.chats (docs/DATA_MODEL.md). Use in other packages instead of parallel chat_id + chat_type strings.
type ChatRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          *ChatType              `protobuf:"varint,2,opt,name=type,proto3,enum=voice.chat.v1.ChatType,oneof" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatRef) Reset() {
	*x = ChatRef{}
	mi := &file_voice_chat_v1_chat_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatRef) ProtoMessage() {}

func (x *ChatRef) ProtoReflect() protoreflect.Message {
	mi := &file_voice_chat_v1_chat_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatRef.ProtoReflect.Descriptor instead.
func (*ChatRef) Descriptor() ([]byte, []int) {
	return file_voice_chat_v1_chat_proto_rawDescGZIP(), []int{26}
}

func (x *ChatRef) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ChatRef) GetType() ChatType {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return ChatType_CHAT_TYPE_UNSPECIFIED
}

type CreateDMResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chat          *Chat                  `protobuf:"bytes,1,opt,name=chat,proto3" json:"chat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDMResponse) Reset() {
	*x = CreateDMResponse{}
	mi := &file_voice_chat_v1_chat_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDMResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDMResponse) ProtoMessage() {}

func (x *CreateDMResponse) ProtoReflect() protoreflect.Message {
	mi := &file_voice_chat_v1_chat_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDMResponse.ProtoReflect.Descriptor instead.
func (*CreateDMResponse) Descriptor() ([]byte, []int) {
	return file_voice_chat_v1_chat_proto_rawDescGZIP(), []int{27}
}

func (x *CreateDMResponse) GetChat() *Chat {
	if x != nil {
		return x.Chat
	}
	return nil
}

type GetDMResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chat          *Chat                  `protobuf:"bytes,1,opt,name=chat,proto3" json:"chat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDMResponse) Reset() {
	*x = GetDMResponse{}
	mi := &file_voice_chat_v1_chat_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDMResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDMResponse) ProtoMessage() {}

func (x *GetDMResponse) ProtoReflect() protoreflect.Message {
	mi := &file_voice_chat_v1_chat_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDMResponse.ProtoReflect.Descriptor instead.
func (*GetDMResponse) Descriptor() ([]byte, []int) {
	return file_voice_chat_v1_chat_proto_rawDescGZIP(), []int{28}
}

func (x *GetDMResponse) GetChat() *Chat {
	if x != nil {
		return x.Chat
	}
	return nil
}

type CreateChatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chat          *Chat                  `protobuf:"bytes,1,opt,name=chat,proto3" json:"chat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateChatResponse) Reset() {
	*x = CreateChatResponse{}
	mi := &file_voice_chat_v1_chat_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateChatResponse) ProtoMessage() {}

func (x *CreateChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_voice_chat_v1_chat_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateChatResponse.ProtoReflect.Descriptor instead.
func (*CreateChatResponse) Descriptor() ([]byte, []int) {
	return file_voice_chat_v1_chat_proto_rawDescGZIP(), []int{29}
}

func (x *CreateChatResponse) GetChat() *Chat {
	if x != nil {
		return x.Chat
	}
	return nil
}

type UpdateChatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chat          *Chat                  `protobuf:"bytes,1,opt,name=chat,proto3" json:"chat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateChatResponse) Reset() {
	*x = UpdateChatResponse{}
	mi := &file_voice_chat_v1_chat_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateChatResponse) ProtoMessage() {}

func (x *UpdateChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_voice_chat_v1_chat_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateChatResponse.ProtoReflect.Descriptor instead.
func (*UpdateChatResponse) Descriptor() ([]byte, []int) {
	return file_voice_chat_v1_chat_proto_rawDescGZIP(), []int{30}
}

func (x *UpdateChatResponse) GetChat() *Chat {
	if x != nil {
		return x.Chat
	}
	return nil
}

type DeleteChatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteChatResponse) Reset() {
	*x = DeleteChatResponse{}
	mi := &file_voice_chat_v1_chat_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteChatResponse) ProtoMessage() {}

func (x *DeleteChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_voice_chat_v1_chat_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteChatResponse.ProtoReflect.Descriptor instead.
func (*DeleteChatResponse) Descriptor() ([]byte, []int) {
	return file_voice_chat_v1_chat_proto_rawDescGZIP(), []int{31}
}

type AddMembersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddMembersResponse) Reset() {
	*x = AddMembersResponse{}
	mi := &file_voice_chat_v1_chat_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddMembersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddMembersResponse) ProtoMessage() {}

func (x *AddMembersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_voice_chat_v1_chat_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddMembersResponse.ProtoReflect.Descriptor instead.
func (*AddMembersResponse) Descriptor() ([]byte, []int) {
	return file_voice_chat_v1_chat_proto_rawDescGZIP(), []int{32}
}

type RemoveMemberResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveMemberResponse) Reset() {
	*x = RemoveMemberResponse{}
	mi := &file_voice_chat_v1_chat_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveMemberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveMemberResponse) ProtoMessage() {}

func (x *RemoveMemberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_voice_chat_v1_chat_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveMemberResponse.ProtoReflect.Descriptor instead.
func (*RemoveMemberResponse) Descriptor() ([]byte, []int) {
	return file_voice_chat_v1_chat_proto_rawDescGZIP(), []int{33}
}

type LeaveChatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveChatResponse) Reset() {
	*x = LeaveChatResponse{}
	mi := &file_voice_chat_v1_chat_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveChatResponse) ProtoMessage() {}

func (x *LeaveChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_voice_chat_v1_chat_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveChatResponse.ProtoReflect.Descriptor instead.
func (*LeaveChatResponse) Descriptor() ([]byte, []int) {
	return file_voice_chat_v1_chat_proto_rawDescGZIP(), []int{34}
}

type ListMembersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MemberList    *MemberList            `protobuf:"bytes,1,opt,name=member_list,json=memberList,proto3" json:"member_list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMembersResponse) Reset() {
	*x = ListMembersResponse{}
	mi := &file_voice_chat_v1_chat_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMembersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMembersResponse) ProtoMessage() {}

func (x *ListMembersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_voice_chat_v1_chat_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMembersResponse.ProtoReflect.Descriptor instead.
func (*ListMembersResponse) Descriptor() ([]byte, []int) {
	return file_voice_chat_v1_chat_proto_rawDescGZIP(), []int{35}
}

func (x *ListMembersResponse) GetMemberList() *MemberList {
	if x != nil {
		return x.MemberList
	}
	return nil
}

type ListChatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatList      *ChatList              `protobuf:"bytes,1,opt,name=chat_list,json=chatList,proto3" json:"chat_list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListChatsResponse) Reset() {
	*x = ListChatsResponse{}
	mi := &file_voice_chat_v1_chat_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListChatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChatsResponse) ProtoMessage() {}

func (x *ListChatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_voice_chat_v1_chat_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChatsResponse.ProtoReflect.Descriptor instead.
func (*ListChatsResponse) Descriptor() ([]byte, []int) {
	return file_voice_chat_v1_chat_proto_rawDescGZIP(), []int{36}
}

func (x *ListChatsResponse) GetChatList() *ChatList {
	if x != nil {
		return x.ChatList
	}
	return nil
}

type GetChatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chat          *Chat                  `protobuf:"bytes,1,opt,name=chat,proto3" json:"chat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChatResponse) Reset() {
	*x = GetChatResponse{}
	mi := &file_voice_chat_v1_chat_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChatResponse) ProtoMessage() {}

func (x *GetChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_voice_chat_v1_chat_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChatResponse.ProtoReflect.Descriptor instead.
func (*GetChatResponse) Descriptor() ([]byte, []int) {
	return file_voice_chat_v1_chat_proto_rawDescGZIP(), []int{37}
}

func (x *GetChatResponse) GetChat() *Chat {
	if x != nil {
		return x.Chat
	}
	return nil
}

type ListFoldersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FolderList    *FolderList            `protobuf:"bytes,1,opt,name=folder_list,json=folderList,proto3" json:"folder_list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFoldersResponse) Reset() {
	*x = ListFoldersResponse{}
	mi := &file_voice_chat_v1_chat_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFoldersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFoldersResponse) ProtoMessage() {}

func (x *ListFoldersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_voice_chat_v1_chat_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFoldersResponse.ProtoReflect.Descriptor instead.
func (*ListFoldersResponse) Descriptor() ([]byte, []int) {
	return file_voice_chat_v1_chat_proto_rawDescGZIP(), []int{38}
}

func (x *ListFoldersResponse) GetFolderList() *FolderList {
	if x != nil {
		return x.FolderList
	}
	return nil
}

type CreateFolderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Folder        *Folder                `protobuf:"bytes,1,opt,name=folder,proto3" json:"folder,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFolderResponse) Reset() {
	*x = CreateFolderResponse{}
	mi := &file_voice_chat_v1_chat_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFolderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFolderResponse) ProtoMessage() {}

func (x *CreateFolderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_voice_chat_v1_chat_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFolderResponse.ProtoReflect.Descriptor instead.
func (*CreateFolderResponse) Descriptor() ([]byte, []int) {
	return file_voice_chat_v1_chat_proto_rawDescGZIP(), []int{39}
}

func (x *CreateFolderResponse) GetFolder() *Folder {
	if x != nil {
		return x.Folder
	}
	return nil
}

type UpdateFolderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Folder        *Folder                `protobuf:"bytes,1,opt,name=folder,proto3" json:"folder,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateFolderResponse) Reset() {
	*x = UpdateFolderResponse{}
	mi := &file_voice_chat_v1_chat_proto_msgTypes[40]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateFolderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFolderResponse) ProtoMessage() {}

func (x *UpdateFolderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_voice_chat_v1_chat_proto_msgTypes[40]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFolderResponse.ProtoReflect.Descriptor instead.
func (*UpdateFolderResponse) Descriptor() ([]byte, []int) {
	return file_voice_chat_v1_chat_proto_rawDescGZIP(), []int{40}
}

func (x *UpdateFolderResponse) GetFolder() *Folder {
	if x != nil {
		return x.Folder
	}
	return nil
}

type DeleteFolderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFolderResponse) Reset() {
	*x = DeleteFolderResponse{}
	mi := &file_voice_chat_v1_chat_proto_msgTypes[41]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFolderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFolderResponse) ProtoMessage() {}

func (x *DeleteFolderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_voice_chat_v1_chat_proto_msgTypes[41]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFolderResponse.ProtoReflect.Descriptor instead.
func (*DeleteFolderResponse) Descriptor() ([]byte, []int) {
	return file_voice_chat_v1_chat_proto_rawDescGZIP(), []int{41}
}

type AcceptDMRequestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptDMRequestResponse) Reset() {
	*x = AcceptDMRequestResponse{}
	mi := &file_voice_chat_v1_chat_proto_msgTypes[42]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptDMRequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptDMRequestResponse) ProtoMessage() {}

func (x *AcceptDMRequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_voice_chat_v1_chat_proto_msgTypes[42]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptDMRequestResponse.ProtoReflect.Descriptor instead.
func (*AcceptDMRequestResponse) Descriptor() ([]byte, []int) {
	return file_voice_chat_v1_chat_proto_rawDescGZIP(), []int{42}
}

type DeclineDMRequestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeclineDMRequestResponse) Reset() {
	*x = DeclineDMRequestResponse{}
	mi := &file_voice_chat_v1_chat_proto_msgTypes[43]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeclineDMRequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeclineDMRequestResponse) ProtoMessage() {}

func (x *DeclineDMRequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_voice_chat_v1_chat_proto_msgTypes[43]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeclineDMRequestResponse.ProtoReflect.Descriptor instead.
func (*DeclineDMRequestResponse) Descriptor() ([]byte, []int) {
	return file_voice_chat_v1_chat_proto_rawDescGZIP(), []int{43}
}

type MuteChatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MuteChatResponse) Reset() {
	*x = MuteChatResponse{}
	mi := &file_voice_chat_v1_chat_proto_msgTypes[44]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MuteChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MuteChatResponse) ProtoMessage() {}

func (x *MuteChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_voice_chat_v1_chat_proto_msgTypes[44]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MuteChatResponse.ProtoReflect.Descriptor instead.
func (*MuteChatResponse) Descriptor() ([]byte, []int) {
	return file_voice_chat_v1_chat_proto_rawDescGZIP(), []int{44}
}

type ArchiveChatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArchiveChatResponse) Reset() {
	*x = ArchiveChatResponse{}
	mi := &file_voice_chat_v1_chat_proto_msgTypes[45]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArchiveChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArchiveChatResponse) ProtoMessage() {}

func (x *ArchiveChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_voice_chat_v1_chat_proto_msgTypes[45]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArchiveChatResponse.ProtoReflect.Descriptor instead.
func (*ArchiveChatResponse) Descriptor() ([]byte, []int) {
	return file_voice_chat_v1_chat_proto_rawDescGZIP(), []int{45}
}

var File_voice_chat_v1_chat_proto protoreflect.FileDescriptor

const file_voice_chat_v1_chat_proto_rawDesc = "" +
	"\n" +
	"\x18voice/chat/v1/chat.proto\x12\rvoice.chat.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cvoice/common/v1/common.proto\"\x97\x04\n" +
	"\x04Chat\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12+\n" +
	"\x04type\x18\x02 \x01(\x0e2\x17.voice.chat.v1.ChatTypeR\x04type\x12\x1e\n" +
	"\bspace_id\x18\x03 \x01(\tH\x00R\aspaceId\x88\x01\x01\x12\x17\n" +
	"\x04name\x18\x04 \x01(\tH\x01R\x04name\x88\x01\x01\x12\"\n" +
	"\n" +
	"avatar_url\x18\x05 \x01(\tH\x02R\tavatarUrl\x88\x01\x01\x12\x19\n" +
	"\x05topic\x18\x06 \x01(\tH\x03R\x05topic\x88\x01\x01\x12,\n" +
	"\x12creator_profile_id\x18\a \x01(\tR\x10creatorProfileId\x12*\n" +
	"\x11slow_mode_seconds\x18\b \x01(\x05R\x0fslowModeSeconds\x12G\n" +
	"\x0flast_message_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampH\x04R\rlastMessageAt\x88\x01\x01\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAtB\v\n" +
	"\t_space_idB\a\n" +
	"\x05_nameB\r\n" +
	"\v_avatar_urlB\b\n" +
	"\x06_topicB\x12\n" +
	"\x10_last_message_at\";\n" +
	"\x0fCreateDMRequest\x12(\n" +
	"\x10other_profile_id\x18\x01 \x01(\tR\x0eotherProfileId\"8\n" +
	"\fGetDMRequest\x12(\n" +
	"\x10other_profile_id\x18\x01 \x01(\tR\x0eotherProfileId\"\xb4\x01\n" +
	"\x11CreateChatRequest\x12+\n" +
	"\x04type\x18\x01 \x01(\x0e2\x17.voice.chat.v1.ChatTypeR\x04type\x12\x1e\n" +
	"\bspace_id\x18\x02 \x01(\tH\x00R\aspaceId\x88\x01\x01\x12\x17\n" +
	"\x04name\x18\x03 \x01(\tH\x01R\x04name\x88\x01\x01\x12\x19\n" +
	"\x05topic\x18\x04 \x01(\tH\x02R\x05topic\x88\x01\x01B\v\n" +
	"\t_space_idB\a\n" +
	"\x05_nameB\b\n" +
	"\x06_topic\"\xed\x01\n" +
	"\x11UpdateChatRequest\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\tR\x06chatId\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x00R\x04name\x88\x01\x01\x12\x19\n" +
	"\x05topic\x18\x03 \x01(\tH\x01R\x05topic\x88\x01\x01\x12/\n" +
	"\x11slow_mode_seconds\x18\x04 \x01(\x05H\x02R\x0fslowModeSeconds\x88\x01\x01\x12\"\n" +
	"\n" +
	"avatar_url\x18\x05 \x01(\tH\x03R\tavatarUrl\x88\x01\x01B\a\n" +
	"\x05_nameB\b\n" +
	"\x06_topicB\x14\n" +
	"\x12_slow_mode_secondsB\r\n" +
	"\v_avatar_url\",\n" +
	"\x11DeleteChatRequest\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\tR\x06chatId\"M\n" +
	"\x11AddMembersRequest\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\tR\x06chatId\x12\x1f\n" +
	"\vprofile_ids\x18\x02 \x03(\tR\n" +
	"profileIds\"M\n" +
	"\x13RemoveMemberRequest\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\tR\x06chatId\x12\x1d\n" +
	"\n" +
	"profile_id\x18\x02 \x01(\tR\tprofileId\"+\n" +
	"\x10LeaveChatRequest\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\tR\x06chatId\"e\n" +
	"\x12ListMembersRequest\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\tR\x06chatId\x126\n" +
	"\x04page\x18\x02 \x01(\v2\".voice.common.v1.CursorPageRequestR\x04page\"b\n" +
	"\n" +
	"MemberList\x123\n" +
	"\amembers\x18\x01 \x03(\v2\x19.voice.chat.v1.ChatMemberR\amembers\x12\x1f\n" +
	"\vnext_cursor\x18\x02 \x01(\tR\n" +
	"nextCursor\"\xeb\x01\n" +
	"\n" +
	"ChatMember\x12\x1d\n" +
	"\n" +
	"profile_id\x18\x01 \x01(\tR\tprofileId\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\x127\n" +
	"\tjoined_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\bjoinedAt\x12@\n" +
	"\vmuted_until\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\n" +
	"mutedUntil\x88\x01\x01\x12\x1f\n" +
	"\vis_archived\x18\x05 \x01(\bR\n" +
	"isArchivedB\x0e\n" +
	"\f_muted_until\"o\n" +
	"\x10ListChatsRequest\x126\n" +
	"\x04page\x18\x01 \x01(\v2\".voice.common.v1.CursorPageRequestR\x04page\x12\x19\n" +
	"\x05inbox\x18\x02 \x01(\tH\x00R\x05inbox\x88\x01\x01B\b\n" +
	"\x06_inbox\"\xce\x02\n" +
	"\fChatListItem\x12'\n" +
	"\x04chat\x18\x01 \x01(\v2\x13.voice.chat.v1.ChatR\x04chat\x125\n" +
	"\x14last_message_preview\x18\x02 \x01(\tH\x00R\x12lastMessagePreview\x88\x01\x01\x12!\n" +
	"\funread_count\x18\x03 \x01(\x03R\vunreadCount\x12\x19\n" +
	"\x05inbox\x18\x04 \x01(\tH\x01R\x05inbox\x88\x01\x01\x12$\n" +
	"\vis_stranger\x18\x05 \x01(\bH\x02R\n" +
	"isStranger\x88\x01\x01\x120\n" +
	"\x12dm_peer_profile_id\x18\x06 \x01(\tH\x03R\x0fdmPeerProfileId\x88\x01\x01B\x17\n" +
	"\x15_last_message_previewB\b\n" +
	"\x06_inboxB\x0e\n" +
	"\f_is_strangerB\x15\n" +
	"\x13_dm_peer_profile_id\"^\n" +
	"\bChatList\x121\n" +
	"\x05items\x18\x01 \x03(\v2\x1b.voice.chat.v1.ChatListItemR\x05items\x12\x1f\n" +
	"\vnext_cursor\x18\x02 \x01(\tR\n" +
	"nextCursor\")\n" +
	"\x0eGetChatRequest\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\tR\x06chatId\"\x14\n" +
	"\x12ListFoldersRequest\"=\n" +
	"\n" +
	"FolderList\x12/\n" +
	"\afolders\x18\x01 \x03(\v2\x15.voice.chat.v1.FolderR\afolders\"\x9a\x01\n" +
	"\x06Folder\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1f\n" +
	"\vfolder_type\x18\x03 \x01(\tR\n" +
	"folderType\x12,\n" +
	"\x12filter_config_json\x18\x04 \x01(\tR\x10filterConfigJson\x12\x1d\n" +
	"\n" +
	"sort_order\x18\x05 \x01(\x05R\tsortOrder\"W\n" +
	"\x13CreateFolderRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12,\n" +
	"\x12filter_config_json\x18\x02 \x01(\tR\x10filterConfigJson\"\xd1\x01\n" +
	"\x13UpdateFolderRequest\x12\x1b\n" +
	"\tfolder_id\x18\x01 \x01(\tR\bfolderId\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x00R\x04name\x88\x01\x01\x121\n" +
	"\x12filter_config_json\x18\x03 \x01(\tH\x01R\x10filterConfigJson\x88\x01\x01\x12\"\n" +
	"\n" +
	"sort_order\x18\x04 \x01(\x05H\x02R\tsortOrder\x88\x01\x01B\a\n" +
	"\x05_nameB\x15\n" +
	"\x13_filter_config_jsonB\r\n" +
	"\v_sort_order\"2\n" +
	"\x13DeleteFolderRequest\x12\x1b\n" +
	"\tfolder_id\x18\x01 \x01(\tR\bfolderId\"1\n" +
	"\x16AcceptDMRequestRequest\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\tR\x06chatId\"2\n" +
	"\x17DeclineDMRequestRequest\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\tR\x06chatId\"|\n" +
	"\x0fMuteChatRequest\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\tR\x06chatId\x12@\n" +
	"\vmuted_until\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\n" +
	"mutedUntil\x88\x01\x01B\x0e\n" +
	"\f_muted_until\"I\n" +
	"\x12ArchiveChatRequest\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\tR\x06chatId\x12\x1a\n" +
	"\barchived\x18\x02 \x01(\bR\barchived\"T\n" +
	"\aChatRef\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x120\n" +
	"\x04type\x18\x02 \x01(\x0e2\x17.voice.chat.v1.ChatTypeH\x00R\x04type\x88\x01\x01B\a\n" +
	"\x05_type\";\n" +
	"\x10CreateDMResponse\x12'\n" +
	"\x04chat\x18\x01 \x01(\v2\x13.voice.chat.v1.ChatR\x04chat\"8\n" +
	"\rGetDMResponse\x12'\n" +
	"\x04chat\x18\x01 \x01(\v2\x13.voice.chat.v1.ChatR\x04chat\"=\n" +
	"\x12CreateChatResponse\x12'\n" +
	"\x04chat\x18\x01 \x01(\v2\x13.voice.chat.v1.ChatR\x04chat\"=\n" +
	"\x12UpdateChatResponse\x12'\n" +
	"\x04chat\x18\x01 \x01(\v2\x13.voice.chat.v1.ChatR\x04chat\"\x14\n" +
	"\x12DeleteChatResponse\"\x14\n" +
	"\x12AddMembersResponse\"\x16\n" +
	"\x14RemoveMemberResponse\"\x13\n" +
	"\x11LeaveChatResponse\"Q\n" +
	"\x13ListMembersResponse\x12:\n" +
	"\vmember_list\x18\x01 \x01(\v2\x19.voice.chat.v1.MemberListR\n" +
	"memberList\"I\n" +
	"\x11ListChatsResponse\x124\n" +
	"\tchat_list\x18\x01 \x01(\v2\x17.voice.chat.v1.ChatListR\bchatList\":\n" +
	"\x0fGetChatResponse\x12'\n" +
	"\x04chat\x18\x01 \x01(\v2\x13.voice.chat.v1.ChatR\x04chat\"Q\n" +
	"\x13ListFoldersResponse\x12:\n" +
	"\vfolder_list\x18\x01 \x01(\v2\x19.voice.chat.v1.FolderListR\n" +
	"folderList\"E\n" +
	"\x14CreateFolderResponse\x12-\n" +
	"\x06folder\x18\x01 \x01(\v2\x15.voice.chat.v1.FolderR\x06folder\"E\n" +
	"\x14UpdateFolderResponse\x12-\n" +
	"\x06folder\x18\x01 \x01(\v2\x15.voice.chat.v1.FolderR\x06folder\"\x16\n" +
	"\x14DeleteFolderResponse\"\x19\n" +
	"\x17AcceptDMRequestResponse\"\x1a\n" +
	"\x18DeclineDMRequestResponse\"\x12\n" +
	"\x10MuteChatResponse\"\x15\n" +
	"\x13ArchiveChatResponse*c\n" +
	"\bChatType\x12\x19\n" +
	"\x15CHAT_TYPE_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fCHAT_TYPE_DM\x10\x01\x12\x13\n" +
	"\x0fCHAT_TYPE_GROUP\x10\x02\x12\x15\n" +
	"\x11CHAT_TYPE_CHANNEL\x10\x032\xce\f\n" +
	"\vChatService\x12K\n" +
	"\bCreateDM\x12\x1e.voice.chat.v1.CreateDMRequest\x1a\x1f.voice.chat.v1.CreateDMResponse\x12B\n" +
	"\x05GetDM\x12\x1b.voice.chat.v1.GetDMRequest\x1a\x1c.voice.chat.v1.GetDMResponse\x12Q\n" +
	"\n" +
	"CreateChat\x12 .voice.chat.v1.CreateChatRequest\x1a!.voice.chat.v1.CreateChatResponse\x12Q\n" +
	"\n" +
	"UpdateChat\x12 .voice.chat.v1.UpdateChatRequest\x1a!.voice.chat.v1.UpdateChatResponse\x12Q\n" +
	"\n" +
	"DeleteChat\x12 .voice.chat.v1.DeleteChatRequest\x1a!.voice.chat.v1.DeleteChatResponse\x12Q\n" +
	"\n" +
	"AddMembers\x12 .voice.chat.v1.AddMembersRequest\x1a!.voice.chat.v1.AddMembersResponse\x12W\n" +
	"\fRemoveMember\x12\".voice.chat.v1.RemoveMemberRequest\x1a#.voice.chat.v1.RemoveMemberResponse\x12N\n" +
	"\tLeaveChat\x12\x1f.voice.chat.v1.LeaveChatRequest\x1a .voice.chat.v1.LeaveChatResponse\x12T\n" +
	"\vListMembers\x12!.voice.chat.v1.ListMembersRequest\x1a\".voice.chat.v1.ListMembersResponse\x12N\n" +
	"\tListChats\x12\x1f.voice.chat.v1.ListChatsRequest\x1a .voice.chat.v1.ListChatsResponse\x12H\n" +
	"\aGetChat\x12\x1d.voice.chat.v1.GetChatRequest\x1a\x1e.voice.chat.v1.GetChatResponse\x12T\n" +
	"\vListFolders\x12!.voice.chat.v1.ListFoldersRequest\x1a\".voice.chat.v1.ListFoldersResponse\x12W\n" +
	"\fCreateFolder\x12\".voice.chat.v1.CreateFolderRequest\x1a#.voice.chat.v1.CreateFolderResponse\x12W\n" +
	"\fUpdateFolder\x12\".voice.chat.v1.UpdateFolderRequest\x1a#.voice.chat.v1.UpdateFolderResponse\x12W\n" +
	"\fDeleteFolder\x12\".voice.chat.v1.DeleteFolderRequest\x1a#.voice.chat.v1.DeleteFolderResponse\x12`\n" +
	"\x0fAcceptDMRequest\x12%.voice.chat.v1.AcceptDMRequestRequest\x1a&.voice.chat.v1.AcceptDMRequestResponse\x12c\n" +
	"\x10DeclineDMRequest\x12&.voice.chat.v1.DeclineDMRequestRequest\x1a'.voice.chat.v1.DeclineDMRequestResponse\x12K\n" +
	"\bMuteChat\x12\x1e.voice.chat.v1.MuteChatRequest\x1a\x1f.voice.chat.v1.MuteChatResponse\x12T\n" +
	"\vArchiveChat\x12!.voice.chat.v1.ArchiveChatRequest\x1a\".voice.chat.v1.ArchiveChatResponseB Z\x1evoice.app/voice/chat/v1;chatv1b\x06proto3"

var (
	file_voice_chat_v1_chat_proto_rawDescOnce sync.Once
	file_voice_chat_v1_chat_proto_rawDescData []byte
)

func file_voice_chat_v1_chat_proto_rawDescGZIP() []byte {
	file_voice_chat_v1_chat_proto_rawDescOnce.Do(func() {
		file_voice_chat_v1_chat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_voice_chat_v1_chat_proto_rawDesc), len(file_voice_chat_v1_chat_proto_rawDesc)))
	})
	return file_voice_chat_v1_chat_proto_rawDescData
}

var file_voice_chat_v1_chat_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_voice_chat_v1_chat_proto_msgTypes = make([]protoimpl.MessageInfo, 46)
var file_voice_chat_v1_chat_proto_goTypes = []any{
	(ChatType)(0),                    // 0: voice.chat.v1.ChatType
	(*Chat)(nil),                     // 1: voice.chat.v1.Chat
	(*CreateDMRequest)(nil),          // 2: voice.chat.v1.CreateDMRequest
	(*GetDMRequest)(nil),             // 3: voice.chat.v1.GetDMRequest
	(*CreateChatRequest)(nil),        // 4: voice.chat.v1.CreateChatRequest
	(*UpdateChatRequest)(nil),        // 5: voice.chat.v1.UpdateChatRequest
	(*DeleteChatRequest)(nil),        // 6: voice.chat.v1.DeleteChatRequest
	(*AddMembersRequest)(nil),        // 7: voice.chat.v1.AddMembersRequest
	(*RemoveMemberRequest)(nil),      // 8: voice.chat.v1.RemoveMemberRequest
	(*LeaveChatRequest)(nil),         // 9: voice.chat.v1.LeaveChatRequest
	(*ListMembersRequest)(nil),       // 10: voice.chat.v1.ListMembersRequest
	(*MemberList)(nil),               // 11: voice.chat.v1.MemberList
	(*ChatMember)(nil),               // 12: voice.chat.v1.ChatMember
	(*ListChatsRequest)(nil),         // 13: voice.chat.v1.ListChatsRequest
	(*ChatListItem)(nil),             // 14: voice.chat.v1.ChatListItem
	(*ChatList)(nil),                 // 15: voice.chat.v1.ChatList
	(*GetChatRequest)(nil),           // 16: voice.chat.v1.GetChatRequest
	(*ListFoldersRequest)(nil),       // 17: voice.chat.v1.ListFoldersRequest
	(*FolderList)(nil),               // 18: voice.chat.v1.FolderList
	(*Folder)(nil),                   // 19: voice.chat.v1.Folder
	(*CreateFolderRequest)(nil),      // 20: voice.chat.v1.CreateFolderRequest
	(*UpdateFolderRequest)(nil),      // 21: voice.chat.v1.UpdateFolderRequest
	(*DeleteFolderRequest)(nil),      // 22: voice.chat.v1.DeleteFolderRequest
	(*AcceptDMRequestRequest)(nil),   // 23: voice.chat.v1.AcceptDMRequestRequest
	(*DeclineDMRequestRequest)(nil),  // 24: voice.chat.v1.DeclineDMRequestRequest
	(*MuteChatRequest)(nil),          // 25: voice.chat.v1.MuteChatRequest
	(*ArchiveChatRequest)(nil),       // 26: voice.chat.v1.ArchiveChatRequest
	(*ChatRef)(nil),                  // 27: voice.chat.v1.ChatRef
	(*CreateDMResponse)(nil),         // 28: voice.chat.v1.CreateDMResponse
	(*GetDMResponse)(nil),            // 29: voice.chat.v1.GetDMResponse
	(*CreateChatResponse)(nil),       // 30: voice.chat.v1.CreateChatResponse
	(*UpdateChatResponse)(nil),       // 31: voice.chat.v1.UpdateChatResponse
	(*DeleteChatResponse)(nil),       // 32: voice.chat.v1.DeleteChatResponse
	(*AddMembersResponse)(nil),       // 33: voice.chat.v1.AddMembersResponse
	(*RemoveMemberResponse)(nil),     // 34: voice.chat.v1.RemoveMemberResponse
	(*LeaveChatResponse)(nil),        // 35: voice.chat.v1.LeaveChatResponse
	(*ListMembersResponse)(nil),      // 36: voice.chat.v1.ListMembersResponse
	(*ListChatsResponse)(nil),        // 37: voice.chat.v1.ListChatsResponse
	(*GetChatResponse)(nil),          // 38: voice.chat.v1.GetChatResponse
	(*ListFoldersResponse)(nil),      // 39: voice.chat.v1.ListFoldersResponse
	(*CreateFolderResponse)(nil),     // 40: voice.chat.v1.CreateFolderResponse
	(*UpdateFolderResponse)(nil),     // 41: voice.chat.v1.UpdateFolderResponse
	(*DeleteFolderResponse)(nil),     // 42: voice.chat.v1.DeleteFolderResponse
	(*AcceptDMRequestResponse)(nil),  // 43: voice.chat.v1.AcceptDMRequestResponse
	(*DeclineDMRequestResponse)(nil), // 44: voice.chat.v1.DeclineDMRequestResponse
	(*MuteChatResponse)(nil),         // 45: voice.chat.v1.MuteChatResponse
	(*ArchiveChatResponse)(nil),      // 46: voice.chat.v1.ArchiveChatResponse
	(*timestamppb.Timestamp)(nil),    // 47: google.protobuf.Timestamp
	(*v1.CursorPageRequest)(nil),     // 48: voice.common.v1.CursorPageRequest
}
var file_voice_chat_v1_chat_proto_depIdxs = []int32{
	0,  // 0: voice.chat.v1.Chat.type:type_name -> voice.chat.v1.ChatType
	47, // 1: voice.chat.v1.Chat.last_message_at:type_name -> google.protobuf.Timestamp
	47, // 2: voice.chat.v1.Chat.created_at:type_name -> google.protobuf.Timestamp
	47, // 3: voice.chat.v1.Chat.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 4: voice.chat.v1.CreateChatRequest.type:type_name -> voice.chat.v1.ChatType
	48, // 5: voice.chat.v1.ListMembersRequest.page:type_name -> voice.common.v1.CursorPageRequest
	12, // 6: voice.chat.v1.MemberList.members:type_name -> voice.chat.v1.ChatMember
	47, // 7: voice.chat.v1.ChatMember.joined_at:type_name -> google.protobuf.Timestamp
	47, // 8: voice.chat.v1.ChatMember.muted_until:type_name -> google.protobuf.Timestamp
	48, // 9: voice.chat.v1.ListChatsRequest.page:type_name -> voice.common.v1.CursorPageRequest
	1,  // 10: voice.chat.v1.ChatListItem.chat:type_name -> voice.chat.v1.Chat
	14, // 11: voice.chat.v1.ChatList.items:type_name -> voice.chat.v1.ChatListItem
	19, // 12: voice.chat.v1.FolderList.folders:type_name -> voice.chat.v1.Folder
	47, // 13: voice.chat.v1.MuteChatRequest.muted_until:type_name -> google.protobuf.Timestamp
	0,  // 14: voice.chat.v1.ChatRef.type:type_name -> voice.chat.v1.ChatType
	1,  // 15: voice.chat.v1.CreateDMResponse.chat:type_name -> voice.chat.v1.Chat
	1,  // 16: voice.chat.v1.GetDMResponse.chat:type_name -> voice.chat.v1.Chat
	1,  // 17: voice.chat.v1.CreateChatResponse.chat:type_name -> voice.chat.v1.Chat
	1,  // 18: voice.chat.v1.UpdateChatResponse.chat:type_name -> voice.chat.v1.Chat
	11, // 19: voice.chat.v1.ListMembersResponse.member_list:type_name -> voice.chat.v1.MemberList
	15, // 20: voice.chat.v1.ListChatsResponse.chat_list:type_name -> voice.chat.v1.ChatList
	1,  // 21: voice.chat.v1.GetChatResponse.chat:type_name -> voice.chat.v1.Chat
	18, // 22: voice.chat.v1.ListFoldersResponse.folder_list:type_name -> voice.chat.v1.FolderList
	19, // 23: voice.chat.v1.CreateFolderResponse.folder:type_name -> voice.chat.v1.Folder
	19, // 24: voice.chat.v1.UpdateFolderResponse.folder:type_name -> voice.chat.v1.Folder
	2,  // 25: voice.chat.v1.ChatService.CreateDM:input_type -> voice.chat.v1.CreateDMRequest
	3,  // 26: voice.chat.v1.ChatService.GetDM:input_type -> voice.chat.v1.GetDMRequest
	4,  // 27: voice.chat.v1.ChatService.CreateChat:input_type -> voice.chat.v1.CreateChatRequest
	5,  // 28: voice.chat.v1.ChatService.UpdateChat:input_type -> voice.chat.v1.UpdateChatRequest
	6,  // 29: voice.chat.v1.ChatService.DeleteChat:input_type -> voice.chat.v1.DeleteChatRequest
	7,  // 30: voice.chat.v1.ChatService.AddMembers:input_type -> voice.chat.v1.AddMembersRequest
	8,  // 31: voice.chat.v1.ChatService.RemoveMember:input_type -> voice.chat.v1.RemoveMemberRequest
	9,  // 32: voice.chat.v1.ChatService.LeaveChat:input_type -> voice.chat.v1.LeaveChatRequest
	10, // 33: voice.chat.v1.ChatService.ListMembers:input_type -> voice.chat.v1.ListMembersRequest
	13, // 34: voice.chat.v1.ChatService.ListChats:input_type -> voice.chat.v1.ListChatsRequest
	16, // 35: voice.chat.v1.ChatService.GetChat:input_type -> voice.chat.v1.GetChatRequest
	17, // 36: voice.chat.v1.ChatService.ListFolders:input_type -> voice.chat.v1.ListFoldersRequest
	20, // 37: voice.chat.v1.ChatService.CreateFolder:input_type -> voice.chat.v1.CreateFolderRequest
	21, // 38: voice.chat.v1.ChatService.UpdateFolder:input_type -> voice.chat.v1.UpdateFolderRequest
	22, // 39: voice.chat.v1.ChatService.DeleteFolder:input_type -> voice.chat.v1.DeleteFolderRequest
	23, // 40: voice.chat.v1.ChatService.AcceptDMRequest:input_type -> voice.chat.v1.AcceptDMRequestRequest
	24, // 41: voice.chat.v1.ChatService.DeclineDMRequest:input_type -> voice.chat.v1.DeclineDMRequestRequest
	25, // 42: voice.chat.v1.ChatService.MuteChat:input_type -> voice.chat.v1.MuteChatRequest
	26, // 43: voice.chat.v1.ChatService.ArchiveChat:input_type -> voice.chat.v1.ArchiveChatRequest
	28, // 44: voice.chat.v1.ChatService.CreateDM:output_type -> voice.chat.v1.CreateDMResponse
	29, // 45: voice.chat.v1.ChatService.GetDM:output_type -> voice.chat.v1.GetDMResponse
	30, // 46: voice.chat.v1.ChatService.CreateChat:output_type -> voice.chat.v1.CreateChatResponse
	31, // 47: voice.chat.v1.ChatService.UpdateChat:output_type -> voice.chat.v1.UpdateChatResponse
	32, // 48: voice.chat.v1.ChatService.DeleteChat:output_type -> voice.chat.v1.DeleteChatResponse
	33, // 49: voice.chat.v1.ChatService.AddMembers:output_type -> voice.chat.v1.AddMembersResponse
	34, // 50: voice.chat.v1.ChatService.RemoveMember:output_type -> voice.chat.v1.RemoveMemberResponse
	35, // 51: voice.chat.v1.ChatService.LeaveChat:output_type -> voice.chat.v1.LeaveChatResponse
	36, // 52: voice.chat.v1.ChatService.ListMembers:output_type -> voice.chat.v1.ListMembersResponse
	37, // 53: voice.chat.v1.ChatService.ListChats:output_type -> voice.chat.v1.ListChatsResponse
	38, // 54: voice.chat.v1.ChatService.GetChat:output_type -> voice.chat.v1.GetChatResponse
	39, // 55: voice.chat.v1.ChatService.ListFolders:output_type -> voice.chat.v1.ListFoldersResponse
	40, // 56: voice.chat.v1.ChatService.CreateFolder:output_type -> voice.chat.v1.CreateFolderResponse
	41, // 57: voice.chat.v1.ChatService.UpdateFolder:output_type -> voice.chat.v1.UpdateFolderResponse
	42, // 58: voice.chat.v1.ChatService.DeleteFolder:output_type -> voice.chat.v1.DeleteFolderResponse
	43, // 59: voice.chat.v1.ChatService.AcceptDMRequest:output_type -> voice.chat.v1.AcceptDMRequestResponse
	44, // 60: voice.chat.v1.ChatService.DeclineDMRequest:output_type -> voice.chat.v1.DeclineDMRequestResponse
	45, // 61: voice.chat.v1.ChatService.MuteChat:output_type -> voice.chat.v1.MuteChatResponse
	46, // 62: voice.chat.v1.ChatService.ArchiveChat:output_type -> voice.chat.v1.ArchiveChatResponse
	44, // [44:63] is the sub-list for method output_type
	25, // [25:44] is the sub-list for method input_type
	25, // [25:25] is the sub-list for extension type_name
	25, // [25:25] is the sub-list for extension extendee
	0,  // [0:25] is the sub-list for field type_name
}

func init() { file_voice_chat_v1_chat_proto_init() }
func file_voice_chat_v1_chat_proto_init() {
	if File_voice_chat_v1_chat_proto != nil {
		return
	}
	file_voice_chat_v1_chat_proto_msgTypes[0].OneofWrappers = []any{}
	file_voice_chat_v1_chat_proto_msgTypes[3].OneofWrappers = []any{}
	file_voice_chat_v1_chat_proto_msgTypes[4].OneofWrappers = []any{}
	file_voice_chat_v1_chat_proto_msgTypes[11].OneofWrappers = []any{}
	file_voice_chat_v1_chat_proto_msgTypes[12].OneofWrappers = []any{}
	file_voice_chat_v1_chat_proto_msgTypes[13].OneofWrappers = []any{}
	file_voice_chat_v1_chat_proto_msgTypes[20].OneofWrappers = []any{}
	file_voice_chat_v1_chat_proto_msgTypes[24].OneofWrappers = []any{}
	file_voice_chat_v1_chat_proto_msgTypes[26].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_voice_chat_v1_chat_proto_rawDesc), len(file_voice_chat_v1_chat_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   46,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_voice_chat_v1_chat_proto_goTypes,
		DependencyIndexes: file_voice_chat_v1_chat_proto_depIdxs,
		EnumInfos:         file_voice_chat_v1_chat_proto_enumTypes,
		MessageInfos:      file_voice_chat_v1_chat_proto_msgTypes,
	}.Build()
	File_voice_chat_v1_chat_proto = out.File
	file_voice_chat_v1_chat_proto_goTypes = nil
	file_voice_chat_v1_chat_proto_depIdxs = nil
}
