// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: voice/authority/v1/authority.proto

package authorityv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AuthoritySourceService_ReadSnapshot_FullMethodName = "/voice.authority.v1.AuthoritySourceService/ReadSnapshot"
	AuthoritySourceService_ReadRevision_FullMethodName = "/voice.authority.v1.AuthoritySourceService/ReadRevision"
)

// AuthoritySourceServiceClient is the client API for AuthoritySourceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Internal owner reads. No public Gateway route or game-node caller is allowed.
// Each server verifies its own audience and exact signed request binding.
type AuthoritySourceServiceClient interface {
	// @voice.security=protected;callers=service:federation
	ReadSnapshot(ctx context.Context, in *ReadSnapshotRequest, opts ...grpc.CallOption) (*ReadSnapshotResponse, error)
	// @voice.security=protected;callers=service:federation
	ReadRevision(ctx context.Context, in *ReadRevisionRequest, opts ...grpc.CallOption) (*ReadRevisionResponse, error)
}

type authoritySourceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthoritySourceServiceClient(cc grpc.ClientConnInterface) AuthoritySourceServiceClient {
	return &authoritySourceServiceClient{cc}
}

func (c *authoritySourceServiceClient) ReadSnapshot(ctx context.Context, in *ReadSnapshotRequest, opts ...grpc.CallOption) (*ReadSnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadSnapshotResponse)
	err := c.cc.Invoke(ctx, AuthoritySourceService_ReadSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authoritySourceServiceClient) ReadRevision(ctx context.Context, in *ReadRevisionRequest, opts ...grpc.CallOption) (*ReadRevisionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadRevisionResponse)
	err := c.cc.Invoke(ctx, AuthoritySourceService_ReadRevision_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthoritySourceServiceServer is the server API for AuthoritySourceService service.
// All implementations must embed UnimplementedAuthoritySourceServiceServer
// for forward compatibility.
//
// Internal owner reads. No public Gateway route or game-node caller is allowed.
// Each server verifies its own audience and exact signed request binding.
type AuthoritySourceServiceServer interface {
	// @voice.security=protected;callers=service:federation
	ReadSnapshot(context.Context, *ReadSnapshotRequest) (*ReadSnapshotResponse, error)
	// @voice.security=protected;callers=service:federation
	ReadRevision(context.Context, *ReadRevisionRequest) (*ReadRevisionResponse, error)
	mustEmbedUnimplementedAuthoritySourceServiceServer()
}

// UnimplementedAuthoritySourceServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAuthoritySourceServiceServer struct{}

func (UnimplementedAuthoritySourceServiceServer) ReadSnapshot(context.Context, *ReadSnapshotRequest) (*ReadSnapshotResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadSnapshot not implemented")
}
func (UnimplementedAuthoritySourceServiceServer) ReadRevision(context.Context, *ReadRevisionRequest) (*ReadRevisionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadRevision not implemented")
}
func (UnimplementedAuthoritySourceServiceServer) mustEmbedUnimplementedAuthoritySourceServiceServer() {
}
func (UnimplementedAuthoritySourceServiceServer) testEmbeddedByValue() {}

// UnsafeAuthoritySourceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthoritySourceServiceServer will
// result in compilation errors.
type UnsafeAuthoritySourceServiceServer interface {
	mustEmbedUnimplementedAuthoritySourceServiceServer()
}

func RegisterAuthoritySourceServiceServer(s grpc.ServiceRegistrar, srv AuthoritySourceServiceServer) {
	// If the following call pancis, it indicates UnimplementedAuthoritySourceServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AuthoritySourceService_ServiceDesc, srv)
}

func _AuthoritySourceService_ReadSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthoritySourceServiceServer).ReadSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthoritySourceService_ReadSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthoritySourceServiceServer).ReadSnapshot(ctx, req.(*ReadSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthoritySourceService_ReadRevision_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadRevisionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthoritySourceServiceServer).ReadRevision(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthoritySourceService_ReadRevision_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthoritySourceServiceServer).ReadRevision(ctx, req.(*ReadRevisionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AuthoritySourceService_ServiceDesc is the grpc.ServiceDesc for AuthoritySourceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuthoritySourceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "voice.authority.v1.AuthoritySourceService",
	HandlerType: (*AuthoritySourceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReadSnapshot",
			Handler:    _AuthoritySourceService_ReadSnapshot_Handler,
		},
		{
			MethodName: "ReadRevision",
			Handler:    _AuthoritySourceService_ReadRevision_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "voice/authority/v1/authority.proto",
}
