// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: voice/moderation/v1/moderation.proto

package moderationv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ModerationService_CreateReport_FullMethodName        = "/voice.moderation.v1.ModerationService/CreateReport"
	ModerationService_GetReport_FullMethodName           = "/voice.moderation.v1.ModerationService/GetReport"
	ModerationService_ListReports_FullMethodName         = "/voice.moderation.v1.ModerationService/ListReports"
	ModerationService_ResolveReport_FullMethodName       = "/voice.moderation.v1.ModerationService/ResolveReport"
	ModerationService_ApplySanction_FullMethodName       = "/voice.moderation.v1.ModerationService/ApplySanction"
	ModerationService_RevokeSanction_FullMethodName      = "/voice.moderation.v1.ModerationService/RevokeSanction"
	ModerationService_GetAccountSanctions_FullMethodName = "/voice.moderation.v1.ModerationService/GetAccountSanctions"
	ModerationService_GetActiveSanction_FullMethodName   = "/voice.moderation.v1.ModerationService/GetActiveSanction"
	ModerationService_SubmitAppeal_FullMethodName        = "/voice.moderation.v1.ModerationService/SubmitAppeal"
	ModerationService_ReviewAppeal_FullMethodName        = "/voice.moderation.v1.ModerationService/ReviewAppeal"
	ModerationService_GetAppeal_FullMethodName           = "/voice.moderation.v1.ModerationService/GetAppeal"
	ModerationService_CheckMessage_FullMethodName        = "/voice.moderation.v1.ModerationService/CheckMessage"
	ModerationService_GetAutoModStats_FullMethodName     = "/voice.moderation.v1.ModerationService/GetAutoModStats"
	ModerationService_IsShadowBanned_FullMethodName      = "/voice.moderation.v1.ModerationService/IsShadowBanned"
)

// ModerationServiceClient is the client API for ModerationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Reports, sanctions, automod. HTTP: /api/v1/moderation/**.
type ModerationServiceClient interface {
	CreateReport(ctx context.Context, in *CreateReportRequest, opts ...grpc.CallOption) (*CreateReportResponse, error)
	GetReport(ctx context.Context, in *GetReportRequest, opts ...grpc.CallOption) (*GetReportResponse, error)
	ListReports(ctx context.Context, in *ListReportsRequest, opts ...grpc.CallOption) (*ListReportsResponse, error)
	ResolveReport(ctx context.Context, in *ResolveReportRequest, opts ...grpc.CallOption) (*ResolveReportResponse, error)
	ApplySanction(ctx context.Context, in *ApplySanctionRequest, opts ...grpc.CallOption) (*ApplySanctionResponse, error)
	RevokeSanction(ctx context.Context, in *RevokeSanctionRequest, opts ...grpc.CallOption) (*RevokeSanctionResponse, error)
	GetAccountSanctions(ctx context.Context, in *GetAccountSanctionsRequest, opts ...grpc.CallOption) (*GetAccountSanctionsResponse, error)
	GetActiveSanction(ctx context.Context, in *GetActiveSanctionRequest, opts ...grpc.CallOption) (*GetActiveSanctionResponse, error)
	SubmitAppeal(ctx context.Context, in *SubmitAppealRequest, opts ...grpc.CallOption) (*SubmitAppealResponse, error)
	ReviewAppeal(ctx context.Context, in *ReviewAppealRequest, opts ...grpc.CallOption) (*ReviewAppealResponse, error)
	GetAppeal(ctx context.Context, in *GetAppealRequest, opts ...grpc.CallOption) (*GetAppealResponse, error)
	CheckMessage(ctx context.Context, in *CheckMessageRequest, opts ...grpc.CallOption) (*CheckMessageResponse, error)
	GetAutoModStats(ctx context.Context, in *GetAutoModStatsRequest, opts ...grpc.CallOption) (*GetAutoModStatsResponse, error)
	IsShadowBanned(ctx context.Context, in *IsShadowBannedRequest, opts ...grpc.CallOption) (*IsShadowBannedResponse, error)
}

type moderationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewModerationServiceClient(cc grpc.ClientConnInterface) ModerationServiceClient {
	return &moderationServiceClient{cc}
}

func (c *moderationServiceClient) CreateReport(ctx context.Context, in *CreateReportRequest, opts ...grpc.CallOption) (*CreateReportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateReportResponse)
	err := c.cc.Invoke(ctx, ModerationService_CreateReport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moderationServiceClient) GetReport(ctx context.Context, in *GetReportRequest, opts ...grpc.CallOption) (*GetReportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetReportResponse)
	err := c.cc.Invoke(ctx, ModerationService_GetReport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moderationServiceClient) ListReports(ctx context.Context, in *ListReportsRequest, opts ...grpc.CallOption) (*ListReportsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListReportsResponse)
	err := c.cc.Invoke(ctx, ModerationService_ListReports_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moderationServiceClient) ResolveReport(ctx context.Context, in *ResolveReportRequest, opts ...grpc.CallOption) (*ResolveReportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResolveReportResponse)
	err := c.cc.Invoke(ctx, ModerationService_ResolveReport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moderationServiceClient) ApplySanction(ctx context.Context, in *ApplySanctionRequest, opts ...grpc.CallOption) (*ApplySanctionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplySanctionResponse)
	err := c.cc.Invoke(ctx, ModerationService_ApplySanction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moderationServiceClient) RevokeSanction(ctx context.Context, in *RevokeSanctionRequest, opts ...grpc.CallOption) (*RevokeSanctionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RevokeSanctionResponse)
	err := c.cc.Invoke(ctx, ModerationService_RevokeSanction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moderationServiceClient) GetAccountSanctions(ctx context.Context, in *GetAccountSanctionsRequest, opts ...grpc.CallOption) (*GetAccountSanctionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAccountSanctionsResponse)
	err := c.cc.Invoke(ctx, ModerationService_GetAccountSanctions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moderationServiceClient) GetActiveSanction(ctx context.Context, in *GetActiveSanctionRequest, opts ...grpc.CallOption) (*GetActiveSanctionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetActiveSanctionResponse)
	err := c.cc.Invoke(ctx, ModerationService_GetActiveSanction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moderationServiceClient) SubmitAppeal(ctx context.Context, in *SubmitAppealRequest, opts ...grpc.CallOption) (*SubmitAppealResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitAppealResponse)
	err := c.cc.Invoke(ctx, ModerationService_SubmitAppeal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moderationServiceClient) ReviewAppeal(ctx context.Context, in *ReviewAppealRequest, opts ...grpc.CallOption) (*ReviewAppealResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReviewAppealResponse)
	err := c.cc.Invoke(ctx, ModerationService_ReviewAppeal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moderationServiceClient) GetAppeal(ctx context.Context, in *GetAppealRequest, opts ...grpc.CallOption) (*GetAppealResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAppealResponse)
	err := c.cc.Invoke(ctx, ModerationService_GetAppeal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moderationServiceClient) CheckMessage(ctx context.Context, in *CheckMessageRequest, opts ...grpc.CallOption) (*CheckMessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckMessageResponse)
	err := c.cc.Invoke(ctx, ModerationService_CheckMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moderationServiceClient) GetAutoModStats(ctx context.Context, in *GetAutoModStatsRequest, opts ...grpc.CallOption) (*GetAutoModStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAutoModStatsResponse)
	err := c.cc.Invoke(ctx, ModerationService_GetAutoModStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moderationServiceClient) IsShadowBanned(ctx context.Context, in *IsShadowBannedRequest, opts ...grpc.CallOption) (*IsShadowBannedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IsShadowBannedResponse)
	err := c.cc.Invoke(ctx, ModerationService_IsShadowBanned_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ModerationServiceServer is the server API for ModerationService service.
// All implementations must embed UnimplementedModerationServiceServer
// for forward compatibility.
//
// Reports, sanctions, automod. HTTP: /api/v1/moderation/**.
type ModerationServiceServer interface {
	CreateReport(context.Context, *CreateReportRequest) (*CreateReportResponse, error)
	GetReport(context.Context, *GetReportRequest) (*GetReportResponse, error)
	ListReports(context.Context, *ListReportsRequest) (*ListReportsResponse, error)
	ResolveReport(context.Context, *ResolveReportRequest) (*ResolveReportResponse, error)
	ApplySanction(context.Context, *ApplySanctionRequest) (*ApplySanctionResponse, error)
	RevokeSanction(context.Context, *RevokeSanctionRequest) (*RevokeSanctionResponse, error)
	GetAccountSanctions(context.Context, *GetAccountSanctionsRequest) (*GetAccountSanctionsResponse, error)
	GetActiveSanction(context.Context, *GetActiveSanctionRequest) (*GetActiveSanctionResponse, error)
	SubmitAppeal(context.Context, *SubmitAppealRequest) (*SubmitAppealResponse, error)
	ReviewAppeal(context.Context, *ReviewAppealRequest) (*ReviewAppealResponse, error)
	GetAppeal(context.Context, *GetAppealRequest) (*GetAppealResponse, error)
	CheckMessage(context.Context, *CheckMessageRequest) (*CheckMessageResponse, error)
	GetAutoModStats(context.Context, *GetAutoModStatsRequest) (*GetAutoModStatsResponse, error)
	IsShadowBanned(context.Context, *IsShadowBannedRequest) (*IsShadowBannedResponse, error)
	mustEmbedUnimplementedModerationServiceServer()
}

// UnimplementedModerationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedModerationServiceServer struct{}

func (UnimplementedModerationServiceServer) CreateReport(context.Context, *CreateReportRequest) (*CreateReportResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateReport not implemented")
}
func (UnimplementedModerationServiceServer) GetReport(context.Context, *GetReportRequest) (*GetReportResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetReport not implemented")
}
func (UnimplementedModerationServiceServer) ListReports(context.Context, *ListReportsRequest) (*ListReportsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListReports not implemented")
}
func (UnimplementedModerationServiceServer) ResolveReport(context.Context, *ResolveReportRequest) (*ResolveReportResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResolveReport not implemented")
}
func (UnimplementedModerationServiceServer) ApplySanction(context.Context, *ApplySanctionRequest) (*ApplySanctionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApplySanction not implemented")
}
func (UnimplementedModerationServiceServer) RevokeSanction(context.Context, *RevokeSanctionRequest) (*RevokeSanctionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RevokeSanction not implemented")
}
func (UnimplementedModerationServiceServer) GetAccountSanctions(context.Context, *GetAccountSanctionsRequest) (*GetAccountSanctionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAccountSanctions not implemented")
}
func (UnimplementedModerationServiceServer) GetActiveSanction(context.Context, *GetActiveSanctionRequest) (*GetActiveSanctionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetActiveSanction not implemented")
}
func (UnimplementedModerationServiceServer) SubmitAppeal(context.Context, *SubmitAppealRequest) (*SubmitAppealResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitAppeal not implemented")
}
func (UnimplementedModerationServiceServer) ReviewAppeal(context.Context, *ReviewAppealRequest) (*ReviewAppealResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReviewAppeal not implemented")
}
func (UnimplementedModerationServiceServer) GetAppeal(context.Context, *GetAppealRequest) (*GetAppealResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAppeal not implemented")
}
func (UnimplementedModerationServiceServer) CheckMessage(context.Context, *CheckMessageRequest) (*CheckMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckMessage not implemented")
}
func (UnimplementedModerationServiceServer) GetAutoModStats(context.Context, *GetAutoModStatsRequest) (*GetAutoModStatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAutoModStats not implemented")
}
func (UnimplementedModerationServiceServer) IsShadowBanned(context.Context, *IsShadowBannedRequest) (*IsShadowBannedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsShadowBanned not implemented")
}
func (UnimplementedModerationServiceServer) mustEmbedUnimplementedModerationServiceServer() {}
func (UnimplementedModerationServiceServer) testEmbeddedByValue()                           {}

// UnsafeModerationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ModerationServiceServer will
// result in compilation errors.
type UnsafeModerationServiceServer interface {
	mustEmbedUnimplementedModerationServiceServer()
}

func RegisterModerationServiceServer(s grpc.ServiceRegistrar, srv ModerationServiceServer) {
	// If the following call pancis, it indicates UnimplementedModerationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ModerationService_ServiceDesc, srv)
}

func _ModerationService_CreateReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModerationServiceServer).CreateReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModerationService_CreateReport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModerationServiceServer).CreateReport(ctx, req.(*CreateReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModerationService_GetReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModerationServiceServer).GetReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModerationService_GetReport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModerationServiceServer).GetReport(ctx, req.(*GetReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModerationService_ListReports_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListReportsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModerationServiceServer).ListReports(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModerationService_ListReports_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModerationServiceServer).ListReports(ctx, req.(*ListReportsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModerationService_ResolveReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModerationServiceServer).ResolveReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModerationService_ResolveReport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModerationServiceServer).ResolveReport(ctx, req.(*ResolveReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModerationService_ApplySanction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplySanctionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModerationServiceServer).ApplySanction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModerationService_ApplySanction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModerationServiceServer).ApplySanction(ctx, req.(*ApplySanctionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModerationService_RevokeSanction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeSanctionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModerationServiceServer).RevokeSanction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModerationService_RevokeSanction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModerationServiceServer).RevokeSanction(ctx, req.(*RevokeSanctionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModerationService_GetAccountSanctions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAccountSanctionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModerationServiceServer).GetAccountSanctions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModerationService_GetAccountSanctions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModerationServiceServer).GetAccountSanctions(ctx, req.(*GetAccountSanctionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModerationService_GetActiveSanction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetActiveSanctionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModerationServiceServer).GetActiveSanction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModerationService_GetActiveSanction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModerationServiceServer).GetActiveSanction(ctx, req.(*GetActiveSanctionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModerationService_SubmitAppeal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitAppealRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModerationServiceServer).SubmitAppeal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModerationService_SubmitAppeal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModerationServiceServer).SubmitAppeal(ctx, req.(*SubmitAppealRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModerationService_ReviewAppeal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReviewAppealRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModerationServiceServer).ReviewAppeal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModerationService_ReviewAppeal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModerationServiceServer).ReviewAppeal(ctx, req.(*ReviewAppealRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModerationService_GetAppeal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAppealRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModerationServiceServer).GetAppeal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModerationService_GetAppeal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModerationServiceServer).GetAppeal(ctx, req.(*GetAppealRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModerationService_CheckMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModerationServiceServer).CheckMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModerationService_CheckMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModerationServiceServer).CheckMessage(ctx, req.(*CheckMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModerationService_GetAutoModStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAutoModStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModerationServiceServer).GetAutoModStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModerationService_GetAutoModStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModerationServiceServer).GetAutoModStats(ctx, req.(*GetAutoModStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModerationService_IsShadowBanned_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsShadowBannedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModerationServiceServer).IsShadowBanned(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModerationService_IsShadowBanned_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModerationServiceServer).IsShadowBanned(ctx, req.(*IsShadowBannedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ModerationService_ServiceDesc is the grpc.ServiceDesc for ModerationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ModerationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "voice.moderation.v1.ModerationService",
	HandlerType: (*ModerationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateReport",
			Handler:    _ModerationService_CreateReport_Handler,
		},
		{
			MethodName: "GetReport",
			Handler:    _ModerationService_GetReport_Handler,
		},
		{
			MethodName: "ListReports",
			Handler:    _ModerationService_ListReports_Handler,
		},
		{
			MethodName: "ResolveReport",
			Handler:    _ModerationService_ResolveReport_Handler,
		},
		{
			MethodName: "ApplySanction",
			Handler:    _ModerationService_ApplySanction_Handler,
		},
		{
			MethodName: "RevokeSanction",
			Handler:    _ModerationService_RevokeSanction_Handler,
		},
		{
			MethodName: "GetAccountSanctions",
			Handler:    _ModerationService_GetAccountSanctions_Handler,
		},
		{
			MethodName: "GetActiveSanction",
			Handler:    _ModerationService_GetActiveSanction_Handler,
		},
		{
			MethodName: "SubmitAppeal",
			Handler:    _ModerationService_SubmitAppeal_Handler,
		},
		{
			MethodName: "ReviewAppeal",
			Handler:    _ModerationService_ReviewAppeal_Handler,
		},
		{
			MethodName: "GetAppeal",
			Handler:    _ModerationService_GetAppeal_Handler,
		},
		{
			MethodName: "CheckMessage",
			Handler:    _ModerationService_CheckMessage_Handler,
		},
		{
			MethodName: "GetAutoModStats",
			Handler:    _ModerationService_GetAutoModStats_Handler,
		},
		{
			MethodName: "IsShadowBanned",
			Handler:    _ModerationService_IsShadowBanned_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "voice/moderation/v1/moderation.proto",
}
