// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: voice/subscription/v1/subscription.proto

package subscriptionv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SubscriptionService_GetSubscription_FullMethodName            = "/voice.subscription.v1.SubscriptionService/GetSubscription"
	SubscriptionService_CreateCheckoutSession_FullMethodName      = "/voice.subscription.v1.SubscriptionService/CreateCheckoutSession"
	SubscriptionService_CancelSubscription_FullMethodName         = "/voice.subscription.v1.SubscriptionService/CancelSubscription"
	SubscriptionService_ResumeSubscription_FullMethodName         = "/voice.subscription.v1.SubscriptionService/ResumeSubscription"
	SubscriptionService_GetSpaceSubscription_FullMethodName       = "/voice.subscription.v1.SubscriptionService/GetSpaceSubscription"
	SubscriptionService_CreateSpaceCheckoutSession_FullMethodName = "/voice.subscription.v1.SubscriptionService/CreateSpaceCheckoutSession"
	SubscriptionService_GetLimits_FullMethodName                  = "/voice.subscription.v1.SubscriptionService/GetLimits"
	SubscriptionService_CheckLimit_FullMethodName                 = "/voice.subscription.v1.SubscriptionService/CheckLimit"
	SubscriptionService_HandlePaddleWebhook_FullMethodName        = "/voice.subscription.v1.SubscriptionService/HandlePaddleWebhook"
	SubscriptionService_HandleCloudPaymentsWebhook_FullMethodName = "/voice.subscription.v1.SubscriptionService/HandleCloudPaymentsWebhook"
	SubscriptionService_GetBillingHistory_FullMethodName          = "/voice.subscription.v1.SubscriptionService/GetBillingHistory"
	SubscriptionService_ApplyDowngradeProfiles_FullMethodName     = "/voice.subscription.v1.SubscriptionService/ApplyDowngradeProfiles"
)

// SubscriptionServiceClient is the client API for SubscriptionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Billing and limits. HTTP: /api/v1/subscription/**.
type SubscriptionServiceClient interface {
	GetSubscription(ctx context.Context, in *GetSubscriptionRequest, opts ...grpc.CallOption) (*GetSubscriptionResponse, error)
	CreateCheckoutSession(ctx context.Context, in *CreateCheckoutSessionRequest, opts ...grpc.CallOption) (*CreateCheckoutSessionResponse, error)
	CancelSubscription(ctx context.Context, in *CancelSubscriptionRequest, opts ...grpc.CallOption) (*CancelSubscriptionResponse, error)
	ResumeSubscription(ctx context.Context, in *ResumeSubscriptionRequest, opts ...grpc.CallOption) (*ResumeSubscriptionResponse, error)
	GetSpaceSubscription(ctx context.Context, in *GetSpaceSubscriptionRequest, opts ...grpc.CallOption) (*GetSpaceSubscriptionResponse, error)
	CreateSpaceCheckoutSession(ctx context.Context, in *CreateSpaceCheckoutSessionRequest, opts ...grpc.CallOption) (*CreateSpaceCheckoutSessionResponse, error)
	GetLimits(ctx context.Context, in *GetLimitsRequest, opts ...grpc.CallOption) (*GetLimitsResponse, error)
	CheckLimit(ctx context.Context, in *CheckLimitRequest, opts ...grpc.CallOption) (*CheckLimitResponse, error)
	HandlePaddleWebhook(ctx context.Context, in *HandlePaddleWebhookRequest, opts ...grpc.CallOption) (*HandlePaddleWebhookResponse, error)
	HandleCloudPaymentsWebhook(ctx context.Context, in *HandleCloudPaymentsWebhookRequest, opts ...grpc.CallOption) (*HandleCloudPaymentsWebhookResponse, error)
	GetBillingHistory(ctx context.Context, in *GetBillingHistoryRequest, opts ...grpc.CallOption) (*GetBillingHistoryResponse, error)
	// Phase 13: keep selected profiles when downgrading from premium (multi-profile.md).
	ApplyDowngradeProfiles(ctx context.Context, in *ApplyDowngradeProfilesRequest, opts ...grpc.CallOption) (*ApplyDowngradeProfilesResponse, error)
}

type subscriptionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSubscriptionServiceClient(cc grpc.ClientConnInterface) SubscriptionServiceClient {
	return &subscriptionServiceClient{cc}
}

func (c *subscriptionServiceClient) GetSubscription(ctx context.Context, in *GetSubscriptionRequest, opts ...grpc.CallOption) (*GetSubscriptionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSubscriptionResponse)
	err := c.cc.Invoke(ctx, SubscriptionService_GetSubscription_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subscriptionServiceClient) CreateCheckoutSession(ctx context.Context, in *CreateCheckoutSessionRequest, opts ...grpc.CallOption) (*CreateCheckoutSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateCheckoutSessionResponse)
	err := c.cc.Invoke(ctx, SubscriptionService_CreateCheckoutSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subscriptionServiceClient) CancelSubscription(ctx context.Context, in *CancelSubscriptionRequest, opts ...grpc.CallOption) (*CancelSubscriptionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelSubscriptionResponse)
	err := c.cc.Invoke(ctx, SubscriptionService_CancelSubscription_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subscriptionServiceClient) ResumeSubscription(ctx context.Context, in *ResumeSubscriptionRequest, opts ...grpc.CallOption) (*ResumeSubscriptionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResumeSubscriptionResponse)
	err := c.cc.Invoke(ctx, SubscriptionService_ResumeSubscription_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subscriptionServiceClient) GetSpaceSubscription(ctx context.Context, in *GetSpaceSubscriptionRequest, opts ...grpc.CallOption) (*GetSpaceSubscriptionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSpaceSubscriptionResponse)
	err := c.cc.Invoke(ctx, SubscriptionService_GetSpaceSubscription_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subscriptionServiceClient) CreateSpaceCheckoutSession(ctx context.Context, in *CreateSpaceCheckoutSessionRequest, opts ...grpc.CallOption) (*CreateSpaceCheckoutSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateSpaceCheckoutSessionResponse)
	err := c.cc.Invoke(ctx, SubscriptionService_CreateSpaceCheckoutSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subscriptionServiceClient) GetLimits(ctx context.Context, in *GetLimitsRequest, opts ...grpc.CallOption) (*GetLimitsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLimitsResponse)
	err := c.cc.Invoke(ctx, SubscriptionService_GetLimits_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subscriptionServiceClient) CheckLimit(ctx context.Context, in *CheckLimitRequest, opts ...grpc.CallOption) (*CheckLimitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckLimitResponse)
	err := c.cc.Invoke(ctx, SubscriptionService_CheckLimit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subscriptionServiceClient) HandlePaddleWebhook(ctx context.Context, in *HandlePaddleWebhookRequest, opts ...grpc.CallOption) (*HandlePaddleWebhookResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HandlePaddleWebhookResponse)
	err := c.cc.Invoke(ctx, SubscriptionService_HandlePaddleWebhook_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subscriptionServiceClient) HandleCloudPaymentsWebhook(ctx context.Context, in *HandleCloudPaymentsWebhookRequest, opts ...grpc.CallOption) (*HandleCloudPaymentsWebhookResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HandleCloudPaymentsWebhookResponse)
	err := c.cc.Invoke(ctx, SubscriptionService_HandleCloudPaymentsWebhook_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subscriptionServiceClient) GetBillingHistory(ctx context.Context, in *GetBillingHistoryRequest, opts ...grpc.CallOption) (*GetBillingHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBillingHistoryResponse)
	err := c.cc.Invoke(ctx, SubscriptionService_GetBillingHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subscriptionServiceClient) ApplyDowngradeProfiles(ctx context.Context, in *ApplyDowngradeProfilesRequest, opts ...grpc.CallOption) (*ApplyDowngradeProfilesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplyDowngradeProfilesResponse)
	err := c.cc.Invoke(ctx, SubscriptionService_ApplyDowngradeProfiles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SubscriptionServiceServer is the server API for SubscriptionService service.
// All implementations must embed UnimplementedSubscriptionServiceServer
// for forward compatibility.
//
// Billing and limits. HTTP: /api/v1/subscription/**.
type SubscriptionServiceServer interface {
	GetSubscription(context.Context, *GetSubscriptionRequest) (*GetSubscriptionResponse, error)
	CreateCheckoutSession(context.Context, *CreateCheckoutSessionRequest) (*CreateCheckoutSessionResponse, error)
	CancelSubscription(context.Context, *CancelSubscriptionRequest) (*CancelSubscriptionResponse, error)
	ResumeSubscription(context.Context, *ResumeSubscriptionRequest) (*ResumeSubscriptionResponse, error)
	GetSpaceSubscription(context.Context, *GetSpaceSubscriptionRequest) (*GetSpaceSubscriptionResponse, error)
	CreateSpaceCheckoutSession(context.Context, *CreateSpaceCheckoutSessionRequest) (*CreateSpaceCheckoutSessionResponse, error)
	GetLimits(context.Context, *GetLimitsRequest) (*GetLimitsResponse, error)
	CheckLimit(context.Context, *CheckLimitRequest) (*CheckLimitResponse, error)
	HandlePaddleWebhook(context.Context, *HandlePaddleWebhookRequest) (*HandlePaddleWebhookResponse, error)
	HandleCloudPaymentsWebhook(context.Context, *HandleCloudPaymentsWebhookRequest) (*HandleCloudPaymentsWebhookResponse, error)
	GetBillingHistory(context.Context, *GetBillingHistoryRequest) (*GetBillingHistoryResponse, error)
	// Phase 13: keep selected profiles when downgrading from premium (multi-profile.md).
	ApplyDowngradeProfiles(context.Context, *ApplyDowngradeProfilesRequest) (*ApplyDowngradeProfilesResponse, error)
	mustEmbedUnimplementedSubscriptionServiceServer()
}

// UnimplementedSubscriptionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSubscriptionServiceServer struct{}

func (UnimplementedSubscriptionServiceServer) GetSubscription(context.Context, *GetSubscriptionRequest) (*GetSubscriptionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSubscription not implemented")
}
func (UnimplementedSubscriptionServiceServer) CreateCheckoutSession(context.Context, *CreateCheckoutSessionRequest) (*CreateCheckoutSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateCheckoutSession not implemented")
}
func (UnimplementedSubscriptionServiceServer) CancelSubscription(context.Context, *CancelSubscriptionRequest) (*CancelSubscriptionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelSubscription not implemented")
}
func (UnimplementedSubscriptionServiceServer) ResumeSubscription(context.Context, *ResumeSubscriptionRequest) (*ResumeSubscriptionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResumeSubscription not implemented")
}
func (UnimplementedSubscriptionServiceServer) GetSpaceSubscription(context.Context, *GetSpaceSubscriptionRequest) (*GetSpaceSubscriptionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSpaceSubscription not implemented")
}
func (UnimplementedSubscriptionServiceServer) CreateSpaceCheckoutSession(context.Context, *CreateSpaceCheckoutSessionRequest) (*CreateSpaceCheckoutSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSpaceCheckoutSession not implemented")
}
func (UnimplementedSubscriptionServiceServer) GetLimits(context.Context, *GetLimitsRequest) (*GetLimitsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLimits not implemented")
}
func (UnimplementedSubscriptionServiceServer) CheckLimit(context.Context, *CheckLimitRequest) (*CheckLimitResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckLimit not implemented")
}
func (UnimplementedSubscriptionServiceServer) HandlePaddleWebhook(context.Context, *HandlePaddleWebhookRequest) (*HandlePaddleWebhookResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HandlePaddleWebhook not implemented")
}
func (UnimplementedSubscriptionServiceServer) HandleCloudPaymentsWebhook(context.Context, *HandleCloudPaymentsWebhookRequest) (*HandleCloudPaymentsWebhookResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HandleCloudPaymentsWebhook not implemented")
}
func (UnimplementedSubscriptionServiceServer) GetBillingHistory(context.Context, *GetBillingHistoryRequest) (*GetBillingHistoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBillingHistory not implemented")
}
func (UnimplementedSubscriptionServiceServer) ApplyDowngradeProfiles(context.Context, *ApplyDowngradeProfilesRequest) (*ApplyDowngradeProfilesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ApplyDowngradeProfiles not implemented")
}
func (UnimplementedSubscriptionServiceServer) mustEmbedUnimplementedSubscriptionServiceServer() {}
func (UnimplementedSubscriptionServiceServer) testEmbeddedByValue()                             {}

// UnsafeSubscriptionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SubscriptionServiceServer will
// result in compilation errors.
type UnsafeSubscriptionServiceServer interface {
	mustEmbedUnimplementedSubscriptionServiceServer()
}

func RegisterSubscriptionServiceServer(s grpc.ServiceRegistrar, srv SubscriptionServiceServer) {
	// If the following call panics, it indicates UnimplementedSubscriptionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SubscriptionService_ServiceDesc, srv)
}

func _SubscriptionService_GetSubscription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSubscriptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubscriptionServiceServer).GetSubscription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubscriptionService_GetSubscription_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubscriptionServiceServer).GetSubscription(ctx, req.(*GetSubscriptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubscriptionService_CreateCheckoutSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCheckoutSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubscriptionServiceServer).CreateCheckoutSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubscriptionService_CreateCheckoutSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubscriptionServiceServer).CreateCheckoutSession(ctx, req.(*CreateCheckoutSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubscriptionService_CancelSubscription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelSubscriptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubscriptionServiceServer).CancelSubscription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubscriptionService_CancelSubscription_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubscriptionServiceServer).CancelSubscription(ctx, req.(*CancelSubscriptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubscriptionService_ResumeSubscription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResumeSubscriptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubscriptionServiceServer).ResumeSubscription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubscriptionService_ResumeSubscription_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubscriptionServiceServer).ResumeSubscription(ctx, req.(*ResumeSubscriptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubscriptionService_GetSpaceSubscription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSpaceSubscriptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubscriptionServiceServer).GetSpaceSubscription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubscriptionService_GetSpaceSubscription_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubscriptionServiceServer).GetSpaceSubscription(ctx, req.(*GetSpaceSubscriptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubscriptionService_CreateSpaceCheckoutSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSpaceCheckoutSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubscriptionServiceServer).CreateSpaceCheckoutSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubscriptionService_CreateSpaceCheckoutSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubscriptionServiceServer).CreateSpaceCheckoutSession(ctx, req.(*CreateSpaceCheckoutSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubscriptionService_GetLimits_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLimitsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubscriptionServiceServer).GetLimits(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubscriptionService_GetLimits_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubscriptionServiceServer).GetLimits(ctx, req.(*GetLimitsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubscriptionService_CheckLimit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckLimitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubscriptionServiceServer).CheckLimit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubscriptionService_CheckLimit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubscriptionServiceServer).CheckLimit(ctx, req.(*CheckLimitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubscriptionService_HandlePaddleWebhook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HandlePaddleWebhookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubscriptionServiceServer).HandlePaddleWebhook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubscriptionService_HandlePaddleWebhook_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubscriptionServiceServer).HandlePaddleWebhook(ctx, req.(*HandlePaddleWebhookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubscriptionService_HandleCloudPaymentsWebhook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HandleCloudPaymentsWebhookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubscriptionServiceServer).HandleCloudPaymentsWebhook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubscriptionService_HandleCloudPaymentsWebhook_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubscriptionServiceServer).HandleCloudPaymentsWebhook(ctx, req.(*HandleCloudPaymentsWebhookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubscriptionService_GetBillingHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBillingHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubscriptionServiceServer).GetBillingHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubscriptionService_GetBillingHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubscriptionServiceServer).GetBillingHistory(ctx, req.(*GetBillingHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubscriptionService_ApplyDowngradeProfiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyDowngradeProfilesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubscriptionServiceServer).ApplyDowngradeProfiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubscriptionService_ApplyDowngradeProfiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubscriptionServiceServer).ApplyDowngradeProfiles(ctx, req.(*ApplyDowngradeProfilesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SubscriptionService_ServiceDesc is the grpc.ServiceDesc for SubscriptionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SubscriptionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "voice.subscription.v1.SubscriptionService",
	HandlerType: (*SubscriptionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSubscription",
			Handler:    _SubscriptionService_GetSubscription_Handler,
		},
		{
			MethodName: "CreateCheckoutSession",
			Handler:    _SubscriptionService_CreateCheckoutSession_Handler,
		},
		{
			MethodName: "CancelSubscription",
			Handler:    _SubscriptionService_CancelSubscription_Handler,
		},
		{
			MethodName: "ResumeSubscription",
			Handler:    _SubscriptionService_ResumeSubscription_Handler,
		},
		{
			MethodName: "GetSpaceSubscription",
			Handler:    _SubscriptionService_GetSpaceSubscription_Handler,
		},
		{
			MethodName: "CreateSpaceCheckoutSession",
			Handler:    _SubscriptionService_CreateSpaceCheckoutSession_Handler,
		},
		{
			MethodName: "GetLimits",
			Handler:    _SubscriptionService_GetLimits_Handler,
		},
		{
			MethodName: "CheckLimit",
			Handler:    _SubscriptionService_CheckLimit_Handler,
		},
		{
			MethodName: "HandlePaddleWebhook",
			Handler:    _SubscriptionService_HandlePaddleWebhook_Handler,
		},
		{
			MethodName: "HandleCloudPaymentsWebhook",
			Handler:    _SubscriptionService_HandleCloudPaymentsWebhook_Handler,
		},
		{
			MethodName: "GetBillingHistory",
			Handler:    _SubscriptionService_GetBillingHistory_Handler,
		},
		{
			MethodName: "ApplyDowngradeProfiles",
			Handler:    _SubscriptionService_ApplyDowngradeProfiles_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "voice/subscription/v1/subscription.proto",
}
