// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: voice/calls/v1/calls.proto

package callsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
	v1 "voice.app/voice/chat/v1"
	v11 "voice.app/voice/space/v1"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Canonical values for room_type strings (StartCallRequest, CallSession).
type VoiceSessionKind int32

const (
	VoiceSessionKind_VOICE_SESSION_KIND_UNSPECIFIED VoiceSessionKind = 0
	VoiceSessionKind_VOICE_SESSION_KIND_CALL        VoiceSessionKind = 1
	VoiceSessionKind_VOICE_SESSION_KIND_GROUP_VOICE VoiceSessionKind = 2
	VoiceSessionKind_VOICE_SESSION_KIND_VOICE_ROOM  VoiceSessionKind = 3
)

// Enum value maps for VoiceSessionKind.
var (
	VoiceSessionKind_name = map[int32]string{
		0: "VOICE_SESSION_KIND_UNSPECIFIED",
		1: "VOICE_SESSION_KIND_CALL",
		2: "VOICE_SESSION_KIND_GROUP_VOICE",
		3: "VOICE_SESSION_KIND_VOICE_ROOM",
	}
	VoiceSessionKind_value = map[string]int32{
		"VOICE_SESSION_KIND_UNSPECIFIED": 0,
		"VOICE_SESSION_KIND_CALL":        1,
		"VOICE_SESSION_KIND_GROUP_VOICE": 2,
		"VOICE_SESSION_KIND_VOICE_ROOM":  3,
	}
)

func (x VoiceSessionKind) Enum() *VoiceSessionKind {
	p := new(VoiceSessionKind)
	*p = x
	return p
}

func (x VoiceSessionKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VoiceSessionKind) Descriptor() protoreflect.EnumDescriptor {
	return file_voice_calls_v1_calls_proto_enumTypes[0].Descriptor()
}

func (VoiceSessionKind) Type() protoreflect.EnumType {
	return &file_voice_calls_v1_calls_proto_enumTypes[0]
}

func (x VoiceSessionKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VoiceSessionKind.Descriptor instead.
func (VoiceSessionKind) EnumDescriptor() ([]byte, []int) {
	return file_voice_calls_v1_calls_proto_rawDescGZIP(), []int{0}
}

type CallMediaKind int32

const (
	CallMediaKind_CALL_MEDIA_KIND_UNSPECIFIED CallMediaKind = 0
	CallMediaKind_CALL_MEDIA_KIND_AUDIO       CallMediaKind = 1
	CallMediaKind_CALL_MEDIA_KIND_VIDEO       CallMediaKind = 2
)

// Enum value maps for CallMediaKind.
var (
	CallMediaKind_name = map[int32]string{
		0: "CALL_MEDIA_KIND_UNSPECIFIED",
		1: "CALL_MEDIA_KIND_AUDIO",
		2: "CALL_MEDIA_KIND_VIDEO",
	}
	CallMediaKind_value = map[string]int32{
		"CALL_MEDIA_KIND_UNSPECIFIED": 0,
		"CALL_MEDIA_KIND_AUDIO":       1,
		"CALL_MEDIA_KIND_VIDEO":       2,
	}
)

func (x CallMediaKind) Enum() *CallMediaKind {
	p := new(CallMediaKind)
	*p = x
	return p
}

func (x CallMediaKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CallMediaKind) Descriptor() protoreflect.EnumDescriptor {
	return file_voice_calls_v1_calls_proto_enumTypes[1].Descriptor()
}

func (CallMediaKind) Type() protoreflect.EnumType {
	return &file_voice_calls_v1_calls_proto_enumTypes[1]
}

func (x CallMediaKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CallMediaKind.Descriptor instead.
func (CallMediaKind) EnumDescriptor() ([]byte, []int) {
	return file_voice_calls_v1_calls_proto_rawDescGZIP(), []int{1}
}

type CallStatus int32

const (
	CallStatus_CALL_STATUS_UNSPECIFIED CallStatus = 0
	CallStatus_CALL_STATUS_RINGING     CallStatus = 1
	CallStatus_CALL_STATUS_ACTIVE      CallStatus = 2
	CallStatus_CALL_STATUS_DECLINED    CallStatus = 3
	CallStatus_CALL_STATUS_MISSED      CallStatus = 4
	CallStatus_CALL_STATUS_ENDED       CallStatus = 5
)

// Enum value maps for CallStatus.
var (
	CallStatus_name = map[int32]string{
		0: "CALL_STATUS_UNSPECIFIED",
		1: "CALL_STATUS_RINGING",
		2: "CALL_STATUS_ACTIVE",
		3: "CALL_STATUS_DECLINED",
		4: "CALL_STATUS_MISSED",
		5: "CALL_STATUS_ENDED",
	}
	CallStatus_value = map[string]int32{
		"CALL_STATUS_UNSPECIFIED": 0,
		"CALL_STATUS_RINGING":     1,
		"CALL_STATUS_ACTIVE":      2,
		"CALL_STATUS_DECLINED":    3,
		"CALL_STATUS_MISSED":      4,
		"CALL_STATUS_ENDED":       5,
	}
)

func (x CallStatus) Enum() *CallStatus {
	p := new(CallStatus)
	*p = x
	return p
}

func (x CallStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CallStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_voice_calls_v1_calls_proto_enumTypes[2].Descriptor()
}

func (CallStatus) Type() protoreflect.EnumType {
	return &file_voice_calls_v1_calls_proto_enumTypes[2]
}

func (x CallStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CallStatus.Descriptor instead.
func (CallStatus) EnumDescriptor() ([]byte, []int) {
	return file_voice_calls_v1_calls_proto_rawDescGZIP(), []int{2}
}

type StartCallRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RoomType        string                 `protobuf:"bytes,1,opt,name=room_type,json=roomType,proto3" json:"room_type,omitempty"` // call | group_voice | voice_room; prefer room_type_enum when set
	LinkedChat      *v1.ChatRef            `protobuf:"bytes,2,opt,name=linked_chat,json=linkedChat,proto3,oneof" json:"linked_chat,omitempty"`
	VoiceRoomId     *string                `protobuf:"bytes,3,opt,name=voice_room_id,json=voiceRoomId,proto3,oneof" json:"voice_room_id,omitempty"`
	Space           *v11.SpaceRef          `protobuf:"bytes,4,opt,name=space,proto3,oneof" json:"space,omitempty"`
	RoomTypeEnum    *VoiceSessionKind      `protobuf:"varint,5,opt,name=room_type_enum,json=roomTypeEnum,proto3,enum=voice.calls.v1.VoiceSessionKind,oneof" json:"room_type_enum,omitempty"`
	CalleeProfileId *string                `protobuf:"bytes,6,opt,name=callee_profile_id,json=calleeProfileId,proto3,oneof" json:"callee_profile_id,omitempty"`
	MediaKind       *CallMediaKind         `protobuf:"varint,7,opt,name=media_kind,json=mediaKind,proto3,enum=voice.calls.v1.CallMediaKind,oneof" json:"media_kind,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *StartCallRequest) Reset() {
	*x = StartCallRequest{}
	mi := &file_voice_calls_v1_calls_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartCallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartCallRequest) ProtoMessage() {}

func (x *StartCallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_voice_calls_v1_calls_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartCallRequest.ProtoReflect.Descriptor instead.
func (*StartCallRequest) Descriptor() ([]byte, []int) {
	return file_voice_calls_v1_calls_proto_rawDescGZIP(), []int{0}
}

func (x *StartCallRequest) GetRoomType() string {
	if x != nil {
		return x.RoomType
	}
	return ""
}

func (x *StartCallRequest) GetLinkedChat() *v1.ChatRef {
	if x != nil {
		return x.LinkedChat
	}
	return nil
}

func (x *StartCallRequest) GetVoiceRoomId() string {
	if x != nil && x.VoiceRoomId != nil {
		return *x.VoiceRoomId
	}
	return ""
}

func (x *StartCallRequest) GetSpace() *v11.SpaceRef {
	if x != nil {
		return x.Space
	}
	return nil
}

func (x *StartCallRequest) GetRoomTypeEnum() VoiceSessionKind {
	if x != nil && x.RoomTypeEnum != nil {
		return *x.RoomTypeEnum
	}
	return VoiceSessionKind_VOICE_SESSION_KIND_UNSPECIFIED
}

func (x *StartCallRequest) GetCalleeProfileId() string {
	if x != nil && x.CalleeProfileId != nil {
		return *x.CalleeProfileId
	}
	return ""
}

func (x *StartCallRequest) GetMediaKind() CallMediaKind {
	if x != nil && x.MediaKind != nil {
		return *x.MediaKind
	}
	return CallMediaKind_CALL_MEDIA_KIND_UNSPECIFIED
}

type AcceptCallRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptCallRequest) Reset() {
	*x = AcceptCallRequest{}
	mi := &file_voice_calls_v1_calls_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptCallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptCallRequest) ProtoMessage() {}

func (x *AcceptCallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_voice_calls_v1_calls_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptCallRequest.ProtoReflect.Descriptor instead.
func (*AcceptCallRequest) Descriptor() ([]byte, []int) {
	return file_voice_calls_v1_calls_proto_rawDescGZIP(), []int{1}
}

func (x *AcceptCallRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

type DeclineCallRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeclineCallRequest) Reset() {
	*x = DeclineCallRequest{}
	mi := &file_voice_calls_v1_calls_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeclineCallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeclineCallRequest) ProtoMessage() {}

func (x *DeclineCallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_voice_calls_v1_calls_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeclineCallRequest.ProtoReflect.Descriptor instead.
func (*DeclineCallRequest) Descriptor() ([]byte, []int) {
	return file_voice_calls_v1_calls_proto_rawDescGZIP(), []int{2}
}

func (x *DeclineCallRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

type JoinCallRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinCallRequest) Reset() {
	*x = JoinCallRequest{}
	mi := &file_voice_calls_v1_calls_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinCallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinCallRequest) ProtoMessage() {}

func (x *JoinCallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_voice_calls_v1_calls_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinCallRequest.ProtoReflect.Descriptor instead.
func (*JoinCallRequest) Descriptor() ([]byte, []int) {
	return file_voice_calls_v1_calls_proto_rawDescGZIP(), []int{3}
}

func (x *JoinCallRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

type LeaveCallRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveCallRequest) Reset() {
	*x = LeaveCallRequest{}
	mi := &file_voice_calls_v1_calls_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveCallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveCallRequest) ProtoMessage() {}

func (x *LeaveCallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_voice_calls_v1_calls_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveCallRequest.ProtoReflect.Descriptor instead.
func (*LeaveCallRequest) Descriptor() ([]byte, []int) {
	return file_voice_calls_v1_calls_proto_rawDescGZIP(), []int{4}
}

func (x *LeaveCallRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

type EndCallRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndCallRequest) Reset() {
	*x = EndCallRequest{}
	mi := &file_voice_calls_v1_calls_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndCallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndCallRequest) ProtoMessage() {}

func (x *EndCallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_voice_calls_v1_calls_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndCallRequest.ProtoReflect.Descriptor instead.
func (*EndCallRequest) Descriptor() ([]byte, []int) {
	return file_voice_calls_v1_calls_proto_rawDescGZIP(), []int{5}
}

func (x *EndCallRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

type CallSession struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	RoomId             string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	LivekitRoomName    string                 `protobuf:"bytes,2,opt,name=livekit_room_name,json=livekitRoomName,proto3" json:"livekit_room_name,omitempty"`
	RoomType           string                 `protobuf:"bytes,3,opt,name=room_type,json=roomType,proto3" json:"room_type,omitempty"` // prefer room_type_enum when set
	LinkedChat         *v1.ChatRef            `protobuf:"bytes,4,opt,name=linked_chat,json=linkedChat,proto3,oneof" json:"linked_chat,omitempty"`
	VoiceRoomId        *string                `protobuf:"bytes,5,opt,name=voice_room_id,json=voiceRoomId,proto3,oneof" json:"voice_room_id,omitempty"`
	StartedAt          *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	RoomTypeEnum       *VoiceSessionKind      `protobuf:"varint,7,opt,name=room_type_enum,json=roomTypeEnum,proto3,enum=voice.calls.v1.VoiceSessionKind,oneof" json:"room_type_enum,omitempty"`
	InitiatorProfileId string                 `protobuf:"bytes,8,opt,name=initiator_profile_id,json=initiatorProfileId,proto3" json:"initiator_profile_id,omitempty"`
	CalleeProfileId    string                 `protobuf:"bytes,9,opt,name=callee_profile_id,json=calleeProfileId,proto3" json:"callee_profile_id,omitempty"`
	MediaKind          CallMediaKind          `protobuf:"varint,10,opt,name=media_kind,json=mediaKind,proto3,enum=voice.calls.v1.CallMediaKind" json:"media_kind,omitempty"`
	Status             CallStatus             `protobuf:"varint,11,opt,name=status,proto3,enum=voice.calls.v1.CallStatus" json:"status,omitempty"`
	ExpiresAt          *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	EndedAt            *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=ended_at,json=endedAt,proto3" json:"ended_at,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CallSession) Reset() {
	*x = CallSession{}
	mi := &file_voice_calls_v1_calls_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallSession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallSession) ProtoMessage() {}

func (x *CallSession) ProtoReflect() protoreflect.Message {
	mi := &file_voice_calls_v1_calls_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallSession.ProtoReflect.Descriptor instead.
func (*CallSession) Descriptor() ([]byte, []int) {
	return file_voice_calls_v1_calls_proto_rawDescGZIP(), []int{6}
}

func (x *CallSession) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *CallSession) GetLivekitRoomName() string {
	if x != nil {
		return x.LivekitRoomName
	}
	return ""
}

func (x *CallSession) GetRoomType() string {
	if x != nil {
		return x.RoomType
	}
	return ""
}

func (x *CallSession) GetLinkedChat() *v1.ChatRef {
	if x != nil {
		return x.LinkedChat
	}
	return nil
}

func (x *CallSession) GetVoiceRoomId() string {
	if x != nil && x.VoiceRoomId != nil {
		return *x.VoiceRoomId
	}
	return ""
}

func (x *CallSession) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *CallSession) GetRoomTypeEnum() VoiceSessionKind {
	if x != nil && x.RoomTypeEnum != nil {
		return *x.RoomTypeEnum
	}
	return VoiceSessionKind_VOICE_SESSION_KIND_UNSPECIFIED
}

func (x *CallSession) GetInitiatorProfileId() string {
	if x != nil {
		return x.InitiatorProfileId
	}
	return ""
}

func (x *CallSession) GetCalleeProfileId() string {
	if x != nil {
		return x.CalleeProfileId
	}
	return ""
}

func (x *CallSession) GetMediaKind() CallMediaKind {
	if x != nil {
		return x.MediaKind
	}
	return CallMediaKind_CALL_MEDIA_KIND_UNSPECIFIED
}

func (x *CallSession) GetStatus() CallStatus {
	if x != nil {
		return x.Status
	}
	return CallStatus_CALL_STATUS_UNSPECIFIED
}

func (x *CallSession) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *CallSession) GetEndedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EndedAt
	}
	return nil
}

type JoinVoiceRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VoiceRoomId   string                 `protobuf:"bytes,1,opt,name=voice_room_id,json=voiceRoomId,proto3" json:"voice_room_id,omitempty"`
	Space         *v11.SpaceRef          `protobuf:"bytes,2,opt,name=space,proto3" json:"space,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinVoiceRoomRequest) Reset() {
	*x = JoinVoiceRoomRequest{}
	mi := &file_voice_calls_v1_calls_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinVoiceRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinVoiceRoomRequest) ProtoMessage() {}

func (x *JoinVoiceRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_voice_calls_v1_calls_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinVoiceRoomRequest.ProtoReflect.Descriptor instead.
func (*JoinVoiceRoomRequest) Descriptor() ([]byte, []int) {
	return file_voice_calls_v1_calls_proto_rawDescGZIP(), []int{7}
}

func (x *JoinVoiceRoomRequest) GetVoiceRoomId() string {
	if x != nil {
		return x.VoiceRoomId
	}
	return ""
}

func (x *JoinVoiceRoomRequest) GetSpace() *v11.SpaceRef {
	if x != nil {
		return x.Space
	}
	return nil
}

type LeaveVoiceRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VoiceRoomId   string                 `protobuf:"bytes,1,opt,name=voice_room_id,json=voiceRoomId,proto3" json:"voice_room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveVoiceRoomRequest) Reset() {
	*x = LeaveVoiceRoomRequest{}
	mi := &file_voice_calls_v1_calls_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveVoiceRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveVoiceRoomRequest) ProtoMessage() {}

func (x *LeaveVoiceRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_voice_calls_v1_calls_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveVoiceRoomRequest.ProtoReflect.Descriptor instead.
func (*LeaveVoiceRoomRequest) Descriptor() ([]byte, []int) {
	return file_voice_calls_v1_calls_proto_rawDescGZIP(), []int{8}
}

func (x *LeaveVoiceRoomRequest) GetVoiceRoomId() string {
	if x != nil {
		return x.VoiceRoomId
	}
	return ""
}

type MoveToVoiceRoomRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	FromVoiceRoomId string                 `protobuf:"bytes,1,opt,name=from_voice_room_id,json=fromVoiceRoomId,proto3" json:"from_voice_room_id,omitempty"`
	ToVoiceRoomId   string                 `protobuf:"bytes,2,opt,name=to_voice_room_id,json=toVoiceRoomId,proto3" json:"to_voice_room_id,omitempty"`
	Space           *v11.SpaceRef          `protobuf:"bytes,3,opt,name=space,proto3" json:"space,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MoveToVoiceRoomRequest) Reset() {
	*x = MoveToVoiceRoomRequest{}
	mi := &file_voice_calls_v1_calls_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveToVoiceRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveToVoiceRoomRequest) ProtoMessage() {}

func (x *MoveToVoiceRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_voice_calls_v1_calls_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveToVoiceRoomRequest.ProtoReflect.Descriptor instead.
func (*MoveToVoiceRoomRequest) Descriptor() ([]byte, []int) {
	return file_voice_calls_v1_calls_proto_rawDescGZIP(), []int{9}
}

func (x *MoveToVoiceRoomRequest) GetFromVoiceRoomId() string {
	if x != nil {
		return x.FromVoiceRoomId
	}
	return ""
}

func (x *MoveToVoiceRoomRequest) GetToVoiceRoomId() string {
	if x != nil {
		return x.ToVoiceRoomId
	}
	return ""
}

func (x *MoveToVoiceRoomRequest) GetSpace() *v11.SpaceRef {
	if x != nil {
		return x.Space
	}
	return nil
}

type VoiceSession struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RoomId          string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	LivekitRoomName string                 `protobuf:"bytes,2,opt,name=livekit_room_name,json=livekitRoomName,proto3" json:"livekit_room_name,omitempty"`
	VoiceRoomId     string                 `protobuf:"bytes,3,opt,name=voice_room_id,json=voiceRoomId,proto3" json:"voice_room_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *VoiceSession) Reset() {
	*x = VoiceSession{}
	mi := &file_voice_calls_v1_calls_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VoiceSession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoiceSession) ProtoMessage() {}

func (x *VoiceSession) ProtoReflect() protoreflect.Message {
	mi := &file_voice_calls_v1_calls_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoiceSession.ProtoReflect.Descriptor instead.
func (*VoiceSession) Descriptor() ([]byte, []int) {
	return file_voice_calls_v1_calls_proto_rawDescGZIP(), []int{10}
}

func (x *VoiceSession) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *VoiceSession) GetLivekitRoomName() string {
	if x != nil {
		return x.LivekitRoomName
	}
	return ""
}

func (x *VoiceSession) GetVoiceRoomId() string {
	if x != nil {
		return x.VoiceRoomId
	}
	return ""
}

type GetJoinTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJoinTokenRequest) Reset() {
	*x = GetJoinTokenRequest{}
	mi := &file_voice_calls_v1_calls_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJoinTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJoinTokenRequest) ProtoMessage() {}

func (x *GetJoinTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_voice_calls_v1_calls_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJoinTokenRequest.ProtoReflect.Descriptor instead.
func (*GetJoinTokenRequest) Descriptor() ([]byte, []int) {
	return file_voice_calls_v1_calls_proto_rawDescGZIP(), []int{11}
}

func (x *GetJoinTokenRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

type UpdateVoiceStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	IsMuted       *bool                  `protobuf:"varint,2,opt,name=is_muted,json=isMuted,proto3,oneof" json:"is_muted,omitempty"`
	IsDeafened    *bool                  `protobuf:"varint,3,opt,name=is_deafened,json=isDeafened,proto3,oneof" json:"is_deafened,omitempty"`
	IsVideoOn     *bool                  `protobuf:"varint,4,opt,name=is_video_on,json=isVideoOn,proto3,oneof" json:"is_video_on,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateVoiceStateRequest) Reset() {
	*x = UpdateVoiceStateRequest{}
	mi := &file_voice_calls_v1_calls_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateVoiceStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateVoiceStateRequest) ProtoMessage() {}

func (x *UpdateVoiceStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_voice_calls_v1_calls_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateVoiceStateRequest.ProtoReflect.Descriptor instead.
func (*UpdateVoiceStateRequest) Descriptor() ([]byte, []int) {
	return file_voice_calls_v1_calls_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateVoiceStateRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *UpdateVoiceStateRequest) GetIsMuted() bool {
	if x != nil && x.IsMuted != nil {
		return *x.IsMuted
	}
	return false
}

func (x *UpdateVoiceStateRequest) GetIsDeafened() bool {
	if x != nil && x.IsDeafened != nil {
		return *x.IsDeafened
	}
	return false
}

func (x *UpdateVoiceStateRequest) GetIsVideoOn() bool {
	if x != nil && x.IsVideoOn != nil {
		return *x.IsVideoOn
	}
	return false
}

type GetVoiceStatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVoiceStatesRequest) Reset() {
	*x = GetVoiceStatesRequest{}
	mi := &file_voice_calls_v1_calls_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVoiceStatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVoiceStatesRequest) ProtoMessage() {}

func (x *GetVoiceStatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_voice_calls_v1_calls_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVoiceStatesRequest.ProtoReflect.Descriptor instead.
func (*GetVoiceStatesRequest) Descriptor() ([]byte, []int) {
	return file_voice_calls_v1_calls_proto_rawDescGZIP(), []int{13}
}

func (x *GetVoiceStatesRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

type VoiceParticipantState struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProfileId       string                 `protobuf:"bytes,1,opt,name=profile_id,json=profileId,proto3" json:"profile_id,omitempty"`
	IsMuted         bool                   `protobuf:"varint,2,opt,name=is_muted,json=isMuted,proto3" json:"is_muted,omitempty"`
	IsDeafened      bool                   `protobuf:"varint,3,opt,name=is_deafened,json=isDeafened,proto3" json:"is_deafened,omitempty"`
	IsVideoOn       bool                   `protobuf:"varint,4,opt,name=is_video_on,json=isVideoOn,proto3" json:"is_video_on,omitempty"`
	IsScreenSharing bool                   `protobuf:"varint,5,opt,name=is_screen_sharing,json=isScreenSharing,proto3" json:"is_screen_sharing,omitempty"`
	IsCommander     bool                   `protobuf:"varint,6,opt,name=is_commander,json=isCommander,proto3" json:"is_commander,omitempty"`
	HandRaised      bool                   `protobuf:"varint,7,opt,name=hand_raised,json=handRaised,proto3" json:"hand_raised,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *VoiceParticipantState) Reset() {
	*x = VoiceParticipantState{}
	mi := &file_voice_calls_v1_calls_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VoiceParticipantState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoiceParticipantState) ProtoMessage() {}

func (x *VoiceParticipantState) ProtoReflect() protoreflect.Message {
	mi := &file_voice_calls_v1_calls_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoiceParticipantState.ProtoReflect.Descriptor instead.
func (*VoiceParticipantState) Descriptor() ([]byte, []int) {
	return file_voice_calls_v1_calls_proto_rawDescGZIP(), []int{14}
}

func (x *VoiceParticipantState) GetProfileId() string {
	if x != nil {
		return x.ProfileId
	}
	return ""
}

func (x *VoiceParticipantState) GetIsMuted() bool {
	if x != nil {
		return x.IsMuted
	}
	return false
}

func (x *VoiceParticipantState) GetIsDeafened() bool {
	if x != nil {
		return x.IsDeafened
	}
	return false
}

func (x *VoiceParticipantState) GetIsVideoOn() bool {
	if x != nil {
		return x.IsVideoOn
	}
	return false
}

func (x *VoiceParticipantState) GetIsScreenSharing() bool {
	if x != nil {
		return x.IsScreenSharing
	}
	return false
}

func (x *VoiceParticipantState) GetIsCommander() bool {
	if x != nil {
		return x.IsCommander
	}
	return false
}

func (x *VoiceParticipantState) GetHandRaised() bool {
	if x != nil {
		return x.HandRaised
	}
	return false
}

type GetActiveCallRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetActiveCallRequest) Reset() {
	*x = GetActiveCallRequest{}
	mi := &file_voice_calls_v1_calls_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActiveCallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActiveCallRequest) ProtoMessage() {}

func (x *GetActiveCallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_voice_calls_v1_calls_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActiveCallRequest.ProtoReflect.Descriptor instead.
func (*GetActiveCallRequest) Descriptor() ([]byte, []int) {
	return file_voice_calls_v1_calls_proto_rawDescGZIP(), []int{15}
}

type StartScreenShareRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartScreenShareRequest) Reset() {
	*x = StartScreenShareRequest{}
	mi := &file_voice_calls_v1_calls_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartScreenShareRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartScreenShareRequest) ProtoMessage() {}

func (x *StartScreenShareRequest) ProtoReflect() protoreflect.Message {
	mi := &file_voice_calls_v1_calls_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartScreenShareRequest.ProtoReflect.Descriptor instead.
func (*StartScreenShareRequest) Descriptor() ([]byte, []int) {
	return file_voice_calls_v1_calls_proto_rawDescGZIP(), []int{16}
}

func (x *StartScreenShareRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

type ScreenShareSession struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreamId      string                 `protobuf:"bytes,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScreenShareSession) Reset() {
	*x = ScreenShareSession{}
	mi := &file_voice_calls_v1_calls_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScreenShareSession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScreenShareSession) ProtoMessage() {}

func (x *ScreenShareSession) ProtoReflect() protoreflect.Message {
	mi := &file_voice_calls_v1_calls_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScreenShareSession.ProtoReflect.Descriptor instead.
func (*ScreenShareSession) Descriptor() ([]byte, []int) {
	return file_voice_calls_v1_calls_proto_rawDescGZIP(), []int{17}
}

func (x *ScreenShareSession) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

type StopScreenShareRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	StreamId      *string                `protobuf:"bytes,2,opt,name=stream_id,json=streamId,proto3,oneof" json:"stream_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopScreenShareRequest) Reset() {
	*x = StopScreenShareRequest{}
	mi := &file_voice_calls_v1_calls_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopScreenShareRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopScreenShareRequest) ProtoMessage() {}

func (x *StopScreenShareRequest) ProtoReflect() protoreflect.Message {
	mi := &file_voice_calls_v1_calls_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopScreenShareRequest.ProtoReflect.Descriptor instead.
func (*StopScreenShareRequest) Descriptor() ([]byte, []int) {
	return file_voice_calls_v1_calls_proto_rawDescGZIP(), []int{18}
}

func (x *StopScreenShareRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *StopScreenShareRequest) GetStreamId() string {
	if x != nil && x.StreamId != nil {
		return *x.StreamId
	}
	return ""
}

type SetCommanderModeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Enabled       bool                   `protobuf:"varint,2,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetCommanderModeRequest) Reset() {
	*x = SetCommanderModeRequest{}
	mi := &file_voice_calls_v1_calls_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetCommanderModeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetCommanderModeRequest) ProtoMessage() {}

func (x *SetCommanderModeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_voice_calls_v1_calls_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetCommanderModeRequest.ProtoReflect.Descriptor instead.
func (*SetCommanderModeRequest) Descriptor() ([]byte, []int) {
	return file_voice_calls_v1_calls_proto_rawDescGZIP(), []int{19}
}

func (x *SetCommanderModeRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *SetCommanderModeRequest) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

type RaiseHandRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RaiseHandRequest) Reset() {
	*x = RaiseHandRequest{}
	mi := &file_voice_calls_v1_calls_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RaiseHandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaiseHandRequest) ProtoMessage() {}

func (x *RaiseHandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_voice_calls_v1_calls_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaiseHandRequest.ProtoReflect.Descriptor instead.
func (*RaiseHandRequest) Descriptor() ([]byte, []int) {
	return file_voice_calls_v1_calls_proto_rawDescGZIP(), []int{20}
}

func (x *RaiseHandRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

type LowerHandRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LowerHandRequest) Reset() {
	*x = LowerHandRequest{}
	mi := &file_voice_calls_v1_calls_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LowerHandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LowerHandRequest) ProtoMessage() {}

func (x *LowerHandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_voice_calls_v1_calls_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LowerHandRequest.ProtoReflect.Descriptor instead.
func (*LowerHandRequest) Descriptor() ([]byte, []int) {
	return file_voice_calls_v1_calls_proto_rawDescGZIP(), []int{21}
}

func (x *LowerHandRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

type StartCallResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CallSession   *CallSession           `protobuf:"bytes,1,opt,name=call_session,json=callSession,proto3" json:"call_session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartCallResponse) Reset() {
	*x = StartCallResponse{}
	mi := &file_voice_calls_v1_calls_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartCallResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartCallResponse) ProtoMessage() {}

func (x *StartCallResponse) ProtoReflect() protoreflect.Message {
	mi := &file_voice_calls_v1_calls_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartCallResponse.ProtoReflect.Descriptor instead.
func (*StartCallResponse) Descriptor() ([]byte, []int) {
	return file_voice_calls_v1_calls_proto_rawDescGZIP(), []int{22}
}

func (x *StartCallResponse) GetCallSession() *CallSession {
	if x != nil {
		return x.CallSession
	}
	return nil
}

type AcceptCallResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CallSession   *CallSession           `protobuf:"bytes,1,opt,name=call_session,json=callSession,proto3" json:"call_session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptCallResponse) Reset() {
	*x = AcceptCallResponse{}
	mi := &file_voice_calls_v1_calls_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptCallResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptCallResponse) ProtoMessage() {}

func (x *AcceptCallResponse) ProtoReflect() protoreflect.Message {
	mi := &file_voice_calls_v1_calls_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptCallResponse.ProtoReflect.Descriptor instead.
func (*AcceptCallResponse) Descriptor() ([]byte, []int) {
	return file_voice_calls_v1_calls_proto_rawDescGZIP(), []int{23}
}

func (x *AcceptCallResponse) GetCallSession() *CallSession {
	if x != nil {
		return x.CallSession
	}
	return nil
}

type DeclineCallResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CallSession   *CallSession           `protobuf:"bytes,1,opt,name=call_session,json=callSession,proto3" json:"call_session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeclineCallResponse) Reset() {
	*x = DeclineCallResponse{}
	mi := &file_voice_calls_v1_calls_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeclineCallResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeclineCallResponse) ProtoMessage() {}

func (x *DeclineCallResponse) ProtoReflect() protoreflect.Message {
	mi := &file_voice_calls_v1_calls_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeclineCallResponse.ProtoReflect.Descriptor instead.
func (*DeclineCallResponse) Descriptor() ([]byte, []int) {
	return file_voice_calls_v1_calls_proto_rawDescGZIP(), []int{24}
}

func (x *DeclineCallResponse) GetCallSession() *CallSession {
	if x != nil {
		return x.CallSession
	}
	return nil
}

type JoinCallResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CallSession   *CallSession           `protobuf:"bytes,1,opt,name=call_session,json=callSession,proto3" json:"call_session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinCallResponse) Reset() {
	*x = JoinCallResponse{}
	mi := &file_voice_calls_v1_calls_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinCallResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinCallResponse) ProtoMessage() {}

func (x *JoinCallResponse) ProtoReflect() protoreflect.Message {
	mi := &file_voice_calls_v1_calls_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinCallResponse.ProtoReflect.Descriptor instead.
func (*JoinCallResponse) Descriptor() ([]byte, []int) {
	return file_voice_calls_v1_calls_proto_rawDescGZIP(), []int{25}
}

func (x *JoinCallResponse) GetCallSession() *CallSession {
	if x != nil {
		return x.CallSession
	}
	return nil
}

type LeaveCallResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveCallResponse) Reset() {
	*x = LeaveCallResponse{}
	mi := &file_voice_calls_v1_calls_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveCallResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveCallResponse) ProtoMessage() {}

func (x *LeaveCallResponse) ProtoReflect() protoreflect.Message {
	mi := &file_voice_calls_v1_calls_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveCallResponse.ProtoReflect.Descriptor instead.
func (*LeaveCallResponse) Descriptor() ([]byte, []int) {
	return file_voice_calls_v1_calls_proto_rawDescGZIP(), []int{26}
}

type EndCallResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndCallResponse) Reset() {
	*x = EndCallResponse{}
	mi := &file_voice_calls_v1_calls_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndCallResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndCallResponse) ProtoMessage() {}

func (x *EndCallResponse) ProtoReflect() protoreflect.Message {
	mi := &file_voice_calls_v1_calls_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndCallResponse.ProtoReflect.Descriptor instead.
func (*EndCallResponse) Descriptor() ([]byte, []int) {
	return file_voice_calls_v1_calls_proto_rawDescGZIP(), []int{27}
}

type JoinVoiceRoomResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VoiceSession  *VoiceSession          `protobuf:"bytes,1,opt,name=voice_session,json=voiceSession,proto3" json:"voice_session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinVoiceRoomResponse) Reset() {
	*x = JoinVoiceRoomResponse{}
	mi := &file_voice_calls_v1_calls_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinVoiceRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinVoiceRoomResponse) ProtoMessage() {}

func (x *JoinVoiceRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_voice_calls_v1_calls_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinVoiceRoomResponse.ProtoReflect.Descriptor instead.
func (*JoinVoiceRoomResponse) Descriptor() ([]byte, []int) {
	return file_voice_calls_v1_calls_proto_rawDescGZIP(), []int{28}
}

func (x *JoinVoiceRoomResponse) GetVoiceSession() *VoiceSession {
	if x != nil {
		return x.VoiceSession
	}
	return nil
}

type LeaveVoiceRoomResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveVoiceRoomResponse) Reset() {
	*x = LeaveVoiceRoomResponse{}
	mi := &file_voice_calls_v1_calls_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveVoiceRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveVoiceRoomResponse) ProtoMessage() {}

func (x *LeaveVoiceRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_voice_calls_v1_calls_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveVoiceRoomResponse.ProtoReflect.Descriptor instead.
func (*LeaveVoiceRoomResponse) Descriptor() ([]byte, []int) {
	return file_voice_calls_v1_calls_proto_rawDescGZIP(), []int{29}
}

type MoveToVoiceRoomResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VoiceSession  *VoiceSession          `protobuf:"bytes,1,opt,name=voice_session,json=voiceSession,proto3" json:"voice_session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveToVoiceRoomResponse) Reset() {
	*x = MoveToVoiceRoomResponse{}
	mi := &file_voice_calls_v1_calls_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveToVoiceRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveToVoiceRoomResponse) ProtoMessage() {}

func (x *MoveToVoiceRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_voice_calls_v1_calls_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveToVoiceRoomResponse.ProtoReflect.Descriptor instead.
func (*MoveToVoiceRoomResponse) Descriptor() ([]byte, []int) {
	return file_voice_calls_v1_calls_proto_rawDescGZIP(), []int{30}
}

func (x *MoveToVoiceRoomResponse) GetVoiceSession() *VoiceSession {
	if x != nil {
		return x.VoiceSession
	}
	return nil
}

// JWT and wall-clock expiry (UTC). Public API uses google.protobuf.Timestamp per docs/REPOSITORIES.md.
type GetJoinTokenResponse struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Jwt       string                 `protobuf:"bytes,1,opt,name=jwt,proto3" json:"jwt,omitempty"`
	ExpiresAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	// WebSocket URL for LiveKit SDK connect (public ingress; not the internal service URL).
	LivekitUrl    string `protobuf:"bytes,3,opt,name=livekit_url,json=livekitUrl,proto3" json:"livekit_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJoinTokenResponse) Reset() {
	*x = GetJoinTokenResponse{}
	mi := &file_voice_calls_v1_calls_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJoinTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJoinTokenResponse) ProtoMessage() {}

func (x *GetJoinTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_voice_calls_v1_calls_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJoinTokenResponse.ProtoReflect.Descriptor instead.
func (*GetJoinTokenResponse) Descriptor() ([]byte, []int) {
	return file_voice_calls_v1_calls_proto_rawDescGZIP(), []int{31}
}

func (x *GetJoinTokenResponse) GetJwt() string {
	if x != nil {
		return x.Jwt
	}
	return ""
}

func (x *GetJoinTokenResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *GetJoinTokenResponse) GetLivekitUrl() string {
	if x != nil {
		return x.LivekitUrl
	}
	return ""
}

type UpdateVoiceStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateVoiceStateResponse) Reset() {
	*x = UpdateVoiceStateResponse{}
	mi := &file_voice_calls_v1_calls_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateVoiceStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateVoiceStateResponse) ProtoMessage() {}

func (x *UpdateVoiceStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_voice_calls_v1_calls_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateVoiceStateResponse.ProtoReflect.Descriptor instead.
func (*UpdateVoiceStateResponse) Descriptor() ([]byte, []int) {
	return file_voice_calls_v1_calls_proto_rawDescGZIP(), []int{32}
}

type GetVoiceStatesResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Participants  []*VoiceParticipantState `protobuf:"bytes,1,rep,name=participants,proto3" json:"participants,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVoiceStatesResponse) Reset() {
	*x = GetVoiceStatesResponse{}
	mi := &file_voice_calls_v1_calls_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVoiceStatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVoiceStatesResponse) ProtoMessage() {}

func (x *GetVoiceStatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_voice_calls_v1_calls_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVoiceStatesResponse.ProtoReflect.Descriptor instead.
func (*GetVoiceStatesResponse) Descriptor() ([]byte, []int) {
	return file_voice_calls_v1_calls_proto_rawDescGZIP(), []int{33}
}

func (x *GetVoiceStatesResponse) GetParticipants() []*VoiceParticipantState {
	if x != nil {
		return x.Participants
	}
	return nil
}

type GetActiveCallResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CallSession   *CallSession           `protobuf:"bytes,1,opt,name=call_session,json=callSession,proto3" json:"call_session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetActiveCallResponse) Reset() {
	*x = GetActiveCallResponse{}
	mi := &file_voice_calls_v1_calls_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActiveCallResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActiveCallResponse) ProtoMessage() {}

func (x *GetActiveCallResponse) ProtoReflect() protoreflect.Message {
	mi := &file_voice_calls_v1_calls_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActiveCallResponse.ProtoReflect.Descriptor instead.
func (*GetActiveCallResponse) Descriptor() ([]byte, []int) {
	return file_voice_calls_v1_calls_proto_rawDescGZIP(), []int{34}
}

func (x *GetActiveCallResponse) GetCallSession() *CallSession {
	if x != nil {
		return x.CallSession
	}
	return nil
}

type StartScreenShareResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ScreenShareSession *ScreenShareSession    `protobuf:"bytes,1,opt,name=screen_share_session,json=screenShareSession,proto3" json:"screen_share_session,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *StartScreenShareResponse) Reset() {
	*x = StartScreenShareResponse{}
	mi := &file_voice_calls_v1_calls_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartScreenShareResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartScreenShareResponse) ProtoMessage() {}

func (x *StartScreenShareResponse) ProtoReflect() protoreflect.Message {
	mi := &file_voice_calls_v1_calls_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartScreenShareResponse.ProtoReflect.Descriptor instead.
func (*StartScreenShareResponse) Descriptor() ([]byte, []int) {
	return file_voice_calls_v1_calls_proto_rawDescGZIP(), []int{35}
}

func (x *StartScreenShareResponse) GetScreenShareSession() *ScreenShareSession {
	if x != nil {
		return x.ScreenShareSession
	}
	return nil
}

type StopScreenShareResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopScreenShareResponse) Reset() {
	*x = StopScreenShareResponse{}
	mi := &file_voice_calls_v1_calls_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopScreenShareResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopScreenShareResponse) ProtoMessage() {}

func (x *StopScreenShareResponse) ProtoReflect() protoreflect.Message {
	mi := &file_voice_calls_v1_calls_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopScreenShareResponse.ProtoReflect.Descriptor instead.
func (*StopScreenShareResponse) Descriptor() ([]byte, []int) {
	return file_voice_calls_v1_calls_proto_rawDescGZIP(), []int{36}
}

type SetCommanderModeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetCommanderModeResponse) Reset() {
	*x = SetCommanderModeResponse{}
	mi := &file_voice_calls_v1_calls_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetCommanderModeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetCommanderModeResponse) ProtoMessage() {}

func (x *SetCommanderModeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_voice_calls_v1_calls_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetCommanderModeResponse.ProtoReflect.Descriptor instead.
func (*SetCommanderModeResponse) Descriptor() ([]byte, []int) {
	return file_voice_calls_v1_calls_proto_rawDescGZIP(), []int{37}
}

type RaiseHandResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RaiseHandResponse) Reset() {
	*x = RaiseHandResponse{}
	mi := &file_voice_calls_v1_calls_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RaiseHandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaiseHandResponse) ProtoMessage() {}

func (x *RaiseHandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_voice_calls_v1_calls_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaiseHandResponse.ProtoReflect.Descriptor instead.
func (*RaiseHandResponse) Descriptor() ([]byte, []int) {
	return file_voice_calls_v1_calls_proto_rawDescGZIP(), []int{38}
}

type LowerHandResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LowerHandResponse) Reset() {
	*x = LowerHandResponse{}
	mi := &file_voice_calls_v1_calls_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LowerHandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LowerHandResponse) ProtoMessage() {}

func (x *LowerHandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_voice_calls_v1_calls_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LowerHandResponse.ProtoReflect.Descriptor instead.
func (*LowerHandResponse) Descriptor() ([]byte, []int) {
	return file_voice_calls_v1_calls_proto_rawDescGZIP(), []int{39}
}

var File_voice_calls_v1_calls_proto protoreflect.FileDescriptor

const file_voice_calls_v1_calls_proto_rawDesc = "" +
	"\n" +
	"\x1avoice/calls/v1/calls.proto\x12\x0evoice.calls.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x18voice/chat/v1/chat.proto\x1a\x1avoice/space/v1/space.proto\"\xf0\x03\n" +
	"\x10StartCallRequest\x12\x1b\n" +
	"\troom_type\x18\x01 \x01(\tR\broomType\x12<\n" +
	"\vlinked_chat\x18\x02 \x01(\v2\x16.voice.chat.v1.ChatRefH\x00R\n" +
	"linkedChat\x88\x01\x01\x12'\n" +
	"\rvoice_room_id\x18\x03 \x01(\tH\x01R\vvoiceRoomId\x88\x01\x01\x123\n" +
	"\x05space\x18\x04 \x01(\v2\x18.voice.space.v1.SpaceRefH\x02R\x05space\x88\x01\x01\x12K\n" +
	"\x0eroom_type_enum\x18\x05 \x01(\x0e2 .voice.calls.v1.VoiceSessionKindH\x03R\froomTypeEnum\x88\x01\x01\x12/\n" +
	"\x11callee_profile_id\x18\x06 \x01(\tH\x04R\x0fcalleeProfileId\x88\x01\x01\x12A\n" +
	"\n" +
	"media_kind\x18\a \x01(\x0e2\x1d.voice.calls.v1.CallMediaKindH\x05R\tmediaKind\x88\x01\x01B\x0e\n" +
	"\f_linked_chatB\x10\n" +
	"\x0e_voice_room_idB\b\n" +
	"\x06_spaceB\x11\n" +
	"\x0f_room_type_enumB\x14\n" +
	"\x12_callee_profile_idB\r\n" +
	"\v_media_kind\",\n" +
	"\x11AcceptCallRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\"-\n" +
	"\x12DeclineCallRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\"*\n" +
	"\x0fJoinCallRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\"+\n" +
	"\x10LeaveCallRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\")\n" +
	"\x0eEndCallRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\"\xd5\x05\n" +
	"\vCallSession\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12*\n" +
	"\x11livekit_room_name\x18\x02 \x01(\tR\x0flivekitRoomName\x12\x1b\n" +
	"\troom_type\x18\x03 \x01(\tR\broomType\x12<\n" +
	"\vlinked_chat\x18\x04 \x01(\v2\x16.voice.chat.v1.ChatRefH\x00R\n" +
	"linkedChat\x88\x01\x01\x12'\n" +
	"\rvoice_room_id\x18\x05 \x01(\tH\x01R\vvoiceRoomId\x88\x01\x01\x129\n" +
	"\n" +
	"started_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12K\n" +
	"\x0eroom_type_enum\x18\a \x01(\x0e2 .voice.calls.v1.VoiceSessionKindH\x02R\froomTypeEnum\x88\x01\x01\x120\n" +
	"\x14initiator_profile_id\x18\b \x01(\tR\x12initiatorProfileId\x12*\n" +
	"\x11callee_profile_id\x18\t \x01(\tR\x0fcalleeProfileId\x12<\n" +
	"\n" +
	"media_kind\x18\n" +
	" \x01(\x0e2\x1d.voice.calls.v1.CallMediaKindR\tmediaKind\x122\n" +
	"\x06status\x18\v \x01(\x0e2\x1a.voice.calls.v1.CallStatusR\x06status\x129\n" +
	"\n" +
	"expires_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x125\n" +
	"\bended_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\aendedAtB\x0e\n" +
	"\f_linked_chatB\x10\n" +
	"\x0e_voice_room_idB\x11\n" +
	"\x0f_room_type_enum\"j\n" +
	"\x14JoinVoiceRoomRequest\x12\"\n" +
	"\rvoice_room_id\x18\x01 \x01(\tR\vvoiceRoomId\x12.\n" +
	"\x05space\x18\x02 \x01(\v2\x18.voice.space.v1.SpaceRefR\x05space\";\n" +
	"\x15LeaveVoiceRoomRequest\x12\"\n" +
	"\rvoice_room_id\x18\x01 \x01(\tR\vvoiceRoomId\"\x9e\x01\n" +
	"\x16MoveToVoiceRoomRequest\x12+\n" +
	"\x12from_voice_room_id\x18\x01 \x01(\tR\x0ffromVoiceRoomId\x12'\n" +
	"\x10to_voice_room_id\x18\x02 \x01(\tR\rtoVoiceRoomId\x12.\n" +
	"\x05space\x18\x03 \x01(\v2\x18.voice.space.v1.SpaceRefR\x05space\"w\n" +
	"\fVoiceSession\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12*\n" +
	"\x11livekit_room_name\x18\x02 \x01(\tR\x0flivekitRoomName\x12\"\n" +
	"\rvoice_room_id\x18\x03 \x01(\tR\vvoiceRoomId\".\n" +
	"\x13GetJoinTokenRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\"\xca\x01\n" +
	"\x17UpdateVoiceStateRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x1e\n" +
	"\bis_muted\x18\x02 \x01(\bH\x00R\aisMuted\x88\x01\x01\x12$\n" +
	"\vis_deafened\x18\x03 \x01(\bH\x01R\n" +
	"isDeafened\x88\x01\x01\x12#\n" +
	"\vis_video_on\x18\x04 \x01(\bH\x02R\tisVideoOn\x88\x01\x01B\v\n" +
	"\t_is_mutedB\x0e\n" +
	"\f_is_deafenedB\x0e\n" +
	"\f_is_video_on\"0\n" +
	"\x15GetVoiceStatesRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\"\x82\x02\n" +
	"\x15VoiceParticipantState\x12\x1d\n" +
	"\n" +
	"profile_id\x18\x01 \x01(\tR\tprofileId\x12\x19\n" +
	"\bis_muted\x18\x02 \x01(\bR\aisMuted\x12\x1f\n" +
	"\vis_deafened\x18\x03 \x01(\bR\n" +
	"isDeafened\x12\x1e\n" +
	"\vis_video_on\x18\x04 \x01(\bR\tisVideoOn\x12*\n" +
	"\x11is_screen_sharing\x18\x05 \x01(\bR\x0fisScreenSharing\x12!\n" +
	"\fis_commander\x18\x06 \x01(\bR\visCommander\x12\x1f\n" +
	"\vhand_raised\x18\a \x01(\bR\n" +
	"handRaised\"\x16\n" +
	"\x14GetActiveCallRequest\"2\n" +
	"\x17StartScreenShareRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\"1\n" +
	"\x12ScreenShareSession\x12\x1b\n" +
	"\tstream_id\x18\x01 \x01(\tR\bstreamId\"a\n" +
	"\x16StopScreenShareRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12 \n" +
	"\tstream_id\x18\x02 \x01(\tH\x00R\bstreamId\x88\x01\x01B\f\n" +
	"\n" +
	"_stream_id\"L\n" +
	"\x17SetCommanderModeRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x18\n" +
	"\aenabled\x18\x02 \x01(\bR\aenabled\"+\n" +
	"\x10RaiseHandRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\"+\n" +
	"\x10LowerHandRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\"S\n" +
	"\x11StartCallResponse\x12>\n" +
	"\fcall_session\x18\x01 \x01(\v2\x1b.voice.calls.v1.CallSessionR\vcallSession\"T\n" +
	"\x12AcceptCallResponse\x12>\n" +
	"\fcall_session\x18\x01 \x01(\v2\x1b.voice.calls.v1.CallSessionR\vcallSession\"U\n" +
	"\x13DeclineCallResponse\x12>\n" +
	"\fcall_session\x18\x01 \x01(\v2\x1b.voice.calls.v1.CallSessionR\vcallSession\"R\n" +
	"\x10JoinCallResponse\x12>\n" +
	"\fcall_session\x18\x01 \x01(\v2\x1b.voice.calls.v1.CallSessionR\vcallSession\"\x13\n" +
	"\x11LeaveCallResponse\"\x11\n" +
	"\x0fEndCallResponse\"Z\n" +
	"\x15JoinVoiceRoomResponse\x12A\n" +
	"\rvoice_session\x18\x01 \x01(\v2\x1c.voice.calls.v1.VoiceSessionR\fvoiceSession\"\x18\n" +
	"\x16LeaveVoiceRoomResponse\"\\\n" +
	"\x17MoveToVoiceRoomResponse\x12A\n" +
	"\rvoice_session\x18\x01 \x01(\v2\x1c.voice.calls.v1.VoiceSessionR\fvoiceSession\"\x84\x01\n" +
	"\x14GetJoinTokenResponse\x12\x10\n" +
	"\x03jwt\x18\x01 \x01(\tR\x03jwt\x129\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12\x1f\n" +
	"\vlivekit_url\x18\x03 \x01(\tR\n" +
	"livekitUrl\"\x1a\n" +
	"\x18UpdateVoiceStateResponse\"c\n" +
	"\x16GetVoiceStatesResponse\x12I\n" +
	"\fparticipants\x18\x01 \x03(\v2%.voice.calls.v1.VoiceParticipantStateR\fparticipants\"W\n" +
	"\x15GetActiveCallResponse\x12>\n" +
	"\fcall_session\x18\x01 \x01(\v2\x1b.voice.calls.v1.CallSessionR\vcallSession\"p\n" +
	"\x18StartScreenShareResponse\x12T\n" +
	"\x14screen_share_session\x18\x01 \x01(\v2\".voice.calls.v1.ScreenShareSessionR\x12screenShareSession\"\x19\n" +
	"\x17StopScreenShareResponse\"\x1a\n" +
	"\x18SetCommanderModeResponse\"\x13\n" +
	"\x11RaiseHandResponse\"\x13\n" +
	"\x11LowerHandResponse*\x9a\x01\n" +
	"\x10VoiceSessionKind\x12\"\n" +
	"\x1eVOICE_SESSION_KIND_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17VOICE_SESSION_KIND_CALL\x10\x01\x12\"\n" +
	"\x1eVOICE_SESSION_KIND_GROUP_VOICE\x10\x02\x12!\n" +
	"\x1dVOICE_SESSION_KIND_VOICE_ROOM\x10\x03*f\n" +
	"\rCallMediaKind\x12\x1f\n" +
	"\x1bCALL_MEDIA_KIND_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15CALL_MEDIA_KIND_AUDIO\x10\x01\x12\x19\n" +
	"\x15CALL_MEDIA_KIND_VIDEO\x10\x02*\xa3\x01\n" +
	"\n" +
	"CallStatus\x12\x1b\n" +
	"\x17CALL_STATUS_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13CALL_STATUS_RINGING\x10\x01\x12\x16\n" +
	"\x12CALL_STATUS_ACTIVE\x10\x02\x12\x18\n" +
	"\x14CALL_STATUS_DECLINED\x10\x03\x12\x16\n" +
	"\x12CALL_STATUS_MISSED\x10\x04\x12\x15\n" +
	"\x11CALL_STATUS_ENDED\x10\x052\xf4\f\n" +
	"\fVoiceService\x12P\n" +
	"\tStartCall\x12 .voice.calls.v1.StartCallRequest\x1a!.voice.calls.v1.StartCallResponse\x12S\n" +
	"\n" +
	"AcceptCall\x12!.voice.calls.v1.AcceptCallRequest\x1a\".voice.calls.v1.AcceptCallResponse\x12V\n" +
	"\vDeclineCall\x12\".voice.calls.v1.DeclineCallRequest\x1a#.voice.calls.v1.DeclineCallResponse\x12M\n" +
	"\bJoinCall\x12\x1f.voice.calls.v1.JoinCallRequest\x1a .voice.calls.v1.JoinCallResponse\x12P\n" +
	"\tLeaveCall\x12 .voice.calls.v1.LeaveCallRequest\x1a!.voice.calls.v1.LeaveCallResponse\x12J\n" +
	"\aEndCall\x12\x1e.voice.calls.v1.EndCallRequest\x1a\x1f.voice.calls.v1.EndCallResponse\x12\\\n" +
	"\rJoinVoiceRoom\x12$.voice.calls.v1.JoinVoiceRoomRequest\x1a%.voice.calls.v1.JoinVoiceRoomResponse\x12_\n" +
	"\x0eLeaveVoiceRoom\x12%.voice.calls.v1.LeaveVoiceRoomRequest\x1a&.voice.calls.v1.LeaveVoiceRoomResponse\x12b\n" +
	"\x0fMoveToVoiceRoom\x12&.voice.calls.v1.MoveToVoiceRoomRequest\x1a'.voice.calls.v1.MoveToVoiceRoomResponse\x12Y\n" +
	"\fGetJoinToken\x12#.voice.calls.v1.GetJoinTokenRequest\x1a$.voice.calls.v1.GetJoinTokenResponse\x12e\n" +
	"\x10UpdateVoiceState\x12'.voice.calls.v1.UpdateVoiceStateRequest\x1a(.voice.calls.v1.UpdateVoiceStateResponse\x12_\n" +
	"\x0eGetVoiceStates\x12%.voice.calls.v1.GetVoiceStatesRequest\x1a&.voice.calls.v1.GetVoiceStatesResponse\x12\\\n" +
	"\rGetActiveCall\x12$.voice.calls.v1.GetActiveCallRequest\x1a%.voice.calls.v1.GetActiveCallResponse\x12e\n" +
	"\x10StartScreenShare\x12'.voice.calls.v1.StartScreenShareRequest\x1a(.voice.calls.v1.StartScreenShareResponse\x12b\n" +
	"\x0fStopScreenShare\x12&.voice.calls.v1.StopScreenShareRequest\x1a'.voice.calls.v1.StopScreenShareResponse\x12e\n" +
	"\x10SetCommanderMode\x12'.voice.calls.v1.SetCommanderModeRequest\x1a(.voice.calls.v1.SetCommanderModeResponse\x12P\n" +
	"\tRaiseHand\x12 .voice.calls.v1.RaiseHandRequest\x1a!.voice.calls.v1.RaiseHandResponse\x12P\n" +
	"\tLowerHand\x12 .voice.calls.v1.LowerHandRequest\x1a!.voice.calls.v1.LowerHandResponseB\"Z voice.app/voice/calls/v1;callsv1b\x06proto3"

var (
	file_voice_calls_v1_calls_proto_rawDescOnce sync.Once
	file_voice_calls_v1_calls_proto_rawDescData []byte
)

func file_voice_calls_v1_calls_proto_rawDescGZIP() []byte {
	file_voice_calls_v1_calls_proto_rawDescOnce.Do(func() {
		file_voice_calls_v1_calls_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_voice_calls_v1_calls_proto_rawDesc), len(file_voice_calls_v1_calls_proto_rawDesc)))
	})
	return file_voice_calls_v1_calls_proto_rawDescData
}

var file_voice_calls_v1_calls_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_voice_calls_v1_calls_proto_msgTypes = make([]protoimpl.MessageInfo, 40)
var file_voice_calls_v1_calls_proto_goTypes = []any{
	(VoiceSessionKind)(0),            // 0: voice.calls.v1.VoiceSessionKind
	(CallMediaKind)(0),               // 1: voice.calls.v1.CallMediaKind
	(CallStatus)(0),                  // 2: voice.calls.v1.CallStatus
	(*StartCallRequest)(nil),         // 3: voice.calls.v1.StartCallRequest
	(*AcceptCallRequest)(nil),        // 4: voice.calls.v1.AcceptCallRequest
	(*DeclineCallRequest)(nil),       // 5: voice.calls.v1.DeclineCallRequest
	(*JoinCallRequest)(nil),          // 6: voice.calls.v1.JoinCallRequest
	(*LeaveCallRequest)(nil),         // 7: voice.calls.v1.LeaveCallRequest
	(*EndCallRequest)(nil),           // 8: voice.calls.v1.EndCallRequest
	(*CallSession)(nil),              // 9: voice.calls.v1.CallSession
	(*JoinVoiceRoomRequest)(nil),     // 10: voice.calls.v1.JoinVoiceRoomRequest
	(*LeaveVoiceRoomRequest)(nil),    // 11: voice.calls.v1.LeaveVoiceRoomRequest
	(*MoveToVoiceRoomRequest)(nil),   // 12: voice.calls.v1.MoveToVoiceRoomRequest
	(*VoiceSession)(nil),             // 13: voice.calls.v1.VoiceSession
	(*GetJoinTokenRequest)(nil),      // 14: voice.calls.v1.GetJoinTokenRequest
	(*UpdateVoiceStateRequest)(nil),  // 15: voice.calls.v1.UpdateVoiceStateRequest
	(*GetVoiceStatesRequest)(nil),    // 16: voice.calls.v1.GetVoiceStatesRequest
	(*VoiceParticipantState)(nil),    // 17: voice.calls.v1.VoiceParticipantState
	(*GetActiveCallRequest)(nil),     // 18: voice.calls.v1.GetActiveCallRequest
	(*StartScreenShareRequest)(nil),  // 19: voice.calls.v1.StartScreenShareRequest
	(*ScreenShareSession)(nil),       // 20: voice.calls.v1.ScreenShareSession
	(*StopScreenShareRequest)(nil),   // 21: voice.calls.v1.StopScreenShareRequest
	(*SetCommanderModeRequest)(nil),  // 22: voice.calls.v1.SetCommanderModeRequest
	(*RaiseHandRequest)(nil),         // 23: voice.calls.v1.RaiseHandRequest
	(*LowerHandRequest)(nil),         // 24: voice.calls.v1.LowerHandRequest
	(*StartCallResponse)(nil),        // 25: voice.calls.v1.StartCallResponse
	(*AcceptCallResponse)(nil),       // 26: voice.calls.v1.AcceptCallResponse
	(*DeclineCallResponse)(nil),      // 27: voice.calls.v1.DeclineCallResponse
	(*JoinCallResponse)(nil),         // 28: voice.calls.v1.JoinCallResponse
	(*LeaveCallResponse)(nil),        // 29: voice.calls.v1.LeaveCallResponse
	(*EndCallResponse)(nil),          // 30: voice.calls.v1.EndCallResponse
	(*JoinVoiceRoomResponse)(nil),    // 31: voice.calls.v1.JoinVoiceRoomResponse
	(*LeaveVoiceRoomResponse)(nil),   // 32: voice.calls.v1.LeaveVoiceRoomResponse
	(*MoveToVoiceRoomResponse)(nil),  // 33: voice.calls.v1.MoveToVoiceRoomResponse
	(*GetJoinTokenResponse)(nil),     // 34: voice.calls.v1.GetJoinTokenResponse
	(*UpdateVoiceStateResponse)(nil), // 35: voice.calls.v1.UpdateVoiceStateResponse
	(*GetVoiceStatesResponse)(nil),   // 36: voice.calls.v1.GetVoiceStatesResponse
	(*GetActiveCallResponse)(nil),    // 37: voice.calls.v1.GetActiveCallResponse
	(*StartScreenShareResponse)(nil), // 38: voice.calls.v1.StartScreenShareResponse
	(*StopScreenShareResponse)(nil),  // 39: voice.calls.v1.StopScreenShareResponse
	(*SetCommanderModeResponse)(nil), // 40: voice.calls.v1.SetCommanderModeResponse
	(*RaiseHandResponse)(nil),        // 41: voice.calls.v1.RaiseHandResponse
	(*LowerHandResponse)(nil),        // 42: voice.calls.v1.LowerHandResponse
	(*v1.ChatRef)(nil),               // 43: voice.chat.v1.ChatRef
	(*v11.SpaceRef)(nil),             // 44: voice.space.v1.SpaceRef
	(*timestamppb.Timestamp)(nil),    // 45: google.protobuf.Timestamp
}
var file_voice_calls_v1_calls_proto_depIdxs = []int32{
	43, // 0: voice.calls.v1.StartCallRequest.linked_chat:type_name -> voice.chat.v1.ChatRef
	44, // 1: voice.calls.v1.StartCallRequest.space:type_name -> voice.space.v1.SpaceRef
	0,  // 2: voice.calls.v1.StartCallRequest.room_type_enum:type_name -> voice.calls.v1.VoiceSessionKind
	1,  // 3: voice.calls.v1.StartCallRequest.media_kind:type_name -> voice.calls.v1.CallMediaKind
	43, // 4: voice.calls.v1.CallSession.linked_chat:type_name -> voice.chat.v1.ChatRef
	45, // 5: voice.calls.v1.CallSession.started_at:type_name -> google.protobuf.Timestamp
	0,  // 6: voice.calls.v1.CallSession.room_type_enum:type_name -> voice.calls.v1.VoiceSessionKind
	1,  // 7: voice.calls.v1.CallSession.media_kind:type_name -> voice.calls.v1.CallMediaKind
	2,  // 8: voice.calls.v1.CallSession.status:type_name -> voice.calls.v1.CallStatus
	45, // 9: voice.calls.v1.CallSession.expires_at:type_name -> google.protobuf.Timestamp
	45, // 10: voice.calls.v1.CallSession.ended_at:type_name -> google.protobuf.Timestamp
	44, // 11: voice.calls.v1.JoinVoiceRoomRequest.space:type_name -> voice.space.v1.SpaceRef
	44, // 12: voice.calls.v1.MoveToVoiceRoomRequest.space:type_name -> voice.space.v1.SpaceRef
	9,  // 13: voice.calls.v1.StartCallResponse.call_session:type_name -> voice.calls.v1.CallSession
	9,  // 14: voice.calls.v1.AcceptCallResponse.call_session:type_name -> voice.calls.v1.CallSession
	9,  // 15: voice.calls.v1.DeclineCallResponse.call_session:type_name -> voice.calls.v1.CallSession
	9,  // 16: voice.calls.v1.JoinCallResponse.call_session:type_name -> voice.calls.v1.CallSession
	13, // 17: voice.calls.v1.JoinVoiceRoomResponse.voice_session:type_name -> voice.calls.v1.VoiceSession
	13, // 18: voice.calls.v1.MoveToVoiceRoomResponse.voice_session:type_name -> voice.calls.v1.VoiceSession
	45, // 19: voice.calls.v1.GetJoinTokenResponse.expires_at:type_name -> google.protobuf.Timestamp
	17, // 20: voice.calls.v1.GetVoiceStatesResponse.participants:type_name -> voice.calls.v1.VoiceParticipantState
	9,  // 21: voice.calls.v1.GetActiveCallResponse.call_session:type_name -> voice.calls.v1.CallSession
	20, // 22: voice.calls.v1.StartScreenShareResponse.screen_share_session:type_name -> voice.calls.v1.ScreenShareSession
	3,  // 23: voice.calls.v1.VoiceService.StartCall:input_type -> voice.calls.v1.StartCallRequest
	4,  // 24: voice.calls.v1.VoiceService.AcceptCall:input_type -> voice.calls.v1.AcceptCallRequest
	5,  // 25: voice.calls.v1.VoiceService.DeclineCall:input_type -> voice.calls.v1.DeclineCallRequest
	6,  // 26: voice.calls.v1.VoiceService.JoinCall:input_type -> voice.calls.v1.JoinCallRequest
	7,  // 27: voice.calls.v1.VoiceService.LeaveCall:input_type -> voice.calls.v1.LeaveCallRequest
	8,  // 28: voice.calls.v1.VoiceService.EndCall:input_type -> voice.calls.v1.EndCallRequest
	10, // 29: voice.calls.v1.VoiceService.JoinVoiceRoom:input_type -> voice.calls.v1.JoinVoiceRoomRequest
	11, // 30: voice.calls.v1.VoiceService.LeaveVoiceRoom:input_type -> voice.calls.v1.LeaveVoiceRoomRequest
	12, // 31: voice.calls.v1.VoiceService.MoveToVoiceRoom:input_type -> voice.calls.v1.MoveToVoiceRoomRequest
	14, // 32: voice.calls.v1.VoiceService.GetJoinToken:input_type -> voice.calls.v1.GetJoinTokenRequest
	15, // 33: voice.calls.v1.VoiceService.UpdateVoiceState:input_type -> voice.calls.v1.UpdateVoiceStateRequest
	16, // 34: voice.calls.v1.VoiceService.GetVoiceStates:input_type -> voice.calls.v1.GetVoiceStatesRequest
	18, // 35: voice.calls.v1.VoiceService.GetActiveCall:input_type -> voice.calls.v1.GetActiveCallRequest
	19, // 36: voice.calls.v1.VoiceService.StartScreenShare:input_type -> voice.calls.v1.StartScreenShareRequest
	21, // 37: voice.calls.v1.VoiceService.StopScreenShare:input_type -> voice.calls.v1.StopScreenShareRequest
	22, // 38: voice.calls.v1.VoiceService.SetCommanderMode:input_type -> voice.calls.v1.SetCommanderModeRequest
	23, // 39: voice.calls.v1.VoiceService.RaiseHand:input_type -> voice.calls.v1.RaiseHandRequest
	24, // 40: voice.calls.v1.VoiceService.LowerHand:input_type -> voice.calls.v1.LowerHandRequest
	25, // 41: voice.calls.v1.VoiceService.StartCall:output_type -> voice.calls.v1.StartCallResponse
	26, // 42: voice.calls.v1.VoiceService.AcceptCall:output_type -> voice.calls.v1.AcceptCallResponse
	27, // 43: voice.calls.v1.VoiceService.DeclineCall:output_type -> voice.calls.v1.DeclineCallResponse
	28, // 44: voice.calls.v1.VoiceService.JoinCall:output_type -> voice.calls.v1.JoinCallResponse
	29, // 45: voice.calls.v1.VoiceService.LeaveCall:output_type -> voice.calls.v1.LeaveCallResponse
	30, // 46: voice.calls.v1.VoiceService.EndCall:output_type -> voice.calls.v1.EndCallResponse
	31, // 47: voice.calls.v1.VoiceService.JoinVoiceRoom:output_type -> voice.calls.v1.JoinVoiceRoomResponse
	32, // 48: voice.calls.v1.VoiceService.LeaveVoiceRoom:output_type -> voice.calls.v1.LeaveVoiceRoomResponse
	33, // 49: voice.calls.v1.VoiceService.MoveToVoiceRoom:output_type -> voice.calls.v1.MoveToVoiceRoomResponse
	34, // 50: voice.calls.v1.VoiceService.GetJoinToken:output_type -> voice.calls.v1.GetJoinTokenResponse
	35, // 51: voice.calls.v1.VoiceService.UpdateVoiceState:output_type -> voice.calls.v1.UpdateVoiceStateResponse
	36, // 52: voice.calls.v1.VoiceService.GetVoiceStates:output_type -> voice.calls.v1.GetVoiceStatesResponse
	37, // 53: voice.calls.v1.VoiceService.GetActiveCall:output_type -> voice.calls.v1.GetActiveCallResponse
	38, // 54: voice.calls.v1.VoiceService.StartScreenShare:output_type -> voice.calls.v1.StartScreenShareResponse
	39, // 55: voice.calls.v1.VoiceService.StopScreenShare:output_type -> voice.calls.v1.StopScreenShareResponse
	40, // 56: voice.calls.v1.VoiceService.SetCommanderMode:output_type -> voice.calls.v1.SetCommanderModeResponse
	41, // 57: voice.calls.v1.VoiceService.RaiseHand:output_type -> voice.calls.v1.RaiseHandResponse
	42, // 58: voice.calls.v1.VoiceService.LowerHand:output_type -> voice.calls.v1.LowerHandResponse
	41, // [41:59] is the sub-list for method output_type
	23, // [23:41] is the sub-list for method input_type
	23, // [23:23] is the sub-list for extension type_name
	23, // [23:23] is the sub-list for extension extendee
	0,  // [0:23] is the sub-list for field type_name
}

func init() { file_voice_calls_v1_calls_proto_init() }
func file_voice_calls_v1_calls_proto_init() {
	if File_voice_calls_v1_calls_proto != nil {
		return
	}
	file_voice_calls_v1_calls_proto_msgTypes[0].OneofWrappers = []any{}
	file_voice_calls_v1_calls_proto_msgTypes[6].OneofWrappers = []any{}
	file_voice_calls_v1_calls_proto_msgTypes[12].OneofWrappers = []any{}
	file_voice_calls_v1_calls_proto_msgTypes[18].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_voice_calls_v1_calls_proto_rawDesc), len(file_voice_calls_v1_calls_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   40,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_voice_calls_v1_calls_proto_goTypes,
		DependencyIndexes: file_voice_calls_v1_calls_proto_depIdxs,
		EnumInfos:         file_voice_calls_v1_calls_proto_enumTypes,
		MessageInfos:      file_voice_calls_v1_calls_proto_msgTypes,
	}.Build()
	File_voice_calls_v1_calls_proto = out.File
	file_voice_calls_v1_calls_proto_goTypes = nil
	file_voice_calls_v1_calls_proto_depIdxs = nil
}
