// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: voice/auth/v1/auth.proto

package authv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Canonical values for VerifyOTPRequest.otp_type (string).
type OtpType int32

const (
	OtpType_OTP_TYPE_UNSPECIFIED    OtpType = 0
	OtpType_OTP_TYPE_EMAIL_VERIFY   OtpType = 1
	OtpType_OTP_TYPE_PASSWORD_RESET OtpType = 2
)

// Enum value maps for OtpType.
var (
	OtpType_name = map[int32]string{
		0: "OTP_TYPE_UNSPECIFIED",
		1: "OTP_TYPE_EMAIL_VERIFY",
		2: "OTP_TYPE_PASSWORD_RESET",
	}
	OtpType_value = map[string]int32{
		"OTP_TYPE_UNSPECIFIED":    0,
		"OTP_TYPE_EMAIL_VERIFY":   1,
		"OTP_TYPE_PASSWORD_RESET": 2,
	}
)

func (x OtpType) Enum() *OtpType {
	p := new(OtpType)
	*p = x
	return p
}

func (x OtpType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OtpType) Descriptor() protoreflect.EnumDescriptor {
	return file_voice_auth_v1_auth_proto_enumTypes[0].Descriptor()
}

func (OtpType) Type() protoreflect.EnumType {
	return &file_voice_auth_v1_auth_proto_enumTypes[0]
}

func (x OtpType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OtpType.Descriptor instead.
func (OtpType) EnumDescriptor() ([]byte, []int) {
	return file_voice_auth_v1_auth_proto_rawDescGZIP(), []int{0}
}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         *string                `protobuf:"bytes,1,opt,name=email,proto3,oneof" json:"email,omitempty"`
	Phone         *string                `protobuf:"bytes,2,opt,name=phone,proto3,oneof" json:"phone,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Guest         bool                   `protobuf:"varint,4,opt,name=guest,proto3" json:"guest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_voice_auth_v1_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_voice_auth_v1_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_voice_auth_v1_auth_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetEmail() string {
	if x != nil && x.Email != nil {
		return *x.Email
	}
	return ""
}

func (x *RegisterRequest) GetPhone() string {
	if x != nil && x.Phone != nil {
		return *x.Phone
	}
	return ""
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterRequest) GetGuest() bool {
	if x != nil {
		return x.Guest
	}
	return false
}

type LoginRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Email          *string                `protobuf:"bytes,1,opt,name=email,proto3,oneof" json:"email,omitempty"`
	Phone          *string                `protobuf:"bytes,2,opt,name=phone,proto3,oneof" json:"phone,omitempty"`
	Password       string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	TotpCode       *string                `protobuf:"bytes,4,opt,name=totp_code,json=totpCode,proto3,oneof" json:"totp_code,omitempty"`
	DeviceInfoJson string                 `protobuf:"bytes,5,opt,name=device_info_json,json=deviceInfoJson,proto3" json:"device_info_json,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_voice_auth_v1_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_voice_auth_v1_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_voice_auth_v1_auth_proto_rawDescGZIP(), []int{1}
}

func (x *LoginRequest) GetEmail() string {
	if x != nil && x.Email != nil {
		return *x.Email
	}
	return ""
}

func (x *LoginRequest) GetPhone() string {
	if x != nil && x.Phone != nil {
		return *x.Phone
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *LoginRequest) GetTotpCode() string {
	if x != nil && x.TotpCode != nil {
		return *x.TotpCode
	}
	return ""
}

func (x *LoginRequest) GetDeviceInfoJson() string {
	if x != nil {
		return x.DeviceInfoJson
	}
	return ""
}

type LogoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  string                 `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutRequest) Reset() {
	*x = LogoutRequest{}
	mi := &file_voice_auth_v1_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutRequest) ProtoMessage() {}

func (x *LogoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_voice_auth_v1_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutRequest.ProtoReflect.Descriptor instead.
func (*LogoutRequest) Descriptor() ([]byte, []int) {
	return file_voice_auth_v1_auth_proto_rawDescGZIP(), []int{2}
}

func (x *LogoutRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type RefreshTokenRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken   string                 `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	DeviceInfoJson string                 `protobuf:"bytes,2,opt,name=device_info_json,json=deviceInfoJson,proto3" json:"device_info_json,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RefreshTokenRequest) Reset() {
	*x = RefreshTokenRequest{}
	mi := &file_voice_auth_v1_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenRequest) ProtoMessage() {}

func (x *RefreshTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_voice_auth_v1_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenRequest.ProtoReflect.Descriptor instead.
func (*RefreshTokenRequest) Descriptor() ([]byte, []int) {
	return file_voice_auth_v1_auth_proto_rawDescGZIP(), []int{3}
}

func (x *RefreshTokenRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *RefreshTokenRequest) GetDeviceInfoJson() string {
	if x != nil {
		return x.DeviceInfoJson
	}
	return ""
}

type Enable2FARequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Password      string                 `protobuf:"bytes,1,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Enable2FARequest) Reset() {
	*x = Enable2FARequest{}
	mi := &file_voice_auth_v1_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Enable2FARequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Enable2FARequest) ProtoMessage() {}

func (x *Enable2FARequest) ProtoReflect() protoreflect.Message {
	mi := &file_voice_auth_v1_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Enable2FARequest.ProtoReflect.Descriptor instead.
func (*Enable2FARequest) Descriptor() ([]byte, []int) {
	return file_voice_auth_v1_auth_proto_rawDescGZIP(), []int{4}
}

func (x *Enable2FARequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type Enable2FAResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TotpUri          string                 `protobuf:"bytes,1,opt,name=totp_uri,json=totpUri,proto3" json:"totp_uri,omitempty"`
	SecretBackupHint string                 `protobuf:"bytes,2,opt,name=secret_backup_hint,json=secretBackupHint,proto3" json:"secret_backup_hint,omitempty"`
	// One-time plaintext backup codes; shown only at enrollment (docs/features/auth-and-contacts.md).
	BackupCodes   []string `protobuf:"bytes,3,rep,name=backup_codes,json=backupCodes,proto3" json:"backup_codes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Enable2FAResponse) Reset() {
	*x = Enable2FAResponse{}
	mi := &file_voice_auth_v1_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Enable2FAResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Enable2FAResponse) ProtoMessage() {}

func (x *Enable2FAResponse) ProtoReflect() protoreflect.Message {
	mi := &file_voice_auth_v1_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Enable2FAResponse.ProtoReflect.Descriptor instead.
func (*Enable2FAResponse) Descriptor() ([]byte, []int) {
	return file_voice_auth_v1_auth_proto_rawDescGZIP(), []int{5}
}

func (x *Enable2FAResponse) GetTotpUri() string {
	if x != nil {
		return x.TotpUri
	}
	return ""
}

func (x *Enable2FAResponse) GetSecretBackupHint() string {
	if x != nil {
		return x.SecretBackupHint
	}
	return ""
}

func (x *Enable2FAResponse) GetBackupCodes() []string {
	if x != nil {
		return x.BackupCodes
	}
	return nil
}

type Verify2FARequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotpCode      string                 `protobuf:"bytes,1,opt,name=totp_code,json=totpCode,proto3" json:"totp_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Verify2FARequest) Reset() {
	*x = Verify2FARequest{}
	mi := &file_voice_auth_v1_auth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Verify2FARequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Verify2FARequest) ProtoMessage() {}

func (x *Verify2FARequest) ProtoReflect() protoreflect.Message {
	mi := &file_voice_auth_v1_auth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Verify2FARequest.ProtoReflect.Descriptor instead.
func (*Verify2FARequest) Descriptor() ([]byte, []int) {
	return file_voice_auth_v1_auth_proto_rawDescGZIP(), []int{6}
}

func (x *Verify2FARequest) GetTotpCode() string {
	if x != nil {
		return x.TotpCode
	}
	return ""
}

type VerifyOTPRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	OtpType       string                 `protobuf:"bytes,2,opt,name=otp_type,json=otpType,proto3" json:"otp_type,omitempty"`                                                 // email_verify | password_reset — see enum OtpType for canonical values
	OtpTypeEnum   *OtpType               `protobuf:"varint,3,opt,name=otp_type_enum,json=otpTypeEnum,proto3,enum=voice.auth.v1.OtpType,oneof" json:"otp_type_enum,omitempty"` // prefer when set (docs/REPOSITORIES.md)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyOTPRequest) Reset() {
	*x = VerifyOTPRequest{}
	mi := &file_voice_auth_v1_auth_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyOTPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyOTPRequest) ProtoMessage() {}

func (x *VerifyOTPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_voice_auth_v1_auth_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyOTPRequest.ProtoReflect.Descriptor instead.
func (*VerifyOTPRequest) Descriptor() ([]byte, []int) {
	return file_voice_auth_v1_auth_proto_rawDescGZIP(), []int{7}
}

func (x *VerifyOTPRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *VerifyOTPRequest) GetOtpType() string {
	if x != nil {
		return x.OtpType
	}
	return ""
}

func (x *VerifyOTPRequest) GetOtpTypeEnum() OtpType {
	if x != nil && x.OtpTypeEnum != nil {
		return *x.OtpTypeEnum
	}
	return OtpType_OTP_TYPE_UNSPECIFIED
}

type ConvertGuestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         *string                `protobuf:"bytes,1,opt,name=email,proto3,oneof" json:"email,omitempty"`
	Phone         *string                `protobuf:"bytes,2,opt,name=phone,proto3,oneof" json:"phone,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConvertGuestRequest) Reset() {
	*x = ConvertGuestRequest{}
	mi := &file_voice_auth_v1_auth_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConvertGuestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConvertGuestRequest) ProtoMessage() {}

func (x *ConvertGuestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_voice_auth_v1_auth_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConvertGuestRequest.ProtoReflect.Descriptor instead.
func (*ConvertGuestRequest) Descriptor() ([]byte, []int) {
	return file_voice_auth_v1_auth_proto_rawDescGZIP(), []int{8}
}

func (x *ConvertGuestRequest) GetEmail() string {
	if x != nil && x.Email != nil {
		return *x.Email
	}
	return ""
}

func (x *ConvertGuestRequest) GetPhone() string {
	if x != nil && x.Phone != nil {
		return *x.Phone
	}
	return ""
}

func (x *ConvertGuestRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type DeleteAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Password      string                 `protobuf:"bytes,1,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAccountRequest) Reset() {
	*x = DeleteAccountRequest{}
	mi := &file_voice_auth_v1_auth_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAccountRequest) ProtoMessage() {}

func (x *DeleteAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_voice_auth_v1_auth_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAccountRequest.ProtoReflect.Descriptor instead.
func (*DeleteAccountRequest) Descriptor() ([]byte, []int) {
	return file_voice_auth_v1_auth_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteAccountRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type RestoreAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreAccountRequest) Reset() {
	*x = RestoreAccountRequest{}
	mi := &file_voice_auth_v1_auth_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreAccountRequest) ProtoMessage() {}

func (x *RestoreAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_voice_auth_v1_auth_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreAccountRequest.ProtoReflect.Descriptor instead.
func (*RestoreAccountRequest) Descriptor() ([]byte, []int) {
	return file_voice_auth_v1_auth_proto_rawDescGZIP(), []int{10}
}

func (x *RestoreAccountRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type ValidateTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateTokenRequest) Reset() {
	*x = ValidateTokenRequest{}
	mi := &file_voice_auth_v1_auth_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateTokenRequest) ProtoMessage() {}

func (x *ValidateTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_voice_auth_v1_auth_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateTokenRequest.ProtoReflect.Descriptor instead.
func (*ValidateTokenRequest) Descriptor() ([]byte, []int) {
	return file_voice_auth_v1_auth_proto_rawDescGZIP(), []int{11}
}

func (x *ValidateTokenRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

// Issued session (access + refresh + account id + active profile).
type AuthSession struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AccessToken      string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken     string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	ExpiresInSeconds int64                  `protobuf:"varint,3,opt,name=expires_in_seconds,json=expiresInSeconds,proto3" json:"expires_in_seconds,omitempty"`
	AccountId        string                 `protobuf:"bytes,4,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	ProfileId        string                 `protobuf:"bytes,5,opt,name=profile_id,json=profileId,proto3" json:"profile_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AuthSession) Reset() {
	*x = AuthSession{}
	mi := &file_voice_auth_v1_auth_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthSession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthSession) ProtoMessage() {}

func (x *AuthSession) ProtoReflect() protoreflect.Message {
	mi := &file_voice_auth_v1_auth_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthSession.ProtoReflect.Descriptor instead.
func (*AuthSession) Descriptor() ([]byte, []int) {
	return file_voice_auth_v1_auth_proto_rawDescGZIP(), []int{12}
}

func (x *AuthSession) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *AuthSession) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *AuthSession) GetExpiresInSeconds() int64 {
	if x != nil {
		return x.ExpiresInSeconds
	}
	return 0
}

func (x *AuthSession) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *AuthSession) GetProfileId() string {
	if x != nil {
		return x.ProfileId
	}
	return ""
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *AuthSession           `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_voice_auth_v1_auth_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_voice_auth_v1_auth_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_voice_auth_v1_auth_proto_rawDescGZIP(), []int{13}
}

func (x *RegisterResponse) GetSession() *AuthSession {
	if x != nil {
		return x.Session
	}
	return nil
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *AuthSession           `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_voice_auth_v1_auth_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_voice_auth_v1_auth_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_voice_auth_v1_auth_proto_rawDescGZIP(), []int{14}
}

func (x *LoginResponse) GetSession() *AuthSession {
	if x != nil {
		return x.Session
	}
	return nil
}

type LogoutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutResponse) Reset() {
	*x = LogoutResponse{}
	mi := &file_voice_auth_v1_auth_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutResponse) ProtoMessage() {}

func (x *LogoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_voice_auth_v1_auth_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutResponse.ProtoReflect.Descriptor instead.
func (*LogoutResponse) Descriptor() ([]byte, []int) {
	return file_voice_auth_v1_auth_proto_rawDescGZIP(), []int{15}
}

type RefreshTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *AuthSession           `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenResponse) Reset() {
	*x = RefreshTokenResponse{}
	mi := &file_voice_auth_v1_auth_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenResponse) ProtoMessage() {}

func (x *RefreshTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_voice_auth_v1_auth_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenResponse.ProtoReflect.Descriptor instead.
func (*RefreshTokenResponse) Descriptor() ([]byte, []int) {
	return file_voice_auth_v1_auth_proto_rawDescGZIP(), []int{16}
}

func (x *RefreshTokenResponse) GetSession() *AuthSession {
	if x != nil {
		return x.Session
	}
	return nil
}

type Verify2FAResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *AuthSession           `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Verify2FAResponse) Reset() {
	*x = Verify2FAResponse{}
	mi := &file_voice_auth_v1_auth_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Verify2FAResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Verify2FAResponse) ProtoMessage() {}

func (x *Verify2FAResponse) ProtoReflect() protoreflect.Message {
	mi := &file_voice_auth_v1_auth_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Verify2FAResponse.ProtoReflect.Descriptor instead.
func (*Verify2FAResponse) Descriptor() ([]byte, []int) {
	return file_voice_auth_v1_auth_proto_rawDescGZIP(), []int{17}
}

func (x *Verify2FAResponse) GetSession() *AuthSession {
	if x != nil {
		return x.Session
	}
	return nil
}

type VerifyOTPResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyOTPResponse) Reset() {
	*x = VerifyOTPResponse{}
	mi := &file_voice_auth_v1_auth_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyOTPResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyOTPResponse) ProtoMessage() {}

func (x *VerifyOTPResponse) ProtoReflect() protoreflect.Message {
	mi := &file_voice_auth_v1_auth_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyOTPResponse.ProtoReflect.Descriptor instead.
func (*VerifyOTPResponse) Descriptor() ([]byte, []int) {
	return file_voice_auth_v1_auth_proto_rawDescGZIP(), []int{18}
}

type ConvertGuestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *AuthSession           `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConvertGuestResponse) Reset() {
	*x = ConvertGuestResponse{}
	mi := &file_voice_auth_v1_auth_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConvertGuestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConvertGuestResponse) ProtoMessage() {}

func (x *ConvertGuestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_voice_auth_v1_auth_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConvertGuestResponse.ProtoReflect.Descriptor instead.
func (*ConvertGuestResponse) Descriptor() ([]byte, []int) {
	return file_voice_auth_v1_auth_proto_rawDescGZIP(), []int{19}
}

func (x *ConvertGuestResponse) GetSession() *AuthSession {
	if x != nil {
		return x.Session
	}
	return nil
}

type DeleteAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAccountResponse) Reset() {
	*x = DeleteAccountResponse{}
	mi := &file_voice_auth_v1_auth_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAccountResponse) ProtoMessage() {}

func (x *DeleteAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_voice_auth_v1_auth_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAccountResponse.ProtoReflect.Descriptor instead.
func (*DeleteAccountResponse) Descriptor() ([]byte, []int) {
	return file_voice_auth_v1_auth_proto_rawDescGZIP(), []int{20}
}

type RestoreAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *AuthSession           `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreAccountResponse) Reset() {
	*x = RestoreAccountResponse{}
	mi := &file_voice_auth_v1_auth_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreAccountResponse) ProtoMessage() {}

func (x *RestoreAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_voice_auth_v1_auth_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreAccountResponse.ProtoReflect.Descriptor instead.
func (*RestoreAccountResponse) Descriptor() ([]byte, []int) {
	return file_voice_auth_v1_auth_proto_rawDescGZIP(), []int{21}
}

func (x *RestoreAccountResponse) GetSession() *AuthSession {
	if x != nil {
		return x.Session
	}
	return nil
}

type ValidateTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Claims        *TokenClaims           `protobuf:"bytes,1,opt,name=claims,proto3" json:"claims,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateTokenResponse) Reset() {
	*x = ValidateTokenResponse{}
	mi := &file_voice_auth_v1_auth_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateTokenResponse) ProtoMessage() {}

func (x *ValidateTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_voice_auth_v1_auth_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateTokenResponse.ProtoReflect.Descriptor instead.
func (*ValidateTokenResponse) Descriptor() ([]byte, []int) {
	return file_voice_auth_v1_auth_proto_rawDescGZIP(), []int{22}
}

func (x *ValidateTokenResponse) GetClaims() *TokenClaims {
	if x != nil {
		return x.Claims
	}
	return nil
}

type GetJWKSRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJWKSRequest) Reset() {
	*x = GetJWKSRequest{}
	mi := &file_voice_auth_v1_auth_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJWKSRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJWKSRequest) ProtoMessage() {}

func (x *GetJWKSRequest) ProtoReflect() protoreflect.Message {
	mi := &file_voice_auth_v1_auth_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJWKSRequest.ProtoReflect.Descriptor instead.
func (*GetJWKSRequest) Descriptor() ([]byte, []int) {
	return file_voice_auth_v1_auth_proto_rawDescGZIP(), []int{23}
}

type GetJWKSResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeysJson      string                 `protobuf:"bytes,1,opt,name=keys_json,json=keysJson,proto3" json:"keys_json,omitempty"` // JWKS document as JSON string
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJWKSResponse) Reset() {
	*x = GetJWKSResponse{}
	mi := &file_voice_auth_v1_auth_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJWKSResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJWKSResponse) ProtoMessage() {}

func (x *GetJWKSResponse) ProtoReflect() protoreflect.Message {
	mi := &file_voice_auth_v1_auth_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJWKSResponse.ProtoReflect.Descriptor instead.
func (*GetJWKSResponse) Descriptor() ([]byte, []int) {
	return file_voice_auth_v1_auth_proto_rawDescGZIP(), []int{24}
}

func (x *GetJWKSResponse) GetKeysJson() string {
	if x != nil {
		return x.KeysJson
	}
	return ""
}

type TokenClaims struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	UserId           string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // account_id (JWT claim name per docs)
	ProfileId        string                 `protobuf:"bytes,2,opt,name=profile_id,json=profileId,proto3" json:"profile_id,omitempty"`
	Roles            []string               `protobuf:"bytes,3,rep,name=roles,proto3" json:"roles,omitempty"`
	SubscriptionTier string                 `protobuf:"bytes,4,opt,name=subscription_tier,json=subscriptionTier,proto3" json:"subscription_tier,omitempty"`
	ExpiresAt        *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TokenClaims) Reset() {
	*x = TokenClaims{}
	mi := &file_voice_auth_v1_auth_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenClaims) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenClaims) ProtoMessage() {}

func (x *TokenClaims) ProtoReflect() protoreflect.Message {
	mi := &file_voice_auth_v1_auth_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenClaims.ProtoReflect.Descriptor instead.
func (*TokenClaims) Descriptor() ([]byte, []int) {
	return file_voice_auth_v1_auth_proto_rawDescGZIP(), []int{25}
}

func (x *TokenClaims) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *TokenClaims) GetProfileId() string {
	if x != nil {
		return x.ProfileId
	}
	return ""
}

func (x *TokenClaims) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *TokenClaims) GetSubscriptionTier() string {
	if x != nil {
		return x.SubscriptionTier
	}
	return ""
}

func (x *TokenClaims) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type SwitchActiveProfileRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AccessToken    string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	ProfileId      string                 `protobuf:"bytes,2,opt,name=profile_id,json=profileId,proto3" json:"profile_id,omitempty"`
	DeviceInfoJson string                 `protobuf:"bytes,3,opt,name=device_info_json,json=deviceInfoJson,proto3" json:"device_info_json,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SwitchActiveProfileRequest) Reset() {
	*x = SwitchActiveProfileRequest{}
	mi := &file_voice_auth_v1_auth_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SwitchActiveProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SwitchActiveProfileRequest) ProtoMessage() {}

func (x *SwitchActiveProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_voice_auth_v1_auth_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SwitchActiveProfileRequest.ProtoReflect.Descriptor instead.
func (*SwitchActiveProfileRequest) Descriptor() ([]byte, []int) {
	return file_voice_auth_v1_auth_proto_rawDescGZIP(), []int{26}
}

func (x *SwitchActiveProfileRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *SwitchActiveProfileRequest) GetProfileId() string {
	if x != nil {
		return x.ProfileId
	}
	return ""
}

func (x *SwitchActiveProfileRequest) GetDeviceInfoJson() string {
	if x != nil {
		return x.DeviceInfoJson
	}
	return ""
}

type SwitchActiveProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *AuthSession           `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SwitchActiveProfileResponse) Reset() {
	*x = SwitchActiveProfileResponse{}
	mi := &file_voice_auth_v1_auth_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SwitchActiveProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SwitchActiveProfileResponse) ProtoMessage() {}

func (x *SwitchActiveProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_voice_auth_v1_auth_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SwitchActiveProfileResponse.ProtoReflect.Descriptor instead.
func (*SwitchActiveProfileResponse) Descriptor() ([]byte, []int) {
	return file_voice_auth_v1_auth_proto_rawDescGZIP(), []int{27}
}

func (x *SwitchActiveProfileResponse) GetSession() *AuthSession {
	if x != nil {
		return x.Session
	}
	return nil
}

type SetAccountStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // active | suspended
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetAccountStatusRequest) Reset() {
	*x = SetAccountStatusRequest{}
	mi := &file_voice_auth_v1_auth_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetAccountStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetAccountStatusRequest) ProtoMessage() {}

func (x *SetAccountStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_voice_auth_v1_auth_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetAccountStatusRequest.ProtoReflect.Descriptor instead.
func (*SetAccountStatusRequest) Descriptor() ([]byte, []int) {
	return file_voice_auth_v1_auth_proto_rawDescGZIP(), []int{28}
}

func (x *SetAccountStatusRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *SetAccountStatusRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SetAccountStatusRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type SetAccountStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetAccountStatusResponse) Reset() {
	*x = SetAccountStatusResponse{}
	mi := &file_voice_auth_v1_auth_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetAccountStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetAccountStatusResponse) ProtoMessage() {}

func (x *SetAccountStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_voice_auth_v1_auth_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetAccountStatusResponse.ProtoReflect.Descriptor instead.
func (*SetAccountStatusResponse) Descriptor() ([]byte, []int) {
	return file_voice_auth_v1_auth_proto_rawDescGZIP(), []int{29}
}

var File_voice_auth_v1_auth_proto protoreflect.FileDescriptor

const file_voice_auth_v1_auth_proto_rawDesc = "" +
	"\n" +
	"\x18voice/auth/v1/auth.proto\x12\rvoice.auth.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x8d\x01\n" +
	"\x0fRegisterRequest\x12\x19\n" +
	"\x05email\x18\x01 \x01(\tH\x00R\x05email\x88\x01\x01\x12\x19\n" +
	"\x05phone\x18\x02 \x01(\tH\x01R\x05phone\x88\x01\x01\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x12\x14\n" +
	"\x05guest\x18\x04 \x01(\bR\x05guestB\b\n" +
	"\x06_emailB\b\n" +
	"\x06_phone\"\xce\x01\n" +
	"\fLoginRequest\x12\x19\n" +
	"\x05email\x18\x01 \x01(\tH\x00R\x05email\x88\x01\x01\x12\x19\n" +
	"\x05phone\x18\x02 \x01(\tH\x01R\x05phone\x88\x01\x01\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x12 \n" +
	"\ttotp_code\x18\x04 \x01(\tH\x02R\btotpCode\x88\x01\x01\x12(\n" +
	"\x10device_info_json\x18\x05 \x01(\tR\x0edeviceInfoJsonB\b\n" +
	"\x06_emailB\b\n" +
	"\x06_phoneB\f\n" +
	"\n" +
	"_totp_code\"4\n" +
	"\rLogoutRequest\x12#\n" +
	"\rrefresh_token\x18\x01 \x01(\tR\frefreshToken\"d\n" +
	"\x13RefreshTokenRequest\x12#\n" +
	"\rrefresh_token\x18\x01 \x01(\tR\frefreshToken\x12(\n" +
	"\x10device_info_json\x18\x02 \x01(\tR\x0edeviceInfoJson\".\n" +
	"\x10Enable2FARequest\x12\x1a\n" +
	"\bpassword\x18\x01 \x01(\tR\bpassword\"\x7f\n" +
	"\x11Enable2FAResponse\x12\x19\n" +
	"\btotp_uri\x18\x01 \x01(\tR\atotpUri\x12,\n" +
	"\x12secret_backup_hint\x18\x02 \x01(\tR\x10secretBackupHint\x12!\n" +
	"\fbackup_codes\x18\x03 \x03(\tR\vbackupCodes\"/\n" +
	"\x10Verify2FARequest\x12\x1b\n" +
	"\ttotp_code\x18\x01 \x01(\tR\btotpCode\"\x94\x01\n" +
	"\x10VerifyOTPRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x19\n" +
	"\botp_type\x18\x02 \x01(\tR\aotpType\x12?\n" +
	"\rotp_type_enum\x18\x03 \x01(\x0e2\x16.voice.auth.v1.OtpTypeH\x00R\votpTypeEnum\x88\x01\x01B\x10\n" +
	"\x0e_otp_type_enum\"{\n" +
	"\x13ConvertGuestRequest\x12\x19\n" +
	"\x05email\x18\x01 \x01(\tH\x00R\x05email\x88\x01\x01\x12\x19\n" +
	"\x05phone\x18\x02 \x01(\tH\x01R\x05phone\x88\x01\x01\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpasswordB\b\n" +
	"\x06_emailB\b\n" +
	"\x06_phone\"2\n" +
	"\x14DeleteAccountRequest\x12\x1a\n" +
	"\bpassword\x18\x01 \x01(\tR\bpassword\"-\n" +
	"\x15RestoreAccountRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"9\n" +
	"\x14ValidateTokenRequest\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\"\xc1\x01\n" +
	"\vAuthSession\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\x12,\n" +
	"\x12expires_in_seconds\x18\x03 \x01(\x03R\x10expiresInSeconds\x12\x1d\n" +
	"\n" +
	"account_id\x18\x04 \x01(\tR\taccountId\x12\x1d\n" +
	"\n" +
	"profile_id\x18\x05 \x01(\tR\tprofileId\"H\n" +
	"\x10RegisterResponse\x124\n" +
	"\asession\x18\x01 \x01(\v2\x1a.voice.auth.v1.AuthSessionR\asession\"E\n" +
	"\rLoginResponse\x124\n" +
	"\asession\x18\x01 \x01(\v2\x1a.voice.auth.v1.AuthSessionR\asession\"\x10\n" +
	"\x0eLogoutResponse\"L\n" +
	"\x14RefreshTokenResponse\x124\n" +
	"\asession\x18\x01 \x01(\v2\x1a.voice.auth.v1.AuthSessionR\asession\"I\n" +
	"\x11Verify2FAResponse\x124\n" +
	"\asession\x18\x01 \x01(\v2\x1a.voice.auth.v1.AuthSessionR\asession\"\x13\n" +
	"\x11VerifyOTPResponse\"L\n" +
	"\x14ConvertGuestResponse\x124\n" +
	"\asession\x18\x01 \x01(\v2\x1a.voice.auth.v1.AuthSessionR\asession\"\x17\n" +
	"\x15DeleteAccountResponse\"N\n" +
	"\x16RestoreAccountResponse\x124\n" +
	"\asession\x18\x01 \x01(\v2\x1a.voice.auth.v1.AuthSessionR\asession\"K\n" +
	"\x15ValidateTokenResponse\x122\n" +
	"\x06claims\x18\x01 \x01(\v2\x1a.voice.auth.v1.TokenClaimsR\x06claims\"\x10\n" +
	"\x0eGetJWKSRequest\".\n" +
	"\x0fGetJWKSResponse\x12\x1b\n" +
	"\tkeys_json\x18\x01 \x01(\tR\bkeysJson\"\xc3\x01\n" +
	"\vTokenClaims\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"profile_id\x18\x02 \x01(\tR\tprofileId\x12\x14\n" +
	"\x05roles\x18\x03 \x03(\tR\x05roles\x12+\n" +
	"\x11subscription_tier\x18\x04 \x01(\tR\x10subscriptionTier\x129\n" +
	"\n" +
	"expires_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"\x88\x01\n" +
	"\x1aSwitchActiveProfileRequest\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12\x1d\n" +
	"\n" +
	"profile_id\x18\x02 \x01(\tR\tprofileId\x12(\n" +
	"\x10device_info_json\x18\x03 \x01(\tR\x0edeviceInfoJson\"S\n" +
	"\x1bSwitchActiveProfileResponse\x124\n" +
	"\asession\x18\x01 \x01(\v2\x1a.voice.auth.v1.AuthSessionR\asession\"h\n" +
	"\x17SetAccountStatusRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"\x1a\n" +
	"\x18SetAccountStatusResponse*[\n" +
	"\aOtpType\x12\x18\n" +
	"\x14OTP_TYPE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15OTP_TYPE_EMAIL_VERIFY\x10\x01\x12\x1b\n" +
	"\x17OTP_TYPE_PASSWORD_RESET\x10\x022\xbb\t\n" +
	"\vAuthService\x12K\n" +
	"\bRegister\x12\x1e.voice.auth.v1.RegisterRequest\x1a\x1f.voice.auth.v1.RegisterResponse\x12B\n" +
	"\x05Login\x12\x1b.voice.auth.v1.LoginRequest\x1a\x1c.voice.auth.v1.LoginResponse\x12E\n" +
	"\x06Logout\x12\x1c.voice.auth.v1.LogoutRequest\x1a\x1d.voice.auth.v1.LogoutResponse\x12W\n" +
	"\fRefreshToken\x12\".voice.auth.v1.RefreshTokenRequest\x1a#.voice.auth.v1.RefreshTokenResponse\x12N\n" +
	"\tEnable2FA\x12\x1f.voice.auth.v1.Enable2FARequest\x1a .voice.auth.v1.Enable2FAResponse\x12N\n" +
	"\tVerify2FA\x12\x1f.voice.auth.v1.Verify2FARequest\x1a .voice.auth.v1.Verify2FAResponse\x12N\n" +
	"\tVerifyOTP\x12\x1f.voice.auth.v1.VerifyOTPRequest\x1a .voice.auth.v1.VerifyOTPResponse\x12W\n" +
	"\fConvertGuest\x12\".voice.auth.v1.ConvertGuestRequest\x1a#.voice.auth.v1.ConvertGuestResponse\x12Z\n" +
	"\rDeleteAccount\x12#.voice.auth.v1.DeleteAccountRequest\x1a$.voice.auth.v1.DeleteAccountResponse\x12]\n" +
	"\x0eRestoreAccount\x12$.voice.auth.v1.RestoreAccountRequest\x1a%.voice.auth.v1.RestoreAccountResponse\x12Z\n" +
	"\rValidateToken\x12#.voice.auth.v1.ValidateTokenRequest\x1a$.voice.auth.v1.ValidateTokenResponse\x12H\n" +
	"\aGetJWKS\x12\x1d.voice.auth.v1.GetJWKSRequest\x1a\x1e.voice.auth.v1.GetJWKSResponse\x12l\n" +
	"\x13SwitchActiveProfile\x12).voice.auth.v1.SwitchActiveProfileRequest\x1a*.voice.auth.v1.SwitchActiveProfileResponse\x12c\n" +
	"\x10SetAccountStatus\x12&.voice.auth.v1.SetAccountStatusRequest\x1a'.voice.auth.v1.SetAccountStatusResponseB5\n" +
	"\x11app.voice.auth.v1P\x01Z\x1evoice.app/voice/auth/v1;authv1b\x06proto3"

var (
	file_voice_auth_v1_auth_proto_rawDescOnce sync.Once
	file_voice_auth_v1_auth_proto_rawDescData []byte
)

func file_voice_auth_v1_auth_proto_rawDescGZIP() []byte {
	file_voice_auth_v1_auth_proto_rawDescOnce.Do(func() {
		file_voice_auth_v1_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_voice_auth_v1_auth_proto_rawDesc), len(file_voice_auth_v1_auth_proto_rawDesc)))
	})
	return file_voice_auth_v1_auth_proto_rawDescData
}

var file_voice_auth_v1_auth_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_voice_auth_v1_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 30)
var file_voice_auth_v1_auth_proto_goTypes = []any{
	(OtpType)(0),                        // 0: voice.auth.v1.OtpType
	(*RegisterRequest)(nil),             // 1: voice.auth.v1.RegisterRequest
	(*LoginRequest)(nil),                // 2: voice.auth.v1.LoginRequest
	(*LogoutRequest)(nil),               // 3: voice.auth.v1.LogoutRequest
	(*RefreshTokenRequest)(nil),         // 4: voice.auth.v1.RefreshTokenRequest
	(*Enable2FARequest)(nil),            // 5: voice.auth.v1.Enable2FARequest
	(*Enable2FAResponse)(nil),           // 6: voice.auth.v1.Enable2FAResponse
	(*Verify2FARequest)(nil),            // 7: voice.auth.v1.Verify2FARequest
	(*VerifyOTPRequest)(nil),            // 8: voice.auth.v1.VerifyOTPRequest
	(*ConvertGuestRequest)(nil),         // 9: voice.auth.v1.ConvertGuestRequest
	(*DeleteAccountRequest)(nil),        // 10: voice.auth.v1.DeleteAccountRequest
	(*RestoreAccountRequest)(nil),       // 11: voice.auth.v1.RestoreAccountRequest
	(*ValidateTokenRequest)(nil),        // 12: voice.auth.v1.ValidateTokenRequest
	(*AuthSession)(nil),                 // 13: voice.auth.v1.AuthSession
	(*RegisterResponse)(nil),            // 14: voice.auth.v1.RegisterResponse
	(*LoginResponse)(nil),               // 15: voice.auth.v1.LoginResponse
	(*LogoutResponse)(nil),              // 16: voice.auth.v1.LogoutResponse
	(*RefreshTokenResponse)(nil),        // 17: voice.auth.v1.RefreshTokenResponse
	(*Verify2FAResponse)(nil),           // 18: voice.auth.v1.Verify2FAResponse
	(*VerifyOTPResponse)(nil),           // 19: voice.auth.v1.VerifyOTPResponse
	(*ConvertGuestResponse)(nil),        // 20: voice.auth.v1.ConvertGuestResponse
	(*DeleteAccountResponse)(nil),       // 21: voice.auth.v1.DeleteAccountResponse
	(*RestoreAccountResponse)(nil),      // 22: voice.auth.v1.RestoreAccountResponse
	(*ValidateTokenResponse)(nil),       // 23: voice.auth.v1.ValidateTokenResponse
	(*GetJWKSRequest)(nil),              // 24: voice.auth.v1.GetJWKSRequest
	(*GetJWKSResponse)(nil),             // 25: voice.auth.v1.GetJWKSResponse
	(*TokenClaims)(nil),                 // 26: voice.auth.v1.TokenClaims
	(*SwitchActiveProfileRequest)(nil),  // 27: voice.auth.v1.SwitchActiveProfileRequest
	(*SwitchActiveProfileResponse)(nil), // 28: voice.auth.v1.SwitchActiveProfileResponse
	(*SetAccountStatusRequest)(nil),     // 29: voice.auth.v1.SetAccountStatusRequest
	(*SetAccountStatusResponse)(nil),    // 30: voice.auth.v1.SetAccountStatusResponse
	(*timestamppb.Timestamp)(nil),       // 31: google.protobuf.Timestamp
}
var file_voice_auth_v1_auth_proto_depIdxs = []int32{
	0,  // 0: voice.auth.v1.VerifyOTPRequest.otp_type_enum:type_name -> voice.auth.v1.OtpType
	13, // 1: voice.auth.v1.RegisterResponse.session:type_name -> voice.auth.v1.AuthSession
	13, // 2: voice.auth.v1.LoginResponse.session:type_name -> voice.auth.v1.AuthSession
	13, // 3: voice.auth.v1.RefreshTokenResponse.session:type_name -> voice.auth.v1.AuthSession
	13, // 4: voice.auth.v1.Verify2FAResponse.session:type_name -> voice.auth.v1.AuthSession
	13, // 5: voice.auth.v1.ConvertGuestResponse.session:type_name -> voice.auth.v1.AuthSession
	13, // 6: voice.auth.v1.RestoreAccountResponse.session:type_name -> voice.auth.v1.AuthSession
	26, // 7: voice.auth.v1.ValidateTokenResponse.claims:type_name -> voice.auth.v1.TokenClaims
	31, // 8: voice.auth.v1.TokenClaims.expires_at:type_name -> google.protobuf.Timestamp
	13, // 9: voice.auth.v1.SwitchActiveProfileResponse.session:type_name -> voice.auth.v1.AuthSession
	1,  // 10: voice.auth.v1.AuthService.Register:input_type -> voice.auth.v1.RegisterRequest
	2,  // 11: voice.auth.v1.AuthService.Login:input_type -> voice.auth.v1.LoginRequest
	3,  // 12: voice.auth.v1.AuthService.Logout:input_type -> voice.auth.v1.LogoutRequest
	4,  // 13: voice.auth.v1.AuthService.RefreshToken:input_type -> voice.auth.v1.RefreshTokenRequest
	5,  // 14: voice.auth.v1.AuthService.Enable2FA:input_type -> voice.auth.v1.Enable2FARequest
	7,  // 15: voice.auth.v1.AuthService.Verify2FA:input_type -> voice.auth.v1.Verify2FARequest
	8,  // 16: voice.auth.v1.AuthService.VerifyOTP:input_type -> voice.auth.v1.VerifyOTPRequest
	9,  // 17: voice.auth.v1.AuthService.ConvertGuest:input_type -> voice.auth.v1.ConvertGuestRequest
	10, // 18: voice.auth.v1.AuthService.DeleteAccount:input_type -> voice.auth.v1.DeleteAccountRequest
	11, // 19: voice.auth.v1.AuthService.RestoreAccount:input_type -> voice.auth.v1.RestoreAccountRequest
	12, // 20: voice.auth.v1.AuthService.ValidateToken:input_type -> voice.auth.v1.ValidateTokenRequest
	24, // 21: voice.auth.v1.AuthService.GetJWKS:input_type -> voice.auth.v1.GetJWKSRequest
	27, // 22: voice.auth.v1.AuthService.SwitchActiveProfile:input_type -> voice.auth.v1.SwitchActiveProfileRequest
	29, // 23: voice.auth.v1.AuthService.SetAccountStatus:input_type -> voice.auth.v1.SetAccountStatusRequest
	14, // 24: voice.auth.v1.AuthService.Register:output_type -> voice.auth.v1.RegisterResponse
	15, // 25: voice.auth.v1.AuthService.Login:output_type -> voice.auth.v1.LoginResponse
	16, // 26: voice.auth.v1.AuthService.Logout:output_type -> voice.auth.v1.LogoutResponse
	17, // 27: voice.auth.v1.AuthService.RefreshToken:output_type -> voice.auth.v1.RefreshTokenResponse
	6,  // 28: voice.auth.v1.AuthService.Enable2FA:output_type -> voice.auth.v1.Enable2FAResponse
	18, // 29: voice.auth.v1.AuthService.Verify2FA:output_type -> voice.auth.v1.Verify2FAResponse
	19, // 30: voice.auth.v1.AuthService.VerifyOTP:output_type -> voice.auth.v1.VerifyOTPResponse
	20, // 31: voice.auth.v1.AuthService.ConvertGuest:output_type -> voice.auth.v1.ConvertGuestResponse
	21, // 32: voice.auth.v1.AuthService.DeleteAccount:output_type -> voice.auth.v1.DeleteAccountResponse
	22, // 33: voice.auth.v1.AuthService.RestoreAccount:output_type -> voice.auth.v1.RestoreAccountResponse
	23, // 34: voice.auth.v1.AuthService.ValidateToken:output_type -> voice.auth.v1.ValidateTokenResponse
	25, // 35: voice.auth.v1.AuthService.GetJWKS:output_type -> voice.auth.v1.GetJWKSResponse
	28, // 36: voice.auth.v1.AuthService.SwitchActiveProfile:output_type -> voice.auth.v1.SwitchActiveProfileResponse
	30, // 37: voice.auth.v1.AuthService.SetAccountStatus:output_type -> voice.auth.v1.SetAccountStatusResponse
	24, // [24:38] is the sub-list for method output_type
	10, // [10:24] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_voice_auth_v1_auth_proto_init() }
func file_voice_auth_v1_auth_proto_init() {
	if File_voice_auth_v1_auth_proto != nil {
		return
	}
	file_voice_auth_v1_auth_proto_msgTypes[0].OneofWrappers = []any{}
	file_voice_auth_v1_auth_proto_msgTypes[1].OneofWrappers = []any{}
	file_voice_auth_v1_auth_proto_msgTypes[7].OneofWrappers = []any{}
	file_voice_auth_v1_auth_proto_msgTypes[8].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_voice_auth_v1_auth_proto_rawDesc), len(file_voice_auth_v1_auth_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   30,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_voice_auth_v1_auth_proto_goTypes,
		DependencyIndexes: file_voice_auth_v1_auth_proto_depIdxs,
		EnumInfos:         file_voice_auth_v1_auth_proto_enumTypes,
		MessageInfos:      file_voice_auth_v1_auth_proto_msgTypes,
	}.Build()
	File_voice_auth_v1_auth_proto = out.File
	file_voice_auth_v1_auth_proto_goTypes = nil
	file_voice_auth_v1_auth_proto_depIdxs = nil
}
