// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: voice/file/v1/file.proto

package filev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FileService_RequestUpload_FullMethodName                          = "/voice.file.v1.FileService/RequestUpload"
	FileService_ConfirmUpload_FullMethodName                          = "/voice.file.v1.FileService/ConfirmUpload"
	FileService_GetFileURL_FullMethodName                             = "/voice.file.v1.FileService/GetFileURL"
	FileService_GetFileMetadata_FullMethodName                        = "/voice.file.v1.FileService/GetFileMetadata"
	FileService_GetBulkMetadata_FullMethodName                        = "/voice.file.v1.FileService/GetBulkMetadata"
	FileService_DeleteFile_FullMethodName                             = "/voice.file.v1.FileService/DeleteFile"
	FileService_ListFiles_FullMethodName                              = "/voice.file.v1.FileService/ListFiles"
	FileService_CheckQuota_FullMethodName                             = "/voice.file.v1.FileService/CheckQuota"
	FileService_IssueFileAccessCapability_FullMethodName              = "/voice.file.v1.FileService/IssueFileAccessCapability"
	FileService_PrepareSpaceDeletionReferenceManifest_FullMethodName  = "/voice.file.v1.FileService/PrepareSpaceDeletionReferenceManifest"
	FileService_RegisterSpaceDeletionReferenceChunk_FullMethodName    = "/voice.file.v1.FileService/RegisterSpaceDeletionReferenceChunk"
	FileService_ReleaseSpaceDeletionProducerReferences_FullMethodName = "/voice.file.v1.FileService/ReleaseSpaceDeletionProducerReferences"
	FileService_ApplySpaceLifecycleFence_FullMethodName               = "/voice.file.v1.FileService/ApplySpaceLifecycleFence"
	FileService_PurgeSpace_FullMethodName                             = "/voice.file.v1.FileService/PurgeSpace"
	FileService_AcquireFileReferences_FullMethodName                  = "/voice.file.v1.FileService/AcquireFileReferences"
	FileService_ReleaseFileReferences_FullMethodName                  = "/voice.file.v1.FileService/ReleaseFileReferences"
	FileService_GetSpacePurgeReceipt_FullMethodName                   = "/voice.file.v1.FileService/GetSpacePurgeReceipt"
)

// FileServiceClient is the client API for FileService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Uploads, R2, scanning. HTTP: /api/v1/files/**.
type FileServiceClient interface {
	RequestUpload(ctx context.Context, in *RequestUploadRequest, opts ...grpc.CallOption) (*RequestUploadResponse, error)
	ConfirmUpload(ctx context.Context, in *ConfirmUploadRequest, opts ...grpc.CallOption) (*ConfirmUploadResponse, error)
	// @voice.security=public_gateway;callers=service:gateway
	GetFileURL(ctx context.Context, in *GetFileURLRequest, opts ...grpc.CallOption) (*GetFileURLResponse, error)
	// @voice.security=public_gateway;callers=service:gateway
	GetFileMetadata(ctx context.Context, in *GetFileMetadataRequest, opts ...grpc.CallOption) (*GetFileMetadataResponse, error)
	// @voice.security=public_gateway;callers=service:gateway
	GetBulkMetadata(ctx context.Context, in *GetBulkMetadataRequest, opts ...grpc.CallOption) (*GetBulkMetadataResponse, error)
	DeleteFile(ctx context.Context, in *DeleteFileRequest, opts ...grpc.CallOption) (*DeleteFileResponse, error)
	ListFiles(ctx context.Context, in *ListFilesRequest, opts ...grpc.CallOption) (*ListFilesResponse, error)
	CheckQuota(ctx context.Context, in *CheckQuotaRequest, opts ...grpc.CallOption) (*CheckQuotaResponse, error)
	// @voice.security=protected;callers=service:messaging,service:chat,service:story,service:user
	IssueFileAccessCapability(ctx context.Context, in *IssueFileAccessCapabilityRequest, opts ...grpc.CallOption) (*IssueFileAccessCapabilityResponse, error)
	// @voice.security=protected;callers=service:space
	PrepareSpaceDeletionReferenceManifest(ctx context.Context, in *PrepareSpaceDeletionReferenceManifestRequest, opts ...grpc.CallOption) (*PrepareSpaceDeletionReferenceManifestResponse, error)
	// @voice.security=protected;callers=service:space,service:chat,service:messaging
	RegisterSpaceDeletionReferenceChunk(ctx context.Context, in *RegisterSpaceDeletionReferenceChunkRequest, opts ...grpc.CallOption) (*RegisterSpaceDeletionReferenceChunkResponse, error)
	// @voice.security=protected;callers=service:space,service:chat,service:messaging
	ReleaseSpaceDeletionProducerReferences(ctx context.Context, in *ReleaseSpaceDeletionProducerReferencesRequest, opts ...grpc.CallOption) (*ReleaseSpaceDeletionProducerReferencesResponse, error)
	// @voice.security=protected;callers=service:space
	ApplySpaceLifecycleFence(ctx context.Context, in *ApplySpaceLifecycleFenceRequest, opts ...grpc.CallOption) (*ApplySpaceLifecycleFenceResponse, error)
	// @voice.security=protected;callers=service:space
	PurgeSpace(ctx context.Context, in *PurgeSpaceRequest, opts ...grpc.CallOption) (*PurgeSpaceResponse, error)
	// @voice.security=protected;callers=service:space,service:chat,service:messaging
	AcquireFileReferences(ctx context.Context, in *AcquireFileReferencesRequest, opts ...grpc.CallOption) (*AcquireFileReferencesResponse, error)
	// @voice.security=protected;callers=service:space,service:chat,service:messaging
	ReleaseFileReferences(ctx context.Context, in *ReleaseFileReferencesRequest, opts ...grpc.CallOption) (*ReleaseFileReferencesResponse, error)
	// @voice.security=protected;callers=service:space
	GetSpacePurgeReceipt(ctx context.Context, in *GetSpacePurgeReceiptRequest, opts ...grpc.CallOption) (*GetSpacePurgeReceiptResponse, error)
}

type fileServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFileServiceClient(cc grpc.ClientConnInterface) FileServiceClient {
	return &fileServiceClient{cc}
}

func (c *fileServiceClient) RequestUpload(ctx context.Context, in *RequestUploadRequest, opts ...grpc.CallOption) (*RequestUploadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RequestUploadResponse)
	err := c.cc.Invoke(ctx, FileService_RequestUpload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileServiceClient) ConfirmUpload(ctx context.Context, in *ConfirmUploadRequest, opts ...grpc.CallOption) (*ConfirmUploadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfirmUploadResponse)
	err := c.cc.Invoke(ctx, FileService_ConfirmUpload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileServiceClient) GetFileURL(ctx context.Context, in *GetFileURLRequest, opts ...grpc.CallOption) (*GetFileURLResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFileURLResponse)
	err := c.cc.Invoke(ctx, FileService_GetFileURL_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileServiceClient) GetFileMetadata(ctx context.Context, in *GetFileMetadataRequest, opts ...grpc.CallOption) (*GetFileMetadataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFileMetadataResponse)
	err := c.cc.Invoke(ctx, FileService_GetFileMetadata_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileServiceClient) GetBulkMetadata(ctx context.Context, in *GetBulkMetadataRequest, opts ...grpc.CallOption) (*GetBulkMetadataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBulkMetadataResponse)
	err := c.cc.Invoke(ctx, FileService_GetBulkMetadata_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileServiceClient) DeleteFile(ctx context.Context, in *DeleteFileRequest, opts ...grpc.CallOption) (*DeleteFileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteFileResponse)
	err := c.cc.Invoke(ctx, FileService_DeleteFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileServiceClient) ListFiles(ctx context.Context, in *ListFilesRequest, opts ...grpc.CallOption) (*ListFilesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListFilesResponse)
	err := c.cc.Invoke(ctx, FileService_ListFiles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileServiceClient) CheckQuota(ctx context.Context, in *CheckQuotaRequest, opts ...grpc.CallOption) (*CheckQuotaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckQuotaResponse)
	err := c.cc.Invoke(ctx, FileService_CheckQuota_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileServiceClient) IssueFileAccessCapability(ctx context.Context, in *IssueFileAccessCapabilityRequest, opts ...grpc.CallOption) (*IssueFileAccessCapabilityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IssueFileAccessCapabilityResponse)
	err := c.cc.Invoke(ctx, FileService_IssueFileAccessCapability_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileServiceClient) PrepareSpaceDeletionReferenceManifest(ctx context.Context, in *PrepareSpaceDeletionReferenceManifestRequest, opts ...grpc.CallOption) (*PrepareSpaceDeletionReferenceManifestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PrepareSpaceDeletionReferenceManifestResponse)
	err := c.cc.Invoke(ctx, FileService_PrepareSpaceDeletionReferenceManifest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileServiceClient) RegisterSpaceDeletionReferenceChunk(ctx context.Context, in *RegisterSpaceDeletionReferenceChunkRequest, opts ...grpc.CallOption) (*RegisterSpaceDeletionReferenceChunkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterSpaceDeletionReferenceChunkResponse)
	err := c.cc.Invoke(ctx, FileService_RegisterSpaceDeletionReferenceChunk_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileServiceClient) ReleaseSpaceDeletionProducerReferences(ctx context.Context, in *ReleaseSpaceDeletionProducerReferencesRequest, opts ...grpc.CallOption) (*ReleaseSpaceDeletionProducerReferencesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReleaseSpaceDeletionProducerReferencesResponse)
	err := c.cc.Invoke(ctx, FileService_ReleaseSpaceDeletionProducerReferences_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileServiceClient) ApplySpaceLifecycleFence(ctx context.Context, in *ApplySpaceLifecycleFenceRequest, opts ...grpc.CallOption) (*ApplySpaceLifecycleFenceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplySpaceLifecycleFenceResponse)
	err := c.cc.Invoke(ctx, FileService_ApplySpaceLifecycleFence_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileServiceClient) PurgeSpace(ctx context.Context, in *PurgeSpaceRequest, opts ...grpc.CallOption) (*PurgeSpaceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PurgeSpaceResponse)
	err := c.cc.Invoke(ctx, FileService_PurgeSpace_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileServiceClient) AcquireFileReferences(ctx context.Context, in *AcquireFileReferencesRequest, opts ...grpc.CallOption) (*AcquireFileReferencesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AcquireFileReferencesResponse)
	err := c.cc.Invoke(ctx, FileService_AcquireFileReferences_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileServiceClient) ReleaseFileReferences(ctx context.Context, in *ReleaseFileReferencesRequest, opts ...grpc.CallOption) (*ReleaseFileReferencesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReleaseFileReferencesResponse)
	err := c.cc.Invoke(ctx, FileService_ReleaseFileReferences_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileServiceClient) GetSpacePurgeReceipt(ctx context.Context, in *GetSpacePurgeReceiptRequest, opts ...grpc.CallOption) (*GetSpacePurgeReceiptResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSpacePurgeReceiptResponse)
	err := c.cc.Invoke(ctx, FileService_GetSpacePurgeReceipt_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FileServiceServer is the server API for FileService service.
// All implementations must embed UnimplementedFileServiceServer
// for forward compatibility.
//
// Uploads, R2, scanning. HTTP: /api/v1/files/**.
type FileServiceServer interface {
	RequestUpload(context.Context, *RequestUploadRequest) (*RequestUploadResponse, error)
	ConfirmUpload(context.Context, *ConfirmUploadRequest) (*ConfirmUploadResponse, error)
	// @voice.security=public_gateway;callers=service:gateway
	GetFileURL(context.Context, *GetFileURLRequest) (*GetFileURLResponse, error)
	// @voice.security=public_gateway;callers=service:gateway
	GetFileMetadata(context.Context, *GetFileMetadataRequest) (*GetFileMetadataResponse, error)
	// @voice.security=public_gateway;callers=service:gateway
	GetBulkMetadata(context.Context, *GetBulkMetadataRequest) (*GetBulkMetadataResponse, error)
	DeleteFile(context.Context, *DeleteFileRequest) (*DeleteFileResponse, error)
	ListFiles(context.Context, *ListFilesRequest) (*ListFilesResponse, error)
	CheckQuota(context.Context, *CheckQuotaRequest) (*CheckQuotaResponse, error)
	// @voice.security=protected;callers=service:messaging,service:chat,service:story,service:user
	IssueFileAccessCapability(context.Context, *IssueFileAccessCapabilityRequest) (*IssueFileAccessCapabilityResponse, error)
	// @voice.security=protected;callers=service:space
	PrepareSpaceDeletionReferenceManifest(context.Context, *PrepareSpaceDeletionReferenceManifestRequest) (*PrepareSpaceDeletionReferenceManifestResponse, error)
	// @voice.security=protected;callers=service:space,service:chat,service:messaging
	RegisterSpaceDeletionReferenceChunk(context.Context, *RegisterSpaceDeletionReferenceChunkRequest) (*RegisterSpaceDeletionReferenceChunkResponse, error)
	// @voice.security=protected;callers=service:space,service:chat,service:messaging
	ReleaseSpaceDeletionProducerReferences(context.Context, *ReleaseSpaceDeletionProducerReferencesRequest) (*ReleaseSpaceDeletionProducerReferencesResponse, error)
	// @voice.security=protected;callers=service:space
	ApplySpaceLifecycleFence(context.Context, *ApplySpaceLifecycleFenceRequest) (*ApplySpaceLifecycleFenceResponse, error)
	// @voice.security=protected;callers=service:space
	PurgeSpace(context.Context, *PurgeSpaceRequest) (*PurgeSpaceResponse, error)
	// @voice.security=protected;callers=service:space,service:chat,service:messaging
	AcquireFileReferences(context.Context, *AcquireFileReferencesRequest) (*AcquireFileReferencesResponse, error)
	// @voice.security=protected;callers=service:space,service:chat,service:messaging
	ReleaseFileReferences(context.Context, *ReleaseFileReferencesRequest) (*ReleaseFileReferencesResponse, error)
	// @voice.security=protected;callers=service:space
	GetSpacePurgeReceipt(context.Context, *GetSpacePurgeReceiptRequest) (*GetSpacePurgeReceiptResponse, error)
	mustEmbedUnimplementedFileServiceServer()
}

// UnimplementedFileServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFileServiceServer struct{}

func (UnimplementedFileServiceServer) RequestUpload(context.Context, *RequestUploadRequest) (*RequestUploadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestUpload not implemented")
}
func (UnimplementedFileServiceServer) ConfirmUpload(context.Context, *ConfirmUploadRequest) (*ConfirmUploadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConfirmUpload not implemented")
}
func (UnimplementedFileServiceServer) GetFileURL(context.Context, *GetFileURLRequest) (*GetFileURLResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFileURL not implemented")
}
func (UnimplementedFileServiceServer) GetFileMetadata(context.Context, *GetFileMetadataRequest) (*GetFileMetadataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFileMetadata not implemented")
}
func (UnimplementedFileServiceServer) GetBulkMetadata(context.Context, *GetBulkMetadataRequest) (*GetBulkMetadataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBulkMetadata not implemented")
}
func (UnimplementedFileServiceServer) DeleteFile(context.Context, *DeleteFileRequest) (*DeleteFileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteFile not implemented")
}
func (UnimplementedFileServiceServer) ListFiles(context.Context, *ListFilesRequest) (*ListFilesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListFiles not implemented")
}
func (UnimplementedFileServiceServer) CheckQuota(context.Context, *CheckQuotaRequest) (*CheckQuotaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckQuota not implemented")
}
func (UnimplementedFileServiceServer) IssueFileAccessCapability(context.Context, *IssueFileAccessCapabilityRequest) (*IssueFileAccessCapabilityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IssueFileAccessCapability not implemented")
}
func (UnimplementedFileServiceServer) PrepareSpaceDeletionReferenceManifest(context.Context, *PrepareSpaceDeletionReferenceManifestRequest) (*PrepareSpaceDeletionReferenceManifestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PrepareSpaceDeletionReferenceManifest not implemented")
}
func (UnimplementedFileServiceServer) RegisterSpaceDeletionReferenceChunk(context.Context, *RegisterSpaceDeletionReferenceChunkRequest) (*RegisterSpaceDeletionReferenceChunkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterSpaceDeletionReferenceChunk not implemented")
}
func (UnimplementedFileServiceServer) ReleaseSpaceDeletionProducerReferences(context.Context, *ReleaseSpaceDeletionProducerReferencesRequest) (*ReleaseSpaceDeletionProducerReferencesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReleaseSpaceDeletionProducerReferences not implemented")
}
func (UnimplementedFileServiceServer) ApplySpaceLifecycleFence(context.Context, *ApplySpaceLifecycleFenceRequest) (*ApplySpaceLifecycleFenceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApplySpaceLifecycleFence not implemented")
}
func (UnimplementedFileServiceServer) PurgeSpace(context.Context, *PurgeSpaceRequest) (*PurgeSpaceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PurgeSpace not implemented")
}
func (UnimplementedFileServiceServer) AcquireFileReferences(context.Context, *AcquireFileReferencesRequest) (*AcquireFileReferencesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AcquireFileReferences not implemented")
}
func (UnimplementedFileServiceServer) ReleaseFileReferences(context.Context, *ReleaseFileReferencesRequest) (*ReleaseFileReferencesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReleaseFileReferences not implemented")
}
func (UnimplementedFileServiceServer) GetSpacePurgeReceipt(context.Context, *GetSpacePurgeReceiptRequest) (*GetSpacePurgeReceiptResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSpacePurgeReceipt not implemented")
}
func (UnimplementedFileServiceServer) mustEmbedUnimplementedFileServiceServer() {}
func (UnimplementedFileServiceServer) testEmbeddedByValue()                     {}

// UnsafeFileServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FileServiceServer will
// result in compilation errors.
type UnsafeFileServiceServer interface {
	mustEmbedUnimplementedFileServiceServer()
}

func RegisterFileServiceServer(s grpc.ServiceRegistrar, srv FileServiceServer) {
	// If the following call pancis, it indicates UnimplementedFileServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FileService_ServiceDesc, srv)
}

func _FileService_RequestUpload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestUploadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).RequestUpload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileService_RequestUpload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).RequestUpload(ctx, req.(*RequestUploadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileService_ConfirmUpload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfirmUploadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).ConfirmUpload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileService_ConfirmUpload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).ConfirmUpload(ctx, req.(*ConfirmUploadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileService_GetFileURL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFileURLRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).GetFileURL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileService_GetFileURL_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).GetFileURL(ctx, req.(*GetFileURLRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileService_GetFileMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFileMetadataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).GetFileMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileService_GetFileMetadata_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).GetFileMetadata(ctx, req.(*GetFileMetadataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileService_GetBulkMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBulkMetadataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).GetBulkMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileService_GetBulkMetadata_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).GetBulkMetadata(ctx, req.(*GetBulkMetadataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileService_DeleteFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).DeleteFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileService_DeleteFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).DeleteFile(ctx, req.(*DeleteFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileService_ListFiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFilesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).ListFiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileService_ListFiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).ListFiles(ctx, req.(*ListFilesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileService_CheckQuota_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckQuotaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).CheckQuota(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileService_CheckQuota_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).CheckQuota(ctx, req.(*CheckQuotaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileService_IssueFileAccessCapability_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IssueFileAccessCapabilityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).IssueFileAccessCapability(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileService_IssueFileAccessCapability_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).IssueFileAccessCapability(ctx, req.(*IssueFileAccessCapabilityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileService_PrepareSpaceDeletionReferenceManifest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrepareSpaceDeletionReferenceManifestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).PrepareSpaceDeletionReferenceManifest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileService_PrepareSpaceDeletionReferenceManifest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).PrepareSpaceDeletionReferenceManifest(ctx, req.(*PrepareSpaceDeletionReferenceManifestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileService_RegisterSpaceDeletionReferenceChunk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterSpaceDeletionReferenceChunkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).RegisterSpaceDeletionReferenceChunk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileService_RegisterSpaceDeletionReferenceChunk_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).RegisterSpaceDeletionReferenceChunk(ctx, req.(*RegisterSpaceDeletionReferenceChunkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileService_ReleaseSpaceDeletionProducerReferences_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReleaseSpaceDeletionProducerReferencesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).ReleaseSpaceDeletionProducerReferences(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileService_ReleaseSpaceDeletionProducerReferences_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).ReleaseSpaceDeletionProducerReferences(ctx, req.(*ReleaseSpaceDeletionProducerReferencesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileService_ApplySpaceLifecycleFence_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplySpaceLifecycleFenceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).ApplySpaceLifecycleFence(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileService_ApplySpaceLifecycleFence_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).ApplySpaceLifecycleFence(ctx, req.(*ApplySpaceLifecycleFenceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileService_PurgeSpace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PurgeSpaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).PurgeSpace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileService_PurgeSpace_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).PurgeSpace(ctx, req.(*PurgeSpaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileService_AcquireFileReferences_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcquireFileReferencesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).AcquireFileReferences(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileService_AcquireFileReferences_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).AcquireFileReferences(ctx, req.(*AcquireFileReferencesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileService_ReleaseFileReferences_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReleaseFileReferencesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).ReleaseFileReferences(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileService_ReleaseFileReferences_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).ReleaseFileReferences(ctx, req.(*ReleaseFileReferencesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileService_GetSpacePurgeReceipt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSpacePurgeReceiptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).GetSpacePurgeReceipt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileService_GetSpacePurgeReceipt_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).GetSpacePurgeReceipt(ctx, req.(*GetSpacePurgeReceiptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FileService_ServiceDesc is the grpc.ServiceDesc for FileService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FileService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "voice.file.v1.FileService",
	HandlerType: (*FileServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RequestUpload",
			Handler:    _FileService_RequestUpload_Handler,
		},
		{
			MethodName: "ConfirmUpload",
			Handler:    _FileService_ConfirmUpload_Handler,
		},
		{
			MethodName: "GetFileURL",
			Handler:    _FileService_GetFileURL_Handler,
		},
		{
			MethodName: "GetFileMetadata",
			Handler:    _FileService_GetFileMetadata_Handler,
		},
		{
			MethodName: "GetBulkMetadata",
			Handler:    _FileService_GetBulkMetadata_Handler,
		},
		{
			MethodName: "DeleteFile",
			Handler:    _FileService_DeleteFile_Handler,
		},
		{
			MethodName: "ListFiles",
			Handler:    _FileService_ListFiles_Handler,
		},
		{
			MethodName: "CheckQuota",
			Handler:    _FileService_CheckQuota_Handler,
		},
		{
			MethodName: "IssueFileAccessCapability",
			Handler:    _FileService_IssueFileAccessCapability_Handler,
		},
		{
			MethodName: "PrepareSpaceDeletionReferenceManifest",
			Handler:    _FileService_PrepareSpaceDeletionReferenceManifest_Handler,
		},
		{
			MethodName: "RegisterSpaceDeletionReferenceChunk",
			Handler:    _FileService_RegisterSpaceDeletionReferenceChunk_Handler,
		},
		{
			MethodName: "ReleaseSpaceDeletionProducerReferences",
			Handler:    _FileService_ReleaseSpaceDeletionProducerReferences_Handler,
		},
		{
			MethodName: "ApplySpaceLifecycleFence",
			Handler:    _FileService_ApplySpaceLifecycleFence_Handler,
		},
		{
			MethodName: "PurgeSpace",
			Handler:    _FileService_PurgeSpace_Handler,
		},
		{
			MethodName: "AcquireFileReferences",
			Handler:    _FileService_AcquireFileReferences_Handler,
		},
		{
			MethodName: "ReleaseFileReferences",
			Handler:    _FileService_ReleaseFileReferences_Handler,
		},
		{
			MethodName: "GetSpacePurgeReceipt",
			Handler:    _FileService_GetSpacePurgeReceipt_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "voice/file/v1/file.proto",
}
