// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: voice/social/v1/social.proto

package socialv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SocialService_SendFriendInvitation_FullMethodName    = "/voice.social.v1.SocialService/SendFriendInvitation"
	SocialService_AcceptFriendInvitation_FullMethodName  = "/voice.social.v1.SocialService/AcceptFriendInvitation"
	SocialService_DeclineFriendInvitation_FullMethodName = "/voice.social.v1.SocialService/DeclineFriendInvitation"
	SocialService_RemoveFriend_FullMethodName            = "/voice.social.v1.SocialService/RemoveFriend"
	SocialService_ListFriends_FullMethodName             = "/voice.social.v1.SocialService/ListFriends"
	SocialService_ListFriendRequests_FullMethodName      = "/voice.social.v1.SocialService/ListFriendRequests"
	SocialService_AddContact_FullMethodName              = "/voice.social.v1.SocialService/AddContact"
	SocialService_RemoveContact_FullMethodName           = "/voice.social.v1.SocialService/RemoveContact"
	SocialService_ListContacts_FullMethodName            = "/voice.social.v1.SocialService/ListContacts"
	SocialService_SyncPhoneContacts_FullMethodName       = "/voice.social.v1.SocialService/SyncPhoneContacts"
	SocialService_SetFavorite_FullMethodName             = "/voice.social.v1.SocialService/SetFavorite"
	SocialService_ListFavorites_FullMethodName           = "/voice.social.v1.SocialService/ListFavorites"
	SocialService_BlockAccount_FullMethodName            = "/voice.social.v1.SocialService/BlockAccount"
	SocialService_UnblockAccount_FullMethodName          = "/voice.social.v1.SocialService/UnblockAccount"
	SocialService_ListBlocked_FullMethodName             = "/voice.social.v1.SocialService/ListBlocked"
	SocialService_IsBlocked_FullMethodName               = "/voice.social.v1.SocialService/IsBlocked"
	SocialService_AreFriends_FullMethodName              = "/voice.social.v1.SocialService/AreFriends"
	SocialService_GetFriendsOfFriends_FullMethodName     = "/voice.social.v1.SocialService/GetFriendsOfFriends"
)

// SocialServiceClient is the client API for SocialService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Social graph — friends, contacts, blocks. HTTP: /api/v1/friends/**.
type SocialServiceClient interface {
	SendFriendInvitation(ctx context.Context, in *SendFriendInvitationRequest, opts ...grpc.CallOption) (*SendFriendInvitationResponse, error)
	AcceptFriendInvitation(ctx context.Context, in *AcceptFriendInvitationRequest, opts ...grpc.CallOption) (*AcceptFriendInvitationResponse, error)
	DeclineFriendInvitation(ctx context.Context, in *DeclineFriendInvitationRequest, opts ...grpc.CallOption) (*DeclineFriendInvitationResponse, error)
	RemoveFriend(ctx context.Context, in *RemoveFriendRequest, opts ...grpc.CallOption) (*RemoveFriendResponse, error)
	ListFriends(ctx context.Context, in *ListFriendsRequest, opts ...grpc.CallOption) (*ListFriendsResponse, error)
	ListFriendRequests(ctx context.Context, in *ListFriendRequestsRequest, opts ...grpc.CallOption) (*ListFriendRequestsResponse, error)
	AddContact(ctx context.Context, in *AddContactRequest, opts ...grpc.CallOption) (*AddContactResponse, error)
	RemoveContact(ctx context.Context, in *RemoveContactRequest, opts ...grpc.CallOption) (*RemoveContactResponse, error)
	ListContacts(ctx context.Context, in *ListContactsRequest, opts ...grpc.CallOption) (*ListContactsResponse, error)
	SyncPhoneContacts(ctx context.Context, in *SyncPhoneContactsRequest, opts ...grpc.CallOption) (*SyncPhoneContactsResponse, error)
	SetFavorite(ctx context.Context, in *SetFavoriteRequest, opts ...grpc.CallOption) (*SetFavoriteResponse, error)
	ListFavorites(ctx context.Context, in *ListFavoritesRequest, opts ...grpc.CallOption) (*ListFavoritesResponse, error)
	BlockAccount(ctx context.Context, in *BlockAccountRequest, opts ...grpc.CallOption) (*BlockAccountResponse, error)
	UnblockAccount(ctx context.Context, in *UnblockAccountRequest, opts ...grpc.CallOption) (*UnblockAccountResponse, error)
	ListBlocked(ctx context.Context, in *ListBlockedRequest, opts ...grpc.CallOption) (*ListBlockedResponse, error)
	IsBlocked(ctx context.Context, in *IsBlockedRequest, opts ...grpc.CallOption) (*IsBlockedResponse, error)
	AreFriends(ctx context.Context, in *AreFriendsRequest, opts ...grpc.CallOption) (*AreFriendsResponse, error)
	GetFriendsOfFriends(ctx context.Context, in *GetFriendsOfFriendsRequest, opts ...grpc.CallOption) (*GetFriendsOfFriendsResponse, error)
}

type socialServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSocialServiceClient(cc grpc.ClientConnInterface) SocialServiceClient {
	return &socialServiceClient{cc}
}

func (c *socialServiceClient) SendFriendInvitation(ctx context.Context, in *SendFriendInvitationRequest, opts ...grpc.CallOption) (*SendFriendInvitationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendFriendInvitationResponse)
	err := c.cc.Invoke(ctx, SocialService_SendFriendInvitation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialServiceClient) AcceptFriendInvitation(ctx context.Context, in *AcceptFriendInvitationRequest, opts ...grpc.CallOption) (*AcceptFriendInvitationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AcceptFriendInvitationResponse)
	err := c.cc.Invoke(ctx, SocialService_AcceptFriendInvitation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialServiceClient) DeclineFriendInvitation(ctx context.Context, in *DeclineFriendInvitationRequest, opts ...grpc.CallOption) (*DeclineFriendInvitationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeclineFriendInvitationResponse)
	err := c.cc.Invoke(ctx, SocialService_DeclineFriendInvitation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialServiceClient) RemoveFriend(ctx context.Context, in *RemoveFriendRequest, opts ...grpc.CallOption) (*RemoveFriendResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveFriendResponse)
	err := c.cc.Invoke(ctx, SocialService_RemoveFriend_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialServiceClient) ListFriends(ctx context.Context, in *ListFriendsRequest, opts ...grpc.CallOption) (*ListFriendsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListFriendsResponse)
	err := c.cc.Invoke(ctx, SocialService_ListFriends_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialServiceClient) ListFriendRequests(ctx context.Context, in *ListFriendRequestsRequest, opts ...grpc.CallOption) (*ListFriendRequestsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListFriendRequestsResponse)
	err := c.cc.Invoke(ctx, SocialService_ListFriendRequests_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialServiceClient) AddContact(ctx context.Context, in *AddContactRequest, opts ...grpc.CallOption) (*AddContactResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddContactResponse)
	err := c.cc.Invoke(ctx, SocialService_AddContact_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialServiceClient) RemoveContact(ctx context.Context, in *RemoveContactRequest, opts ...grpc.CallOption) (*RemoveContactResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveContactResponse)
	err := c.cc.Invoke(ctx, SocialService_RemoveContact_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialServiceClient) ListContacts(ctx context.Context, in *ListContactsRequest, opts ...grpc.CallOption) (*ListContactsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListContactsResponse)
	err := c.cc.Invoke(ctx, SocialService_ListContacts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialServiceClient) SyncPhoneContacts(ctx context.Context, in *SyncPhoneContactsRequest, opts ...grpc.CallOption) (*SyncPhoneContactsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncPhoneContactsResponse)
	err := c.cc.Invoke(ctx, SocialService_SyncPhoneContacts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialServiceClient) SetFavorite(ctx context.Context, in *SetFavoriteRequest, opts ...grpc.CallOption) (*SetFavoriteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetFavoriteResponse)
	err := c.cc.Invoke(ctx, SocialService_SetFavorite_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialServiceClient) ListFavorites(ctx context.Context, in *ListFavoritesRequest, opts ...grpc.CallOption) (*ListFavoritesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListFavoritesResponse)
	err := c.cc.Invoke(ctx, SocialService_ListFavorites_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialServiceClient) BlockAccount(ctx context.Context, in *BlockAccountRequest, opts ...grpc.CallOption) (*BlockAccountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BlockAccountResponse)
	err := c.cc.Invoke(ctx, SocialService_BlockAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialServiceClient) UnblockAccount(ctx context.Context, in *UnblockAccountRequest, opts ...grpc.CallOption) (*UnblockAccountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnblockAccountResponse)
	err := c.cc.Invoke(ctx, SocialService_UnblockAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialServiceClient) ListBlocked(ctx context.Context, in *ListBlockedRequest, opts ...grpc.CallOption) (*ListBlockedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListBlockedResponse)
	err := c.cc.Invoke(ctx, SocialService_ListBlocked_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialServiceClient) IsBlocked(ctx context.Context, in *IsBlockedRequest, opts ...grpc.CallOption) (*IsBlockedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IsBlockedResponse)
	err := c.cc.Invoke(ctx, SocialService_IsBlocked_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialServiceClient) AreFriends(ctx context.Context, in *AreFriendsRequest, opts ...grpc.CallOption) (*AreFriendsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AreFriendsResponse)
	err := c.cc.Invoke(ctx, SocialService_AreFriends_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialServiceClient) GetFriendsOfFriends(ctx context.Context, in *GetFriendsOfFriendsRequest, opts ...grpc.CallOption) (*GetFriendsOfFriendsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFriendsOfFriendsResponse)
	err := c.cc.Invoke(ctx, SocialService_GetFriendsOfFriends_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SocialServiceServer is the server API for SocialService service.
// All implementations must embed UnimplementedSocialServiceServer
// for forward compatibility.
//
// Social graph — friends, contacts, blocks. HTTP: /api/v1/friends/**.
type SocialServiceServer interface {
	SendFriendInvitation(context.Context, *SendFriendInvitationRequest) (*SendFriendInvitationResponse, error)
	AcceptFriendInvitation(context.Context, *AcceptFriendInvitationRequest) (*AcceptFriendInvitationResponse, error)
	DeclineFriendInvitation(context.Context, *DeclineFriendInvitationRequest) (*DeclineFriendInvitationResponse, error)
	RemoveFriend(context.Context, *RemoveFriendRequest) (*RemoveFriendResponse, error)
	ListFriends(context.Context, *ListFriendsRequest) (*ListFriendsResponse, error)
	ListFriendRequests(context.Context, *ListFriendRequestsRequest) (*ListFriendRequestsResponse, error)
	AddContact(context.Context, *AddContactRequest) (*AddContactResponse, error)
	RemoveContact(context.Context, *RemoveContactRequest) (*RemoveContactResponse, error)
	ListContacts(context.Context, *ListContactsRequest) (*ListContactsResponse, error)
	SyncPhoneContacts(context.Context, *SyncPhoneContactsRequest) (*SyncPhoneContactsResponse, error)
	SetFavorite(context.Context, *SetFavoriteRequest) (*SetFavoriteResponse, error)
	ListFavorites(context.Context, *ListFavoritesRequest) (*ListFavoritesResponse, error)
	BlockAccount(context.Context, *BlockAccountRequest) (*BlockAccountResponse, error)
	UnblockAccount(context.Context, *UnblockAccountRequest) (*UnblockAccountResponse, error)
	ListBlocked(context.Context, *ListBlockedRequest) (*ListBlockedResponse, error)
	IsBlocked(context.Context, *IsBlockedRequest) (*IsBlockedResponse, error)
	AreFriends(context.Context, *AreFriendsRequest) (*AreFriendsResponse, error)
	GetFriendsOfFriends(context.Context, *GetFriendsOfFriendsRequest) (*GetFriendsOfFriendsResponse, error)
	mustEmbedUnimplementedSocialServiceServer()
}

// UnimplementedSocialServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSocialServiceServer struct{}

func (UnimplementedSocialServiceServer) SendFriendInvitation(context.Context, *SendFriendInvitationRequest) (*SendFriendInvitationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendFriendInvitation not implemented")
}
func (UnimplementedSocialServiceServer) AcceptFriendInvitation(context.Context, *AcceptFriendInvitationRequest) (*AcceptFriendInvitationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AcceptFriendInvitation not implemented")
}
func (UnimplementedSocialServiceServer) DeclineFriendInvitation(context.Context, *DeclineFriendInvitationRequest) (*DeclineFriendInvitationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeclineFriendInvitation not implemented")
}
func (UnimplementedSocialServiceServer) RemoveFriend(context.Context, *RemoveFriendRequest) (*RemoveFriendResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveFriend not implemented")
}
func (UnimplementedSocialServiceServer) ListFriends(context.Context, *ListFriendsRequest) (*ListFriendsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListFriends not implemented")
}
func (UnimplementedSocialServiceServer) ListFriendRequests(context.Context, *ListFriendRequestsRequest) (*ListFriendRequestsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListFriendRequests not implemented")
}
func (UnimplementedSocialServiceServer) AddContact(context.Context, *AddContactRequest) (*AddContactResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddContact not implemented")
}
func (UnimplementedSocialServiceServer) RemoveContact(context.Context, *RemoveContactRequest) (*RemoveContactResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveContact not implemented")
}
func (UnimplementedSocialServiceServer) ListContacts(context.Context, *ListContactsRequest) (*ListContactsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListContacts not implemented")
}
func (UnimplementedSocialServiceServer) SyncPhoneContacts(context.Context, *SyncPhoneContactsRequest) (*SyncPhoneContactsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SyncPhoneContacts not implemented")
}
func (UnimplementedSocialServiceServer) SetFavorite(context.Context, *SetFavoriteRequest) (*SetFavoriteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetFavorite not implemented")
}
func (UnimplementedSocialServiceServer) ListFavorites(context.Context, *ListFavoritesRequest) (*ListFavoritesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListFavorites not implemented")
}
func (UnimplementedSocialServiceServer) BlockAccount(context.Context, *BlockAccountRequest) (*BlockAccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BlockAccount not implemented")
}
func (UnimplementedSocialServiceServer) UnblockAccount(context.Context, *UnblockAccountRequest) (*UnblockAccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnblockAccount not implemented")
}
func (UnimplementedSocialServiceServer) ListBlocked(context.Context, *ListBlockedRequest) (*ListBlockedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListBlocked not implemented")
}
func (UnimplementedSocialServiceServer) IsBlocked(context.Context, *IsBlockedRequest) (*IsBlockedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsBlocked not implemented")
}
func (UnimplementedSocialServiceServer) AreFriends(context.Context, *AreFriendsRequest) (*AreFriendsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AreFriends not implemented")
}
func (UnimplementedSocialServiceServer) GetFriendsOfFriends(context.Context, *GetFriendsOfFriendsRequest) (*GetFriendsOfFriendsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFriendsOfFriends not implemented")
}
func (UnimplementedSocialServiceServer) mustEmbedUnimplementedSocialServiceServer() {}
func (UnimplementedSocialServiceServer) testEmbeddedByValue()                       {}

// UnsafeSocialServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SocialServiceServer will
// result in compilation errors.
type UnsafeSocialServiceServer interface {
	mustEmbedUnimplementedSocialServiceServer()
}

func RegisterSocialServiceServer(s grpc.ServiceRegistrar, srv SocialServiceServer) {
	// If the following call pancis, it indicates UnimplementedSocialServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SocialService_ServiceDesc, srv)
}

func _SocialService_SendFriendInvitation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendFriendInvitationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServiceServer).SendFriendInvitation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SocialService_SendFriendInvitation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServiceServer).SendFriendInvitation(ctx, req.(*SendFriendInvitationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SocialService_AcceptFriendInvitation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcceptFriendInvitationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServiceServer).AcceptFriendInvitation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SocialService_AcceptFriendInvitation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServiceServer).AcceptFriendInvitation(ctx, req.(*AcceptFriendInvitationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SocialService_DeclineFriendInvitation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeclineFriendInvitationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServiceServer).DeclineFriendInvitation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SocialService_DeclineFriendInvitation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServiceServer).DeclineFriendInvitation(ctx, req.(*DeclineFriendInvitationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SocialService_RemoveFriend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveFriendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServiceServer).RemoveFriend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SocialService_RemoveFriend_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServiceServer).RemoveFriend(ctx, req.(*RemoveFriendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SocialService_ListFriends_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFriendsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServiceServer).ListFriends(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SocialService_ListFriends_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServiceServer).ListFriends(ctx, req.(*ListFriendsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SocialService_ListFriendRequests_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFriendRequestsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServiceServer).ListFriendRequests(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SocialService_ListFriendRequests_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServiceServer).ListFriendRequests(ctx, req.(*ListFriendRequestsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SocialService_AddContact_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddContactRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServiceServer).AddContact(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SocialService_AddContact_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServiceServer).AddContact(ctx, req.(*AddContactRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SocialService_RemoveContact_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveContactRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServiceServer).RemoveContact(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SocialService_RemoveContact_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServiceServer).RemoveContact(ctx, req.(*RemoveContactRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SocialService_ListContacts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListContactsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServiceServer).ListContacts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SocialService_ListContacts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServiceServer).ListContacts(ctx, req.(*ListContactsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SocialService_SyncPhoneContacts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncPhoneContactsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServiceServer).SyncPhoneContacts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SocialService_SyncPhoneContacts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServiceServer).SyncPhoneContacts(ctx, req.(*SyncPhoneContactsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SocialService_SetFavorite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetFavoriteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServiceServer).SetFavorite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SocialService_SetFavorite_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServiceServer).SetFavorite(ctx, req.(*SetFavoriteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SocialService_ListFavorites_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFavoritesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServiceServer).ListFavorites(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SocialService_ListFavorites_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServiceServer).ListFavorites(ctx, req.(*ListFavoritesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SocialService_BlockAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BlockAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServiceServer).BlockAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SocialService_BlockAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServiceServer).BlockAccount(ctx, req.(*BlockAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SocialService_UnblockAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnblockAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServiceServer).UnblockAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SocialService_UnblockAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServiceServer).UnblockAccount(ctx, req.(*UnblockAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SocialService_ListBlocked_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBlockedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServiceServer).ListBlocked(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SocialService_ListBlocked_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServiceServer).ListBlocked(ctx, req.(*ListBlockedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SocialService_IsBlocked_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsBlockedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServiceServer).IsBlocked(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SocialService_IsBlocked_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServiceServer).IsBlocked(ctx, req.(*IsBlockedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SocialService_AreFriends_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AreFriendsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServiceServer).AreFriends(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SocialService_AreFriends_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServiceServer).AreFriends(ctx, req.(*AreFriendsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SocialService_GetFriendsOfFriends_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFriendsOfFriendsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServiceServer).GetFriendsOfFriends(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SocialService_GetFriendsOfFriends_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServiceServer).GetFriendsOfFriends(ctx, req.(*GetFriendsOfFriendsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SocialService_ServiceDesc is the grpc.ServiceDesc for SocialService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SocialService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "voice.social.v1.SocialService",
	HandlerType: (*SocialServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendFriendInvitation",
			Handler:    _SocialService_SendFriendInvitation_Handler,
		},
		{
			MethodName: "AcceptFriendInvitation",
			Handler:    _SocialService_AcceptFriendInvitation_Handler,
		},
		{
			MethodName: "DeclineFriendInvitation",
			Handler:    _SocialService_DeclineFriendInvitation_Handler,
		},
		{
			MethodName: "RemoveFriend",
			Handler:    _SocialService_RemoveFriend_Handler,
		},
		{
			MethodName: "ListFriends",
			Handler:    _SocialService_ListFriends_Handler,
		},
		{
			MethodName: "ListFriendRequests",
			Handler:    _SocialService_ListFriendRequests_Handler,
		},
		{
			MethodName: "AddContact",
			Handler:    _SocialService_AddContact_Handler,
		},
		{
			MethodName: "RemoveContact",
			Handler:    _SocialService_RemoveContact_Handler,
		},
		{
			MethodName: "ListContacts",
			Handler:    _SocialService_ListContacts_Handler,
		},
		{
			MethodName: "SyncPhoneContacts",
			Handler:    _SocialService_SyncPhoneContacts_Handler,
		},
		{
			MethodName: "SetFavorite",
			Handler:    _SocialService_SetFavorite_Handler,
		},
		{
			MethodName: "ListFavorites",
			Handler:    _SocialService_ListFavorites_Handler,
		},
		{
			MethodName: "BlockAccount",
			Handler:    _SocialService_BlockAccount_Handler,
		},
		{
			MethodName: "UnblockAccount",
			Handler:    _SocialService_UnblockAccount_Handler,
		},
		{
			MethodName: "ListBlocked",
			Handler:    _SocialService_ListBlocked_Handler,
		},
		{
			MethodName: "IsBlocked",
			Handler:    _SocialService_IsBlocked_Handler,
		},
		{
			MethodName: "AreFriends",
			Handler:    _SocialService_AreFriends_Handler,
		},
		{
			MethodName: "GetFriendsOfFriends",
			Handler:    _SocialService_GetFriendsOfFriends_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "voice/social/v1/social.proto",
}
